-- =====================================================================
-- 02_sequence.sql - sanction 계정으로 접속 후 실행
-- 매퍼 전수 조사에서 실제 NEXTVAL 호출이 확인된 시퀀스만 생성한다.
-- CSPD001TM/002TG/004TF/006TL/101TI/112TI 등은 MAX(col)+1 패턴을 쓰므로
-- 시퀀스를 만들지 않는다 (원본 로직 보존).
-- =====================================================================

CREATE SEQUENCE CSPD005TH_SG01 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CSPD008TH_SG01 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CSPD102TI_SG01 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CSPD103TI_SG01 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CSPD107TI_SG01 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CSPD110TI_SG01 START WITH 1 INCREMENT BY 1 NOCACHE;
