-- =====================================================================
-- 03_schema_reference.sql - sanction 계정
-- 참조/코드성 테이블 (업무 테이블이 FK로 참조하는 대상들을 먼저 생성)
-- 컬럼/타입은 MyBatis 매퍼 52개 전수 조사 결과(SELECT/INSERT/UPDATE에서
-- 실제로 쓰인 컬럼)를 근거로 함. 원본 DDL이 없어 타입은 컬럼명 규칙과
-- 매퍼 내 TO_CHAR/TO_DATE/비교연산 힌트로 추정한 최선 근사치이다.
-- =====================================================================

-- 공통코드 그룹
CREATE TABLE CSPD111TI (
    AI_INPT_GRP_CD      VARCHAR2(10)  NOT NULL,
    AI_INPT_GRP_NM      VARCHAR2(200),
    AI_INPT_GRP_STA_DTM VARCHAR2(14),
    AI_INPT_GRP_END_DTM VARCHAR2(14),
    AI_INPT_GRP_USG_YN  CHAR(1) DEFAULT 'Y',
    AI_INPT_RMRK_TXT    VARCHAR2(1000),
    TRN_LOG_SRNO        VARCHAR2(20),
    LST_DB_CHG_ID       VARCHAR2(30),
    LST_DB_CHG_DTM      VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),
    CONSTRAINT PK_CSPD111TI PRIMARY KEY (AI_INPT_GRP_CD)
);
COMMENT ON TABLE CSPD111TI IS '공통코드 그룹';

-- 공통코드
CREATE TABLE CSPD112TI (
    AI_INPT_GRP_CD      VARCHAR2(10)  NOT NULL,
    AI_INPT_CMN_CD      VARCHAR2(10)  NOT NULL,
    AI_INPT_CMN_CD_NM   VARCHAR2(200),
    AI_INPT_CMN_CD_ENG_NM VARCHAR2(200),
    AI_INPT_CMN_USG_YN  CHAR(1) DEFAULT 'Y',
    AI_INPT_SORT_SEQ    NUMBER,
    AI_INPT_INTF_ITM_NM VARCHAR2(200),
    AI_INPT_RMRK_TXT    VARCHAR2(1000),
    TRN_LOG_SRNO        VARCHAR2(20),
    LST_DB_CHG_ID       VARCHAR2(30),
    LST_DB_CHG_DTM      VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),
    CONSTRAINT PK_CSPD112TI PRIMARY KEY (AI_INPT_GRP_CD, AI_INPT_CMN_CD),
    CONSTRAINT FK_CSPD112TI_GRP FOREIGN KEY (AI_INPT_GRP_CD) REFERENCES CSPD111TI(AI_INPT_GRP_CD)
);
COMMENT ON TABLE CSPD112TI IS '공통코드 상세 (업무구분150/심사결과170/QA결과190/프로세스280/액티비티290/이력상태300/권한120 등)';

-- 국가
CREATE TABLE CSPD115TI (
    NACD               VARCHAR2(4) NOT NULL,
    NUTP_NACD          VARCHAR2(4),
    KORL_NL_NM         VARCHAR2(100),
    ENG_NL_NM          VARCHAR2(100),
    KORL_NL_ABRV_NM    VARCHAR2(50),
    ENG_NL_ABRV_NM     VARCHAR2(50),
    RPRS_CD_YN         CHAR(1) DEFAULT 'Y',
    CONSTRAINT PK_CSPD115TI PRIMARY KEY (NACD)
);
COMMENT ON TABLE CSPD115TI IS '국가코드';

-- 도시
CREATE TABLE CSPD118TI (
    CITY_SRNO          NUMBER NOT NULL,
    CITY_PORT_DSCD     VARCHAR2(4),
    ENG_CITY_NM        VARCHAR2(200),
    NACD               VARCHAR2(4),
    ENG_CITY_RGN_NM    VARCHAR2(200),
    CONSTRAINT PK_CSPD118TI PRIMARY KEY (CITY_SRNO),
    CONSTRAINT FK_CSPD118TI_NACD FOREIGN KEY (NACD) REFERENCES CSPD115TI(NACD)
);
COMMENT ON TABLE CSPD118TI IS '도시코드';

-- 영업일
CREATE TABLE CSPD118TM (
    BAS_DT             VARCHAR2(8) NOT NULL,
    WKD_CD             VARCHAR2(4),
    HLDY_DSCD          VARCHAR2(4),
    HLDY_TXT           VARCHAR2(200),
    TRN_LOG_SRNO       VARCHAR2(20),
    CONSTRAINT PK_CSPD118TM PRIMARY KEY (BAS_DT)
);
COMMENT ON TABLE CSPD118TM IS '영업일(휴일) 기준';

-- 메뉴 (계층형, CONNECT BY PRIOR)
CREATE TABLE CSPD108TI (
    AI_INPT_MENU_ID      VARCHAR2(20) NOT NULL,
    AI_INPT_MENU_NO      NUMBER,
    AI_INPT_MENU_NM      VARCHAR2(200),
    AI_INPT_HGRN_MENU_ID VARCHAR2(20),
    AI_INPT_MENU_URL_NM  VARCHAR2(500),
    AI_INPT_MGPE_YN      CHAR(1) DEFAULT 'N',
    TRN_LOG_SRNO         VARCHAR2(20),
    LST_DB_CHG_ID        VARCHAR2(30),
    LST_DB_CHG_DTM       VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),
    CONSTRAINT PK_CSPD108TI PRIMARY KEY (AI_INPT_MENU_ID),
    CONSTRAINT FK_CSPD108TI_PARENT FOREIGN KEY (AI_INPT_HGRN_MENU_ID) REFERENCES CSPD108TI(AI_INPT_MENU_ID)
);
COMMENT ON TABLE CSPD108TI IS '메뉴 (자기참조 계층형)';

-- 권한별 메뉴 사용여부
CREATE TABLE CSPD109TI (
    AI_INPT_MENU_ID    VARCHAR2(20) NOT NULL,
    AI_INPT_AUT_CD     VARCHAR2(4)  NOT NULL,
    AI_INPT_AUT_USG_YN CHAR(1) DEFAULT 'Y',
    CONSTRAINT PK_CSPD109TI PRIMARY KEY (AI_INPT_MENU_ID, AI_INPT_AUT_CD),
    CONSTRAINT FK_CSPD109TI_MENU FOREIGN KEY (AI_INPT_MENU_ID) REFERENCES CSPD108TI(AI_INPT_MENU_ID)
);
COMMENT ON TABLE CSPD109TI IS '권한별 메뉴 사용여부';

-- 사용자
CREATE TABLE CSPD101TI (
    AI_INPT_USER_ID       VARCHAR2(30) NOT NULL,
    AI_INPT_USER_ENO      VARCHAR2(20),
    AI_INPT_USER_NM       VARCHAR2(100),
    AI_INPT_USER_FA_RE_YN CHAR(1) DEFAULT 'N',
    AI_INPT_AUT_CD        VARCHAR2(4),
    AI_INPT_SNPE_ENO      VARCHAR2(20),
    AI_INPT_USER_YN       CHAR(1) DEFAULT 'Y',
    AI_INPT_MGPE_YN       CHAR(1) DEFAULT 'N',
    AI_INPT_USER_RGS_DTM  VARCHAR2(20),
    AI_INPT_USER_END_DTM  VARCHAR2(20),
    AI_INPT_SRVC_USER_DSCD VARCHAR2(4),
    TRN_LOG_SRNO          VARCHAR2(20),
    LST_DB_CHG_ID         VARCHAR2(30),
    LST_DB_CHG_DTM        VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),
    CONSTRAINT PK_CSPD101TI PRIMARY KEY (AI_INPT_USER_ID)
);
COMMENT ON TABLE CSPD101TI IS '사용자 (심사자/결재자/QA/관리자, AI_INPT_AUT_CD: 01=S1심사자,02=S2결재자,03=QA,04=일반)';

-- WatchList 카테고리/그룹/항목
CREATE TABLE CSPD102TI (
    AI_INPT_CTGR_ID      NUMBER NOT NULL,
    CTGR_CFCD            VARCHAR2(10),
    AI_INPT_CTGR_NM      VARCHAR2(200),
    AI_INPT_CTGR_TXT     VARCHAR2(1000),
    AI_INPT_CTGR_YN      CHAR(1) DEFAULT 'Y',
    AI_INPT_CTGR_RGS_DTM VARCHAR2(20),
    AI_INPT_CTGR_END_DTM VARCHAR2(20),
    TRN_LOG_SRNO         VARCHAR2(20),
    LST_DB_CHG_ID        VARCHAR2(30),
    LST_DB_CHG_DTM       VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),
    CONSTRAINT PK_CSPD102TI PRIMARY KEY (AI_INPT_CTGR_ID)
);
COMMENT ON TABLE CSPD102TI IS 'WatchList 카테고리';

CREATE TABLE CSPD103TI (
    AI_INPT_CTGR_ID      NUMBER NOT NULL,
    AI_INPT_LIST_ID      NUMBER NOT NULL,
    AI_INPT_LIST_NM      VARCHAR2(200),
    AI_INPT_LIST_DES_TXT VARCHAR2(1000),
    AI_INPT_LIST_YN      CHAR(1) DEFAULT 'Y',
    AI_INPT_LIST_RGS_DTM VARCHAR2(20),
    AI_INPT_LIST_END_DTM VARCHAR2(20),
    CONSTRAINT PK_CSPD103TI PRIMARY KEY (AI_INPT_CTGR_ID, AI_INPT_LIST_ID),
    CONSTRAINT FK_CSPD103TI_CTGR FOREIGN KEY (AI_INPT_CTGR_ID) REFERENCES CSPD102TI(AI_INPT_CTGR_ID)
);
COMMENT ON TABLE CSPD103TI IS 'WatchList 그룹';

CREATE TABLE CSPD104TI (
    AI_INPT_LIST_ID       NUMBER NOT NULL,
    AI_INPT_RSPT_TXT_SRNO NUMBER NOT NULL,
    AI_INPT_RSPT_TXT_DES_TXT VARCHAR2(1000),
    AI_INPT_RSPT_TXT_YN   CHAR(1) DEFAULT 'Y',
    AI_INPT_CTGR_ID       NUMBER,
    TRN_LOG_SRNO          VARCHAR2(20),
    LST_DB_CHG_ID         VARCHAR2(30),
    LST_DB_CHG_DTM        VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),
    CONSTRAINT PK_CSPD104TI PRIMARY KEY (AI_INPT_LIST_ID, AI_INPT_RSPT_TXT_SRNO),
    CONSTRAINT FK_CSPD104TI_LIST FOREIGN KEY (AI_INPT_CTGR_ID, AI_INPT_LIST_ID) REFERENCES CSPD103TI(AI_INPT_CTGR_ID, AI_INPT_LIST_ID)
);
COMMENT ON TABLE CSPD104TI IS 'WatchList 항목(제재대상 텍스트)';

-- 제재 Rule 1/2/3
CREATE TABLE CSPD105TI (
    AI_INPT_SNRL1_ID   NUMBER NOT NULL,
    AI_INPT_SNRL1_NM   VARCHAR2(200),
    AI_INPT_RULE_DSCD  VARCHAR2(4),
    INPT_SANCTION_NO   NUMBER,
    AI_INPT_LIST_ID    NUMBER,
    CONSTRAINT PK_CSPD105TI PRIMARY KEY (AI_INPT_SNRL1_ID)
);
COMMENT ON TABLE CSPD105TI IS '제재 Rule1';

CREATE TABLE CSPD106TI (
    AI_INPT_SNRL2_ID   NUMBER NOT NULL,
    AI_INPT_SNRL2_NM   VARCHAR2(200),
    AI_INPT_RULE_DSCD  VARCHAR2(4),
    INPT_SANCTION1_NO  NUMBER,
    INPT_SANCTION2_NO  NUMBER,
    INPT_SANCTION3_NO  NUMBER,
    INPT_SANCTION4_NO  NUMBER,
    AI_INPT_LIST1_ID   NUMBER,
    AI_INPT_LIST2_ID   NUMBER,
    AI_INPT_LIST3_ID   NUMBER,
    AI_INPT_LIST4_ID   NUMBER,
    CONSTRAINT PK_CSPD106TI PRIMARY KEY (AI_INPT_SNRL2_ID)
);
COMMENT ON TABLE CSPD106TI IS '제재 Rule2';

CREATE TABLE CSPD113TI (
    AI_INPT_SNRL3_ID    NUMBER NOT NULL,
    AI_INPT_SNRL3_NM    VARCHAR2(200),
    AI_INPT_RSPT_SQL_TXT CLOB,
    AI_INPT_SQL_USG_YN  CHAR(1) DEFAULT 'Y',
    CONSTRAINT PK_CSPD113TI PRIMARY KEY (AI_INPT_SNRL3_ID)
);
COMMENT ON TABLE CSPD113TI IS '제재 Rule3 (동적 SQL 텍스트 보관)';

CREATE TABLE CSPD116TI (
    AI_INPT_RULE_DSCD     VARCHAR2(4) NOT NULL,
    AI_INPT_WORD_ACRD_RT  NUMBER,
    AI_INPT_SNRL2_USG_YN  CHAR(1) DEFAULT 'Y',
    AI_INPT_SNRL3_USG_YN  CHAR(1) DEFAULT 'Y',
    CONSTRAINT PK_CSPD116TI PRIMARY KEY (AI_INPT_RULE_DSCD)
);
COMMENT ON TABLE CSPD116TI IS '제재 공통설정';

-- AI 용어사전
CREATE TABLE CSPD117TI (
    AI_INPT_WORD_SRNO   NUMBER NOT NULL,
    AI_INPT_GRP_CD      VARCHAR2(10) NOT NULL,
    AI_INPT_WORD_TXT    CLOB,
    AI_INPT_WORD_INF_NM VARCHAR2(200),
    AI_INPT_RMRK_TXT    VARCHAR2(1000),
    CONSTRAINT PK_CSPD117TI PRIMARY KEY (AI_INPT_WORD_SRNO, AI_INPT_GRP_CD)
);
COMMENT ON TABLE CSPD117TI IS 'AI 용어사전';

-- 결재의견 (사전 정의 코멘트)
CREATE TABLE CSPD110TI (
    AI_INPT_APPV_OPI_SRNO NUMBER NOT NULL,
    AI_INPT_APPV_OPI_USG_YN CHAR(1) DEFAULT 'Y',
    AI_INPT_APPV_OPI_TXT  VARCHAR2(1000),
    CONSTRAINT PK_CSPD110TI PRIMARY KEY (AI_INPT_APPV_OPI_SRNO)
);
COMMENT ON TABLE CSPD110TI IS '결재의견 사전정의';

-- QA 대상 선정 관리
CREATE TABLE CSPD107TI (
    QLAS_SLT_MNG_ID       NUMBER NOT NULL,
    AI_INPT_IMEX_DSCD     VARCHAR2(4),
    QLAS_ITM_TOT_CNT      NUMBER,
    QLAS_VOLN_CHC_CNT     NUMBER,
    QLAS_SLBS_VLD_YN      CHAR(1) DEFAULT 'Y',
    AI_INPT_LIST_ID       NUMBER,
    INPT_SANCTION_NO      NUMBER,
    QLAS_SLT_RGS_DTM      VARCHAR2(20),
    QLAS_SLT_END_DTM      VARCHAR2(20),
    CONSTRAINT PK_CSPD107TI PRIMARY KEY (QLAS_SLT_MNG_ID)
);
COMMENT ON TABLE CSPD107TI IS 'QA 대상 선정 관리(QA Rule)';
