-- =====================================================================
-- 05_code_data.sql - sanction 계정
-- 공통코드(CSPD111TI/112TI) 시드 데이터.
-- 그룹코드 번호 자체는 전부 실제 Java 컨트롤러(setAiInptGrpCd) /
-- MyBatis 매퍼의 리터럴 비교에서 확인된 값만 사용한다 (임의 그룹 추가 금지).
-- 코드값(도메인)이 주석/문서에서 명시적으로 확인된 것은 그대로 반영했고,
-- 근거를 찾지 못한 그룹은 최소 셋만 채워 화면이 비지 않게 하되
-- [검증필요] 주석을 남긴다 (STEP 8 화면 검증 시 실제 표시값과 대조).
-- =====================================================================

-- ---- 그룹 정의 ----
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('100','업무유형',           'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('120','사용자 권한코드',       'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('121','상세권한',           'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('140','결재상태코드(APPV_STCD)', 'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('150','심사 업무구분(수입/수출/QA)', 'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('170','심사결과코드',         'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('190','QA결과코드',           'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('200','제재 Rule 구분',       'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('230','항목심사 공통코드(수출)', 'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('240','항목심사 공통코드(수입)', 'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('250','SW검사항목(수출)',      'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('260','SW검사항목(수입)',      'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('280','QA 대상선정 분류(QA_PRCS_CD)', 'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('290','심사 액티비티코드(ACVT_CD)', 'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('300','진행 이력상태코드',     'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('310','업무일지구분',         'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('320','업무마감구분',         'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('321','업무마감세부구분',      'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('322','심사자동화업무구분',     'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('323','업무일지세부구분',      'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('350','통계 조회구분',        'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('360','통계 항목구분',        'Y');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_USG_YN) VALUES ('905','항구/도시 구분',        'Y');

-- ---- 120: 사용자 권한코드 (AdminLogLoginController.java:30, AdminReTask_SQL.xml WHEN 절 근거) ----
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('120','01','심사자(S1)', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('120','02','결재자(S2)', 2);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('120','03','QA',        3);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('120','04','관리자',    4);

-- ---- 150: 업무구분 (QaTargetBatchController.java:87 주석 근거: 1=수입,2=수출,3=QA) ----
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('150','1','수입', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('150','2','수출', 2);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('150','3','QA',   3);

-- ---- 280: QA 대상선정 분류 (QaTargetBatchController.java:68 주석 근거) ----
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('280','3','QA TotalText', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('280','4','QA 항목심사',   2);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('280','5','QA SafeWatch',  3);

-- ---- 290: 심사 액티비티코드 (AdminReTask_SQL.xml, AppTodo_SQL.xml, AdminStatus_SQL.xml 리터럴 근거) ----
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('290','10','접수',              1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('290','40','재추출',            4);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('290','70','재심사',            7);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('290','80','심사중(배정)',       8);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('290','90','심사중(진행)',       9);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('290','100','결재상신',         10);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('290','110','자체점검 시행(QA진행)', 11);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('290','120','점검결과 확인 및 결재(QA결재대기)', 12);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('290','130','결재중(QA결재상신)', 13);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('290','140','Block',            14);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('290','160','완료(승인)',        16);

-- ---- 140: 결재상태코드 (AppStatus/CommonRevertDetail/QaTargetBatch/TaskLogInquiry 리터럴 근거) ----
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('140','50','미상신',   5);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('140','110','상신',    11);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('140','120','반려',    12);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('140','130','결재대기', 13);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('140','140','Block',   14);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('140','160','승인',    16);

-- ---- 905: 항구/도시 구분 (AdminCityController.java:29 근거, 값은 [검증필요]) ----
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('905','1','항구', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('905','2','공항', 2);

-- ---- 322: 심사자동화업무구분 (TaskLogRegController.java:30 근거, 값은 [검증필요]) ----
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('322','1','정상처리', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('322','2','오류',    2);

-- ---- 나머지 그룹(100,121,170,190,200,230,240,250,260,300,310,320,321,323,350,360)은
--      화면 검증(STEP 8) 단계에서 실제 조회 결과와 대조하며 채운다. 최소 1건씩만 선삽입. [검증필요]
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('100','1','일반', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('121','1','조회', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('170','1','정상', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('190','1','정상', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('200','1','WatchList', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('300','1','정상', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('310','1','업무일지', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('320','1','마감', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('321','1','마감상세', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('323','1','일지상세', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('350','1','전체', 1);
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_SORT_SEQ) VALUES ('360','1','전체', 1);

-- ---- 국가 (최소 셋 — WatchList/원장 FK 대상) ----
INSERT INTO CSPD115TI (NACD, KORL_NL_NM, ENG_NL_NM, RPRS_CD_YN) VALUES ('KR','대한민국','KOREA, REPUBLIC OF','Y');
INSERT INTO CSPD115TI (NACD, KORL_NL_NM, ENG_NL_NM, RPRS_CD_YN) VALUES ('US','미국','UNITED STATES','Y');
INSERT INTO CSPD115TI (NACD, KORL_NL_NM, ENG_NL_NM, RPRS_CD_YN) VALUES ('CN','중국','CHINA','Y');
INSERT INTO CSPD115TI (NACD, KORL_NL_NM, ENG_NL_NM, RPRS_CD_YN) VALUES ('IR','이란','IRAN','Y');
INSERT INTO CSPD115TI (NACD, KORL_NL_NM, ENG_NL_NM, RPRS_CD_YN) VALUES ('KP','북한','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF','Y');
INSERT INTO CSPD115TI (NACD, KORL_NL_NM, ENG_NL_NM, RPRS_CD_YN) VALUES ('RU','러시아','RUSSIAN FEDERATION','Y');

-- ---- 도시 ----
INSERT INTO CSPD118TI (CITY_SRNO, CITY_PORT_DSCD, ENG_CITY_NM, NACD, ENG_CITY_RGN_NM) VALUES (1,'1','BUSAN','KR','BUSAN');
INSERT INTO CSPD118TI (CITY_SRNO, CITY_PORT_DSCD, ENG_CITY_NM, NACD, ENG_CITY_RGN_NM) VALUES (2,'1','LOS ANGELES','US','CALIFORNIA');
INSERT INTO CSPD118TI (CITY_SRNO, CITY_PORT_DSCD, ENG_CITY_NM, NACD, ENG_CITY_RGN_NM) VALUES (3,'1','SHANGHAI','CN','SHANGHAI');

-- ---- 영업일 (SYSDATE 기준 -60일 ~ +30일, 토/일만 휴일 처리, 로컬 테스트용) ----
-- 06_sample_data.sql 의 접수일자(INPT_RCP_DT)가 SYSDATE 기준 상대일자로 생성되므로
-- 실행 시점이 언제든(오늘 날짜가 바뀌어도) 영업일 테이블이 그 범위를 항상 커버하도록
-- 고정 날짜 대신 SYSDATE 기준 범위로 생성한다.
BEGIN
  FOR i IN -60..30 LOOP
    DECLARE
      d DATE := TRUNC(SYSDATE) + i;
      wd NUMBER := TO_NUMBER(TO_CHAR(d,'D')); -- 1=Sun..7=Sat (NLS 기본)
      is_hldy CHAR(1);
    BEGIN
      IF wd IN (1,7) THEN is_hldy := 'Y'; ELSE is_hldy := 'N'; END IF;
      INSERT INTO CSPD118TM (BAS_DT, WKD_CD, HLDY_DSCD, HLDY_TXT)
      VALUES (TO_CHAR(d,'YYYYMMDD'), TO_CHAR(d,'D'), is_hldy, CASE WHEN is_hldy='Y' THEN '주말' ELSE NULL END);
    END;
  END LOOP;
END;
/

-- ---- 메뉴 ----
-- CommonMenu_SQL.xml selectList 의 실제 로직에 맞춘 구조 (CommonMenuApiController 경유):
--  * 최상위(부모) 메뉴는 AI_INPT_MENU_NO 가 NULL 이어야 하고, ID 가 반드시
--    '100000','200000','300000','400000','500000' 중 하나여야만 화면에 노출된다.
--    (해당 집합 밖의 ID는 CASE 문에서 무조건 'N' 처리되어 걸러짐 - 쿼리 하드코딩)
--  * '000000' 은 쿼리에서 명시적으로 제외된다(홈/로고 등 별도 처리 영역으로 추정).
--  * 각 메뉴는 CSPD109TI 에 "보여줄 권한코드(120그룹)"별로 행이 있어야 하고,
--    자식 메뉴가 최소 1개는 해당 권한에 노출(USG_YN='Y') 되어야 부모도 노출된다.
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('100000',NULL,'심사',       NULL,     NULL,          'N');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('101000',1,       '심사 ToDo',  '100000', '/app/todo',   'N');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('102000',2,       '심사 현황',  '100000', '/app/status', 'N');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('200000',NULL,'QA',        NULL,     NULL,          'N');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('201000',1,       'QA ToDo',    '200000', '/qa/todo',    'N');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('202000',2,       'QA 현황',    '200000', '/qa/status',  'N');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('300000',NULL,'현황/통계', NULL,     NULL,          'N');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('301000',1,       '심사 통계',  '300000', '/stat/task',  'N');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('400000',NULL,'업무일지',  NULL,     NULL,          'N');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('401000',1,       '업무일지 ToDo','400000','/revert/todo','N');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('500000',NULL,'관리자',    NULL,     NULL,          'Y');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('501000',1,       '사용자 관리','500000', '/admin/user', 'Y');
INSERT INTO CSPD108TI (AI_INPT_MENU_ID, AI_INPT_MENU_NO, AI_INPT_MENU_NM, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN) VALUES ('502000',2,       '공통코드 관리','500000','/admin/code','Y');

-- 권한별 노출(CSPD109TI): 120그룹 코드 01=심사자,02=결재자,03=QA,04=일반/관리자
-- 심사 메뉴: 심사자만
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN) VALUES ('100000','01','Y');
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN) VALUES ('101000','01','Y');
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN) VALUES ('102000','01','Y');
-- QA 메뉴: QA담당자 + QA결재자(결재자권한)
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN) VALUES ('200000','03','Y');
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN) VALUES ('201000','03','Y');
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN) VALUES ('202000','03','Y');
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN) VALUES ('200000','02','Y');
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN) VALUES ('202000','02','Y');
-- 현황/통계, 업무일지: 전체 권한 공통 노출
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN)
SELECT M.AI_INPT_MENU_ID, AUT.AI_INPT_CMN_CD, 'Y'
FROM (SELECT '300000' AI_INPT_MENU_ID FROM DUAL UNION ALL SELECT '301000' FROM DUAL
      UNION ALL SELECT '400000' FROM DUAL UNION ALL SELECT '401000' FROM DUAL) M,
     (SELECT AI_INPT_CMN_CD FROM CSPD112TI WHERE AI_INPT_GRP_CD='120') AUT;
-- 관리자 메뉴: MGPE_YN='Y' 인 사용자(관리자)만 실제로 보이지만, 쿼리 구조상
-- 로그인 사용자의 AUT_CD 로도 CSPD109TI 조인이 필요하므로 04(일반/관리자)에 등록
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN) VALUES ('500000','04','Y');
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN) VALUES ('501000','04','Y');
INSERT INTO CSPD109TI (AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN) VALUES ('502000','04','Y');

COMMIT;
