#\uac1c\ubc1c\ubaa8\ub4dc
mode=dev
modeName=\uac1c\ubc1c

#\ub3c4\uba54\uc778
domain=https://sanctiond.woorifg.com:8080

#\ud3ec\ud138\ub85c\uadf8\uc778
portal.login=http://wepwebt.woorifg.com

#\ud3ec\ud138\ud504\ub85d\uc2dc
portal.prc=http://wsypxyt.woorifg.com:7781/sanction/sso/prx

#\uc2b9\uc778\uc5ec\ubd80 \uccb4\ud06c
check.approve.yn=Y

#\uadf8\ub9ac\ub4dc \uc18d\uc131
grid.height=438

#BPR \uc774\ubbf8\uc9c0
bpr.url=http://wbbprt.woorifg.com/web/jsp/bprInbCall.jsp?bprScrnNo=BTR000990051&imgKeyNo=

#\ud30c\uc77c\uc5c5\ub85c\ub4dc
#upload.path=/home/aisac/apps/resources/files/
upload.path=/home/aisac/
upload.path.down=/home/aisac/tmp/
upload.url=/files/
upload.exts=txt,pptx,ppt,xlsx,xls,pdf,doc,docx,json,jpg,png,gif,bmp
upload.maxSize=20971520

#\uc2ec\uc0ac\uc0c1\uc138\uad00\ub828
img.url=http://10.232.181.108:10917/sa/g001
file.upload=http://10.232.181.108:10917/aisac/file/upload
file.download=http://10.232.181.108:10917/aisac/file/download
file.delete=http://10.232.181.108:10917/aisac/file/delete
extraction.url=http://10.232.181.108:8096/extraction
inspection.url=http://10.232.181.108:8093/inspection

# sso \ud1b5\ud569 \ub85c\uadf8\uc778 \uad00\ub828
sso.enc.key=!sanction.woori!

# QA \ubc30\uce58\uc2dc\uac04
batchTime.qa=0 0 6 * * *

# \uc5c5\ubb34\ub9c8\uac10 \ubc30\uce58\uc2dc\uac04
batchTime.taskEnd=0 30 23 * * *

# \uba54\ub274\uc5bc \uc11c\ubc84 \uc800\uc7a5 \ub9c1\ud06c
manual.path.linkFlag1=/home/aisac/apps/resources/files/manual/linkFlag1.pdf
manual.path.linkFlag2=/home/aisac/apps/resources/files/manual/linkFlag2.pdf
manual.path.linkFlag3=/home/aisac/apps/resources/files/manual/linkFlag3.pdf

# \uba54\ub274\uc5bc \ub2e4\uc6b4\ub85c\ub4dc \ud30c\uc77c\uba85
manual.name.linkFlag1=\uc0ac\uc6a9\uc790\ub9e4\ub274\uc5bc_part1_(\uc2ec\uc0ac,\uacb0\uc7ac).pdf
manual.name.linkFlag2=\uc0ac\uc6a9\uc790\ub9e4\ub274\uc5bc_part2_(\uc870\ud68c,\ub9c8\uac10,\ud1b5\uacc4).pdf
manual.name.linkFlag3=\uc0ac\uc6a9\uc790\ub9e4\ub274\uc5bc_part3_(\uc124\uc815,\uad00\ub9ac).pdf