#개발모드
mode=local
modeName=로컬

#도메인
domain=http://localhost:8080

#포털로그인
portal.login=http://wepwebt.woorifg.com

#포털프록시
portal.prc=http://wsypxyt.woorifg.com:7781/sanction/login/sso/prx

#승인여부 체크
check.approve.yn=Y

#그리드 속성
grid.height=438

#BPR 이미지
bpr.url=http://wbbprt.woorifg.com/web/jsp/bprInbCall.jsp?bprScrnNo=BTR000990051&imgKeyNo=

#파일업로드
upload.path=C:\\eGovFrameDev-3.8.0-32bit\\workspace\\egov_ui\\src\\main\\webapp\\resources\\files\\
upload.url=/files/
upload.exts=txt,pptx,ppt,xlsx,xls,pdf,doc,docx,json,jpg,png,gif,bmp
upload.maxSize=20971520

#심사상세관련
img.url=http://10.232.181.108:10917/sa/g001
file.upload=http://10.232.181.108:10917/aisac/file/upload
file.download=http://10.232.181.108:10917/aisac/file/download
file.delete=http://10.232.181.108:10917/aisac/file/delete
extraction.url=http://10.232.181.108:8096/extraction
inspection.url=http://10.232.181.108:8093/inspection

# sso 통합 로그인 관련
sso.enc.key=!sanction.woori!