#!/usr/bin/env python3
"""
문서분류 테스트 코드·룰 유틸리티

근거: sql/doc_class_rules.json (12_문서분류내용.md 기반)

사용 예:
  python scripts/doc_class_rules.py list
  python scripts/doc_class_rules.py parse 10001061
  python scripts/doc_class_rules.py titles 01
  python scripts/doc_class_rules.py sql-codes
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RULES_PATH = ROOT / "sql" / "doc_class_rules.json"

TASK_ID_RE = re.compile(r"^(\d{5})(0[1-9]|1[0-3]|99)(\d+)$")


def load_rules() -> dict:
    with RULES_PATH.open(encoding="utf-8") as f:
        return json.load(f)


def category_by_code(rules: dict, code: str) -> dict | None:
    for cat in rules["categories"]:
        if cat["imexHisCd"] == code:
            return cat
    return None


def parse_task_id(task_id: str) -> dict:
    m = TASK_ID_RE.match(str(task_id).strip())
    if not m:
        raise ValueError(f"Task ID 형식 불일치: {task_id} (규칙: {{MST}}{{IMEX_HIS_CD}}{{PAGE}})")
    mst, code, page = m.group(1), m.group(2), m.group(3)
    rules = load_rules()
    cat = category_by_code(rules, code)
    return {
        "taskId": task_id,
        "inptMstSrno": int(mst),
        "imexHisCd": code,
        "page": int(page),
        "label": cat["intfItmNm"] if cat else "Unknown",
        "abbr": cat["abbr"] if cat else "",
    }


def emit_sql_codes() -> str:
    rules = load_rules()
    lines = ["-- generated by scripts/doc_class_rules.py"]
    seq_base = 25
    for i, cat in enumerate(rules["categories"]):
        if cat["imexHisCd"] == "99":
            trn = "29"
        else:
            trn = str(seq_base + i)
        lines.append(
            "INSERT INTO CSPD112TI (...) VALUES ("
            f"'100', '{cat['imexHisCd']}', '{cat['nameKr']}', '{cat['nameEn']}', "
            f"'20200101000000', '99991231235959', 'Y', '{cat['abbr']}', "
            f"'{cat['intfItmNm']}', '{cat['seq']}', '{trn}', 'SYSTEM', '20250115120000');"
        )
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 1

    cmd = argv[1]
    rules = load_rules()

    if cmd == "list":
        print(f"{'CD':<4} {'약어':<6} {'표시명':<14} {'한글그룹':<12} OCR제목수")
        print("-" * 55)
        for cat in rules["categories"]:
            print(
                f"{cat['imexHisCd']:<4} {cat['abbr']:<6} {cat['intfItmNm']:<14} "
                f"{cat['groupKr']:<12} {len(cat.get('ocrTitles', []))}"
            )
        return 0

    if cmd == "parse" and len(argv) >= 3:
        info = parse_task_id(argv[2])
        print(json.dumps(info, ensure_ascii=False, indent=2))
        return 0

    if cmd == "titles" and len(argv) >= 3:
        cat = category_by_code(rules, argv[2].zfill(2) if len(argv[2]) == 1 else argv[2])
        if not cat:
            print(f"코드 없음: {argv[2]}")
            return 1
        for title in cat.get("ocrTitles", []):
            print(title)
        return 0

    if cmd == "sql-codes":
        print(emit_sql_codes())
        return 0

    print(f"알 수 없는 명령: {cmd}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
