-- ============================================================
-- AI 심사 시스템 DDL (Tibero/Oracle)
-- Source: 테이블정의서_추출.xlsx + MyBatis Mapper 분석
-- 실행 순서: 00_drop → 01_ddl → 02_sequence → 03_test_data
--            → 26_task_auth_v2.sql (사용자 권한 테이블·시드)
--            → 27_qa_integ_v2.sql → 28_annotation.sql (형광펜·핀)
--            → 29_item_val_seq.sql (항목심사 수기 행추가, 기존 DB ALTER)
--            → 07_menu_role_test_data → 04~06
-- 운영 기존 DB 권한 이관: 26 적용 후 → 30_task_auth_mig.sql
--            (docs/to-be/업무권한_TO-BE_데이터_마이그레이션.md)
--
-- 본 파일이 기본 스키마 정본. 과거 ALTER 패치(sql/archive)는 신규 설치에 불필요.
-- 사용자 권한(CSPD119~124,127 및 관련 ALTER)은 26_task_auth_v2.sql 에서 생성.
-- 흡수된 스키마:
--   CSPD003TF.AI_INPT_ALT_YN, X/Y 좌표 (구 12, 13)
--   CSPD004TF.ITM_INPT_NACRD_YN, ITM_INPT_HNDG_INP_DAT_TXT VARCHAR2(4000) (구 14, 25)
--   CSPD007TL.LST_DB_CHG_DTM (구 15)
--   CSPD201TM/202TM TRN_OPR_NO, INPT_ATMC_BIZ_DSCD, KRBR_NM, DACC_BRCD, CUS_ENG_NM (구 20)
--   CSPD201TM XPO_PTN_NACD/HS_CD, CSPD202TM XPO_NACD/HS_CD (구 24)
--   CSPD811TH.AI_INPT_CNCT_URL_NM (구 21)
--   CSPD900TI.AI_INPT_SVR_INF_TXT (구 22)
-- ============================================================

-- ------------------------------------------------------------
-- CSPD001TM: AI 심사 마스터
-- ------------------------------------------------------------
CREATE TABLE CSPD001TM (
    ACTL_FX_REFNO                    VARCHAR2(64),
    AI_INPT_ACVT_CD                  VARCHAR2(32),
    AI_INPT_APPV_STCD                VARCHAR2(32),
    AI_INPT_BUY_AM                   NUMBER(20,4),
    AI_INPT_DOC_SCAN_CHRG_ENO        VARCHAR2(64),
    AI_INPT_IMG_KEY_NO               VARCHAR2(64),
    AI_INPT_PROS_CD                  VARCHAR2(32),
    AI_INPT_QLAS_ACVT_CD             VARCHAR2(32),
    AI_INPT_QLAS_APPV_STCD           VARCHAR2(32),
    AI_INPT_QLAS_PROS_CD             VARCHAR2(32),
    AI_INPT_SNPE_ENO                 VARCHAR2(64),
    AI_INSPE_ENO                     VARCHAR2(64),
    ALERT_YN                         CHAR(1),
    FX_REFNO_SRNO                    NUMBER(19),
    IMEX_HIS_CD                      VARCHAR2(32),
    INPT_ATMC_BIZ_DSCD               VARCHAR2(32),
    INPT_BL_GRP_NO                   VARCHAR2(64),
    INPT_ELMT_ID                     VARCHAR2(64),
    INPT_MST_SRNO                    NUMBER(19),
    INPT_RCP_DT                      VARCHAR2(8),
    INPT_RCP_YM                      VARCHAR2(6),
    INPT_SANCTION_NM                 VARCHAR2(300),
    INPT_TASK_ID                     VARCHAR2(64),
    ITM_INPT_AI_INPT_RST_CD          VARCHAR2(32),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    PAPS_CLF_ERR_YN                  CHAR(1),
    PAPS_RE_SCAN_CMPL_YN             CHAR(1),
    PAPS_RE_SCAN_NED_YN              CHAR(1),
    QLAS_ALOC_DT                     VARCHAR2(8),
    QLAS_CRPE_ENO                    VARCHAR2(64),
    QLAS_PRG_YN                      CHAR(1),
    QLAS_SNPE_ENO                    VARCHAR2(64),
    QLT_GRN_AI_INPT_RST_CD           VARCHAR2(32),
    REPROC_CNT                       NUMBER(19),
    RESCAN_CNT                       NUMBER(19),
    SAFEWATCH_AI_INPT_RST_CD         VARCHAR2(32),
    TOTALTEXT_AI_INPT_RST_CD         VARCHAR2(32),
    TRN_LOG_SRNO                     VARCHAR2(60),
    INPT_ATMC_REQ_DSCD               VARCHAR2(32)
,
    CONSTRAINT PK_CSPD001TM PRIMARY KEY (INPT_MST_SRNO)
);

COMMENT ON TABLE CSPD001TM IS 'AI 심사 마스터';
COMMENT ON COLUMN CSPD001TM.ACTL_FX_REFNO IS '실제 외환 참조번호';
COMMENT ON COLUMN CSPD001TM.AI_INPT_ACVT_CD IS 'AI 심사 활동 코드';
COMMENT ON COLUMN CSPD001TM.AI_INPT_APPV_STCD IS 'AI 심사 승인 상태 코드';
COMMENT ON COLUMN CSPD001TM.AI_INPT_BUY_AM IS 'AI 심사 매입 금액';
COMMENT ON COLUMN CSPD001TM.AI_INPT_DOC_SCAN_CHRG_ENO IS 'AI 심사 문서 스캔 담당 직원번호';
COMMENT ON COLUMN CSPD001TM.AI_INPT_IMG_KEY_NO IS 'AI 심사 이미지 키 번호';
COMMENT ON COLUMN CSPD001TM.AI_INPT_PROS_CD IS 'AI 심사 프로세스 코드';
COMMENT ON COLUMN CSPD001TM.AI_INPT_QLAS_ACVT_CD IS 'AI 심사 QA 활동 코드';
COMMENT ON COLUMN CSPD001TM.AI_INPT_QLAS_APPV_STCD IS 'AI 심사 QA 승인 상태 코드';
COMMENT ON COLUMN CSPD001TM.AI_INPT_QLAS_PROS_CD IS 'AI 심사 QA 프로세스 코드';
COMMENT ON COLUMN CSPD001TM.AI_INPT_SNPE_ENO IS 'AI 심사 승인자 직원번호';
COMMENT ON COLUMN CSPD001TM.AI_INSPE_ENO IS 'AI 심사 검사자 직원번호';
COMMENT ON COLUMN CSPD001TM.ALERT_YN IS '알림 여부';
COMMENT ON COLUMN CSPD001TM.FX_REFNO_SRNO IS '외환 참조번호 일련번호';
COMMENT ON COLUMN CSPD001TM.IMEX_HIS_CD IS '수출입 이력 코드';
COMMENT ON COLUMN CSPD001TM.INPT_ATMC_BIZ_DSCD IS '심사 자동화 업무 구분 코드';
COMMENT ON COLUMN CSPD001TM.INPT_BL_GRP_NO IS '심사 B/L 그룹 번호';
COMMENT ON COLUMN CSPD001TM.INPT_ELMT_ID IS '심사 요소 ID';
COMMENT ON COLUMN CSPD001TM.INPT_MST_SRNO IS '심사 마스터 일련번호';
COMMENT ON COLUMN CSPD001TM.INPT_RCP_DT IS '심사 접수 일자';
COMMENT ON COLUMN CSPD001TM.INPT_RCP_YM IS '심사 접수 년월';
COMMENT ON COLUMN CSPD001TM.INPT_SANCTION_NM IS '심사 제재명';
COMMENT ON COLUMN CSPD001TM.INPT_TASK_ID IS '심사 작업 ID';
COMMENT ON COLUMN CSPD001TM.ITM_INPT_AI_INPT_RST_CD IS '항목별 AI 심사 결과 코드';
COMMENT ON COLUMN CSPD001TM.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD001TM.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD001TM.PAPS_CLF_ERR_YN IS '서류 분류 오류 여부';
COMMENT ON COLUMN CSPD001TM.PAPS_RE_SCAN_CMPL_YN IS '서류 재스캔 완료 여부';
COMMENT ON COLUMN CSPD001TM.PAPS_RE_SCAN_NED_YN IS '서류 재스캔 필요 여부';
COMMENT ON COLUMN CSPD001TM.QLAS_ALOC_DT IS 'QA 배정 일자';
COMMENT ON COLUMN CSPD001TM.QLAS_CRPE_ENO IS 'QA 처리자 직원번호';
COMMENT ON COLUMN CSPD001TM.QLAS_PRG_YN IS 'QA 진행 여부';
COMMENT ON COLUMN CSPD001TM.QLAS_SNPE_ENO IS 'QA 승인자 직원번호';
COMMENT ON COLUMN CSPD001TM.QLT_GRN_AI_INPT_RST_CD IS '품질보증 AI 심사 결과 코드';
COMMENT ON COLUMN CSPD001TM.REPROC_CNT IS '재처리 건수';
COMMENT ON COLUMN CSPD001TM.RESCAN_CNT IS '재스캔 건수';
COMMENT ON COLUMN CSPD001TM.SAFEWATCH_AI_INPT_RST_CD IS 'SafeWatch AI 심사 결과 코드';
COMMENT ON COLUMN CSPD001TM.TOTALTEXT_AI_INPT_RST_CD IS 'TotalText AI 심사 결과 코드';
COMMENT ON COLUMN CSPD001TM.TRN_LOG_SRNO IS '거래 로그 일련번호';
COMMENT ON COLUMN CSPD001TM.INPT_ATMC_REQ_DSCD IS '심사 자동화 요청 구분 코드';

-- ------------------------------------------------------------
-- CSPD002TG: 문서 및 이미지 그룹
-- ------------------------------------------------------------
CREATE TABLE CSPD002TG (
    AI_INPT_PAPS_QLT_SCRE            NUMBER(20,4),
    IMEX_HIS_CD                      VARCHAR2(32),
    INPT_BL_GRP_NO                   VARCHAR2(64),
    INPT_ELMT_ID                     VARCHAR2(64),
    INPT_MST_SRNO                    NUMBER(19),
    INPT_TASK_ID                     VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD002TG PRIMARY KEY (INPT_MST_SRNO, INPT_ELMT_ID, IMEX_HIS_CD)
);

COMMENT ON TABLE CSPD002TG IS '문서 및 이미지 그룹';
COMMENT ON COLUMN CSPD002TG.AI_INPT_PAPS_QLT_SCRE IS 'AI 심사 서류 품질 점수';
COMMENT ON COLUMN CSPD002TG.IMEX_HIS_CD IS '수출입 이력 코드';
COMMENT ON COLUMN CSPD002TG.INPT_BL_GRP_NO IS '심사 B/L 그룹 번호';
COMMENT ON COLUMN CSPD002TG.INPT_ELMT_ID IS '심사 요소 ID';
COMMENT ON COLUMN CSPD002TG.INPT_MST_SRNO IS '심사 마스터 일련번호';
COMMENT ON COLUMN CSPD002TG.INPT_TASK_ID IS '심사 작업 ID';
COMMENT ON COLUMN CSPD002TG.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD002TG.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD002TG.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD003TF: TotalText 추출 결과
-- ------------------------------------------------------------
CREATE TABLE CSPD003TF (
    AI_INPT_ALT_YN                   CHAR(1),
    AI_INPT_SANCTION_RULE_TXT        CLOB,
    AI_INPT_TOTALTEXT_RVSN_YN        CHAR(1),
    AI_INPT_TOTALTEXT_SRNO           NUMBER(19),
    BFRS_AICR_EXTC_TXT               CLOB,
    INPT_MST_SRNO                    NUMBER(19),
    INPT_SANCTION_DAT_TXT            VARCHAR2(4000),
    INPT_TASK_ID                     VARCHAR2(64),
    ITM_INPT_XAXIS_END_CRDN_CN       NUMBER(20,4),
    ITM_INPT_XAXIS_STA_CRDN_CN       NUMBER(20,4),
    ITM_INPT_YAXIS_END_CRDN_CN       NUMBER(20,4),
    ITM_INPT_YAXIS_STA_CRDN_CN       NUMBER(20,4),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64)
,
    CONSTRAINT PK_CSPD003TF PRIMARY KEY (INPT_MST_SRNO, AI_INPT_TOTALTEXT_SRNO)
);

COMMENT ON TABLE CSPD003TF IS 'TotalText 추출 결과';
COMMENT ON COLUMN CSPD003TF.AI_INPT_ALT_YN IS 'AI 심사 알림 여부';
COMMENT ON COLUMN CSPD003TF.AI_INPT_SANCTION_RULE_TXT IS 'AI 심사 제재 룰 내용';
COMMENT ON COLUMN CSPD003TF.AI_INPT_TOTALTEXT_RVSN_YN IS 'AI 심사 TotalText 보정 여부';
COMMENT ON COLUMN CSPD003TF.AI_INPT_TOTALTEXT_SRNO IS 'AI 심사 TotalText 일련번호';
COMMENT ON COLUMN CSPD003TF.BFRS_AICR_EXTC_TXT IS 'AI OCR 보정 전 추출 텍스트';
COMMENT ON COLUMN CSPD003TF.INPT_MST_SRNO IS '심사 마스터 일련번호';
COMMENT ON COLUMN CSPD003TF.INPT_SANCTION_DAT_TXT IS '심사 제재 데이터 내용';
COMMENT ON COLUMN CSPD003TF.INPT_TASK_ID IS '심사 작업 ID';
COMMENT ON COLUMN CSPD003TF.ITM_INPT_XAXIS_END_CRDN_CN IS '항목 X축 종료 좌표값';
COMMENT ON COLUMN CSPD003TF.ITM_INPT_XAXIS_STA_CRDN_CN IS '항목 X축 시작 좌표값';
COMMENT ON COLUMN CSPD003TF.ITM_INPT_YAXIS_END_CRDN_CN IS '항목 Y축 종료 좌표값';
COMMENT ON COLUMN CSPD003TF.ITM_INPT_YAXIS_STA_CRDN_CN IS '항목 Y축 시작 좌표값';
COMMENT ON COLUMN CSPD003TF.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD003TF.LST_DB_CHG_ID IS '최종 DB 변경 ID';

-- ------------------------------------------------------------
-- CSPD004TF: 제재 항목 탐지 데이터
-- ------------------------------------------------------------
CREATE TABLE CSPD004TF (
    AFRS_AICR_EXTC_TXT               CLOB,
    AFRS_TA_EXTC_TXT                 CLOB,
    AI_INPT_ALT_YN                   CHAR(1),
    AI_INPT_BUY_AM                   NUMBER(20,4),
    AI_INPT_EXTC_SNTN_TXT            CLOB,
    AI_INPT_SANCTION_RULE_TXT        CLOB,
    AI_INPT_WORD_ACRD_RT             NUMBER(20,4),
    BFRS_AICR_EXTC_TXT               CLOB,
    BFRS_TA_EXTC_TXT                 CLOB,
    INPT_ATMC_BIZ_DSCD               VARCHAR2(32),
    INPT_BL_GRP_NO                   VARCHAR2(64),
    INPT_MST_SRNO                    NUMBER(19),
    INPT_SANCTION_DAT_TXT            VARCHAR2(4000),
    INPT_SANCTION_NO                 NUMBER(19),
    INPT_TASK_ID                     VARCHAR2(64),
    ITM_INPT_VAL_SEQ                 NUMBER(5) DEFAULT 0 NOT NULL,
    ITM_INPT_SRC_DSCD                VARCHAR2(32) DEFAULT 'AI' NOT NULL,
    ITM_INPT_ADD_ROW_YN              CHAR(1) DEFAULT 'N' NOT NULL,
    ITM_INPT_HNDG_INP_DAT_TXT        VARCHAR2(4000),
    ITM_INPT_NACRD_YN                CHAR(1),
    ITM_INPT_RVSN_YN                 CHAR(1),
    ITM_INPT_XAXIS_END_CRDN_CN       NUMBER(20,4),
    ITM_INPT_XAXIS_STA_CRDN_CN       NUMBER(20,4),
    ITM_INPT_YAXIS_END_CRDN_CN       NUMBER(20,4),
    ITM_INPT_YAXIS_STA_CRDN_CN       NUMBER(20,4),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    SAFEWATCH_ITM_YN                 CHAR(1),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD004TF PRIMARY KEY (INPT_MST_SRNO, INPT_SANCTION_NO, ITM_INPT_VAL_SEQ)
);

COMMENT ON TABLE CSPD004TF IS '제재 항목 탐지 데이터';
COMMENT ON COLUMN CSPD004TF.AFRS_AICR_EXTC_TXT IS 'AI OCR 보정 후 추출 텍스트';
COMMENT ON COLUMN CSPD004TF.AFRS_TA_EXTC_TXT IS 'TA 보정 후 추출 텍스트';
COMMENT ON COLUMN CSPD004TF.AI_INPT_ALT_YN IS 'AI 심사 알림 여부';
COMMENT ON COLUMN CSPD004TF.AI_INPT_BUY_AM IS 'AI 심사 매입 금액';
COMMENT ON COLUMN CSPD004TF.AI_INPT_EXTC_SNTN_TXT IS 'AI 심사 추출 문장 내용';
COMMENT ON COLUMN CSPD004TF.AI_INPT_SANCTION_RULE_TXT IS 'AI 심사 제재 룰 내용';
COMMENT ON COLUMN CSPD004TF.AI_INPT_WORD_ACRD_RT IS 'AI 심사 단어 일치율';
COMMENT ON COLUMN CSPD004TF.BFRS_AICR_EXTC_TXT IS 'AI OCR 보정 전 추출 텍스트';
COMMENT ON COLUMN CSPD004TF.BFRS_TA_EXTC_TXT IS 'TA 보정 전 추출 텍스트';
COMMENT ON COLUMN CSPD004TF.INPT_ATMC_BIZ_DSCD IS '심사 자동화 업무 구분 코드';
COMMENT ON COLUMN CSPD004TF.INPT_BL_GRP_NO IS '심사 B/L 그룹 번호';
COMMENT ON COLUMN CSPD004TF.INPT_MST_SRNO IS '심사 마스터 일련번호';
COMMENT ON COLUMN CSPD004TF.INPT_SANCTION_DAT_TXT IS '심사 제재 데이터 내용';
COMMENT ON COLUMN CSPD004TF.INPT_SANCTION_NO IS '심사 제재 번호';
COMMENT ON COLUMN CSPD004TF.INPT_TASK_ID IS '심사 작업 ID';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_VAL_SEQ IS '항목값순번 (동일 항목 복수행, 기본 0)';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_SRC_DSCD IS '값출처 AI/HNDG/SYS';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_ADD_ROW_YN IS '화면 수기 행추가 여부';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_HNDG_INP_DAT_TXT IS '항목별 수기 입력 데이터 내용';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_NACRD_YN IS '항목별 불일치 여부';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_RVSN_YN IS '항목별 보정 여부';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_XAXIS_END_CRDN_CN IS '항목 X축 종료 좌표값';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_XAXIS_STA_CRDN_CN IS '항목 X축 시작 좌표값';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_YAXIS_END_CRDN_CN IS '항목 Y축 종료 좌표값';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_YAXIS_STA_CRDN_CN IS '항목 Y축 시작 좌표값';
COMMENT ON COLUMN CSPD004TF.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD004TF.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD004TF.SAFEWATCH_ITM_YN IS 'SafeWatch 항목 여부';
COMMENT ON COLUMN CSPD004TF.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD005TH: 승인 및 처리 이력
-- ------------------------------------------------------------
CREATE TABLE CSPD005TH (
    AI_INPT_APPV_SRNO                NUMBER(19),
    AI_INPT_APPV_STCD                VARCHAR2(32),
    AI_INPT_BIZ_DSCD                 VARCHAR2(32),
    AI_INPT_CRPE_ENO                 VARCHAR2(64),
    AI_INPT_ITM_RST_CD               VARCHAR2(32),
    AI_INPT_PRC_DTM                  VARCHAR2(20),
    AI_INPT_PRC_OPI_TXT              CLOB,
    AI_INPT_QLAS_PRC_STS_CD          VARCHAR2(32),
    AI_INPT_TOTALTEXT_RST_CD         VARCHAR2(32),
    AI_INPT_TPY_SAVE_YN              CHAR(1),
    INPT_MST_SRNO                    NUMBER(19),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD005TH PRIMARY KEY (INPT_MST_SRNO, AI_INPT_APPV_SRNO)
);

COMMENT ON TABLE CSPD005TH IS '승인 및 처리 이력';
COMMENT ON COLUMN CSPD005TH.AI_INPT_APPV_SRNO IS 'AI 심사 승인 일련번호';
COMMENT ON COLUMN CSPD005TH.AI_INPT_APPV_STCD IS 'AI 심사 승인 상태 코드';
COMMENT ON COLUMN CSPD005TH.AI_INPT_BIZ_DSCD IS 'AI 심사 업무 구분 코드';
COMMENT ON COLUMN CSPD005TH.AI_INPT_CRPE_ENO IS 'AI 심사 처리자 직원번호';
COMMENT ON COLUMN CSPD005TH.AI_INPT_ITM_RST_CD IS 'AI 심사 항목 결과 코드';
COMMENT ON COLUMN CSPD005TH.AI_INPT_PRC_DTM IS 'AI 심사 처리 일시';
COMMENT ON COLUMN CSPD005TH.AI_INPT_PRC_OPI_TXT IS 'AI 심사 처리 의견 내용';
COMMENT ON COLUMN CSPD005TH.AI_INPT_QLAS_PRC_STS_CD IS 'AI 심사 QA 처리 상태 코드';
COMMENT ON COLUMN CSPD005TH.AI_INPT_TOTALTEXT_RST_CD IS 'AI 심사 TotalText 결과 코드';
COMMENT ON COLUMN CSPD005TH.AI_INPT_TPY_SAVE_YN IS 'AI 심사 임시 저장 여부';
COMMENT ON COLUMN CSPD005TH.INPT_MST_SRNO IS '심사 마스터 일련번호';
COMMENT ON COLUMN CSPD005TH.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD005TH.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD005TH.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD006TL: 첨부파일 정보
-- ------------------------------------------------------------
CREATE TABLE CSPD006TL (
    AI_INPT_ATFL_NM                  VARCHAR2(300),
    AI_INPT_ATFL_PATH_TXT            CLOB,
    AI_INPT_ATFL_SRNO                NUMBER(19),
    AI_INPT_BIZ_DSCD                 VARCHAR2(32),
    INPT_MST_SRNO                    NUMBER(19),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD006TL PRIMARY KEY (INPT_MST_SRNO, AI_INPT_ATFL_SRNO)
);

COMMENT ON TABLE CSPD006TL IS '첨부파일 정보';
COMMENT ON COLUMN CSPD006TL.AI_INPT_ATFL_NM IS 'AI 심사 첨부파일명';
COMMENT ON COLUMN CSPD006TL.AI_INPT_ATFL_PATH_TXT IS 'AI 심사 첨부파일 경로';
COMMENT ON COLUMN CSPD006TL.AI_INPT_ATFL_SRNO IS 'AI 심사 첨부파일 일련번호';
COMMENT ON COLUMN CSPD006TL.AI_INPT_BIZ_DSCD IS 'AI 심사 업무 구분 코드';
COMMENT ON COLUMN CSPD006TL.INPT_MST_SRNO IS '심사 마스터 일련번호';
COMMENT ON COLUMN CSPD006TL.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD006TL.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD006TL.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD007TL: SafeWatch 탐지 결과
-- ------------------------------------------------------------
CREATE TABLE CSPD007TL (
    AI_INPT_PRG_SRNO                 NUMBER(19),
    BL_NO                            VARCHAR2(64),
    FILT_DTCT_NO                     VARCHAR2(64),
    INPT_BL_GRP_NO                   VARCHAR2(64),
    INPT_MST_SRNO                    NUMBER(19),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    SAFEWATCH_AI_INPT_RST_CD         VARCHAR2(32)
,
    CONSTRAINT PK_CSPD007TL PRIMARY KEY (INPT_MST_SRNO, AI_INPT_PRG_SRNO)
);

COMMENT ON TABLE CSPD007TL IS 'SafeWatch 탐지 결과';
COMMENT ON COLUMN CSPD007TL.AI_INPT_PRG_SRNO IS 'AI 심사 진행 일련번호';
COMMENT ON COLUMN CSPD007TL.BL_NO IS 'B/L 번호';
COMMENT ON COLUMN CSPD007TL.FILT_DTCT_NO IS '필터 탐지 번호';
COMMENT ON COLUMN CSPD007TL.INPT_BL_GRP_NO IS '심사 B/L 그룹 번호';
COMMENT ON COLUMN CSPD007TL.INPT_MST_SRNO IS '심사 마스터 일련번호';
COMMENT ON COLUMN CSPD007TL.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD007TL.SAFEWATCH_AI_INPT_RST_CD IS 'SafeWatch AI 심사 결과 코드';

-- ------------------------------------------------------------
-- CSPD008TH: AI 심사 진행 이력
-- ------------------------------------------------------------
CREATE TABLE CSPD008TH (
    AI_INPT_ACVT_CD                  VARCHAR2(32),
    AI_INPT_ACVT_STS_CD              VARCHAR2(32),
    AI_INPT_BIZ_DSCD                 VARCHAR2(32),
    AI_INPT_CMN_CD_ENG_NM            VARCHAR2(300),
    AI_INPT_CRPE_ENO                 VARCHAR2(64),
    AI_INPT_PRC_OPI_TXT              CLOB,
    AI_INPT_PRG_SRNO                 NUMBER(19),
    AI_INPT_PROS_STA_DTM             VARCHAR2(20),
    INPT_MST_SRNO                    NUMBER(19),
    INPT_RCP_DT                      VARCHAR2(8),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD008TH PRIMARY KEY (INPT_MST_SRNO, AI_INPT_PRG_SRNO)
);

COMMENT ON TABLE CSPD008TH IS 'AI 심사 진행 이력';
COMMENT ON COLUMN CSPD008TH.AI_INPT_ACVT_CD IS 'AI 심사 활동 코드';
COMMENT ON COLUMN CSPD008TH.AI_INPT_ACVT_STS_CD IS 'AI 심사 활동 상태 코드';
COMMENT ON COLUMN CSPD008TH.AI_INPT_BIZ_DSCD IS 'AI 심사 업무 구분 코드';
COMMENT ON COLUMN CSPD008TH.AI_INPT_CMN_CD_ENG_NM IS 'AI 심사 공통 코드 영문명';
COMMENT ON COLUMN CSPD008TH.AI_INPT_CRPE_ENO IS 'AI 심사 처리자 직원번호';
COMMENT ON COLUMN CSPD008TH.AI_INPT_PRC_OPI_TXT IS 'AI 심사 처리 의견 내용';
COMMENT ON COLUMN CSPD008TH.AI_INPT_PRG_SRNO IS 'AI 심사 진행 일련번호';
COMMENT ON COLUMN CSPD008TH.AI_INPT_PROS_STA_DTM IS 'AI 심사 프로세스 시작 일시';
COMMENT ON COLUMN CSPD008TH.INPT_MST_SRNO IS '심사 마스터 일련번호';
COMMENT ON COLUMN CSPD008TH.INPT_RCP_DT IS '심사 접수 일자';
COMMENT ON COLUMN CSPD008TH.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD008TH.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD008TH.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD009TA: 업무 종료 통계
-- ------------------------------------------------------------
CREATE TABLE CSPD009TA (
    AI_INPT_CLS_CNT                  NUMBER(19),
    AI_INPT_CLS_DSCD                 VARCHAR2(32),
    AI_INPT_CLS_DT                   VARCHAR2(8),
    AI_INPT_CLS_ITCD                 VARCHAR2(32),
    AI_INPT_RMRK_TXT                 CLOB,
    AI_INPT_SNPE_ENO                 VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
);

COMMENT ON TABLE CSPD009TA IS '업무 종료 통계';
COMMENT ON COLUMN CSPD009TA.AI_INPT_CLS_CNT IS 'AI 심사 분류 건수';
COMMENT ON COLUMN CSPD009TA.AI_INPT_CLS_DSCD IS 'AI 심사 분류 구분 코드';
COMMENT ON COLUMN CSPD009TA.AI_INPT_CLS_DT IS 'AI 심사 분류 일자';
COMMENT ON COLUMN CSPD009TA.AI_INPT_CLS_ITCD IS 'AI 심사 분류 항목 코드';
COMMENT ON COLUMN CSPD009TA.AI_INPT_RMRK_TXT IS 'AI 심사 비고 내용';
COMMENT ON COLUMN CSPD009TA.AI_INPT_SNPE_ENO IS 'AI 심사 승인자 직원번호';
COMMENT ON COLUMN CSPD009TA.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD009TA.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD009TA.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD010TA: 업무 등록 통계
-- ------------------------------------------------------------
CREATE TABLE CSPD010TA (
    AI_INPT_APDR_DSCD                VARCHAR2(32),
    AI_INPT_APDR_DT                  VARCHAR2(8),
    AI_INPT_APDR_ITCD                VARCHAR2(32),
    AI_INPT_ETC_ITM_CNT              NUMBER(19),
    AI_INPT_ETC_OPI_TXT              CLOB,
    AI_INPT_IMP_REL_CNT              NUMBER(19),
    AI_INPT_OBK_ISSU_CNT             NUMBER(19),
    AI_INPT_RMSG_CNT                 NUMBER(19),
    AI_INPT_SMSG_CNT                 NUMBER(19),
    AI_INPT_SNPE_ENO                 VARCHAR2(64),
    AI_INPT_TBK_ISSU_CNT             NUMBER(19),
    AI_INPT_XPO_REL_CNT              NUMBER(19),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
);

COMMENT ON TABLE CSPD010TA IS '업무 등록 통계';
COMMENT ON COLUMN CSPD010TA.AI_INPT_APDR_DSCD IS 'AI 심사 적용 기간 구분 코드';
COMMENT ON COLUMN CSPD010TA.AI_INPT_APDR_DT IS 'AI 심사 적용 기간 일자';
COMMENT ON COLUMN CSPD010TA.AI_INPT_APDR_ITCD IS 'AI 심사 적용 기간 항목 코드';
COMMENT ON COLUMN CSPD010TA.AI_INPT_ETC_ITM_CNT IS 'AI 심사 기타 항목 건수';
COMMENT ON COLUMN CSPD010TA.AI_INPT_ETC_OPI_TXT IS 'AI 심사 기타 의견 내용';
COMMENT ON COLUMN CSPD010TA.AI_INPT_IMP_REL_CNT IS 'AI 심사 수입 관련 건수';
COMMENT ON COLUMN CSPD010TA.AI_INPT_OBK_ISSU_CNT IS 'AI 심사 당행 발행 건수';
COMMENT ON COLUMN CSPD010TA.AI_INPT_RMSG_CNT IS 'AI 심사 수신 메시지 건수';
COMMENT ON COLUMN CSPD010TA.AI_INPT_SMSG_CNT IS 'AI 심사 발신 메시지 건수';
COMMENT ON COLUMN CSPD010TA.AI_INPT_SNPE_ENO IS 'AI 심사 승인자 직원번호';
COMMENT ON COLUMN CSPD010TA.AI_INPT_TBK_ISSU_CNT IS 'AI 심사 타행 발행 건수';
COMMENT ON COLUMN CSPD010TA.AI_INPT_XPO_REL_CNT IS 'AI 심사 수출 관련 건수';
COMMENT ON COLUMN CSPD010TA.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD010TA.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD010TA.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD011TL: 미생성 및 추출 처리 로그
-- ------------------------------------------------------------
CREATE TABLE CSPD011TL (
    ACTL_FX_REFNO                    VARCHAR2(64),
    AI_INPT_APL_XT_RNCD              VARCHAR2(32),
    AI_INPT_DOC_SCAN_CHRG_ENO        VARCHAR2(64),
    AI_INPT_DOC_SCAN_DTM             VARCHAR2(20),
    AI_INPT_IMG_KEY_NO               VARCHAR2(64),
    AI_INPT_XT_PRC_DTM               VARCHAR2(20),
    AI_INPT_XT_PRC_ENO               VARCHAR2(64),
    AI_INPT_XT_PRC_STS_DSCD          VARCHAR2(32),
    AI_INPT_XT_SRNO                  NUMBER(19),
    FX_REFNO_SRNO                    NUMBER(19),
    INPT_ATMC_BIZ_DSCD               VARCHAR2(32),
    INPT_RCP_DT                      VARCHAR2(8),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD011TL PRIMARY KEY (AI_INPT_XT_SRNO)
);

COMMENT ON TABLE CSPD011TL IS '미생성 및 추출 처리 로그';
COMMENT ON COLUMN CSPD011TL.ACTL_FX_REFNO IS '실제 외환 참조번호';
COMMENT ON COLUMN CSPD011TL.AI_INPT_APL_XT_RNCD IS 'AI 심사 적용 추출 사유 코드';
COMMENT ON COLUMN CSPD011TL.AI_INPT_DOC_SCAN_CHRG_ENO IS 'AI 심사 문서 스캔 담당 직원번호';
COMMENT ON COLUMN CSPD011TL.AI_INPT_DOC_SCAN_DTM IS 'AI 심사 문서 스캔 일시';
COMMENT ON COLUMN CSPD011TL.AI_INPT_IMG_KEY_NO IS 'AI 심사 이미지 키 번호';
COMMENT ON COLUMN CSPD011TL.AI_INPT_XT_PRC_DTM IS 'AI 심사 추출 처리 일시';
COMMENT ON COLUMN CSPD011TL.AI_INPT_XT_PRC_ENO IS 'AI 심사 추출 처리자 직원번호';
COMMENT ON COLUMN CSPD011TL.AI_INPT_XT_PRC_STS_DSCD IS 'AI 심사 추출 처리 상태 구분 코드';
COMMENT ON COLUMN CSPD011TL.AI_INPT_XT_SRNO IS 'AI 심사 추출 일련번호';
COMMENT ON COLUMN CSPD011TL.FX_REFNO_SRNO IS '외환 참조번호 일련번호';
COMMENT ON COLUMN CSPD011TL.INPT_ATMC_BIZ_DSCD IS '심사 자동화 업무 구분 코드';
COMMENT ON COLUMN CSPD011TL.INPT_RCP_DT IS '심사 접수 일자';
COMMENT ON COLUMN CSPD011TL.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD011TL.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD011TL.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD101TI: 사용자 정보
-- ------------------------------------------------------------
CREATE TABLE CSPD101TI (
    AI_INPT_AUT_CD                   VARCHAR2(32),
    AI_INPT_MGPE_YN                  CHAR(1),
    AI_INPT_SNPE_ENO                 VARCHAR2(64),
    AI_INPT_SRVC_USER_DSCD           VARCHAR2(32),
    AI_INPT_USER_END_DTM             VARCHAR2(20),
    AI_INPT_USER_ENO                 VARCHAR2(64),
    AI_INPT_USER_FA_RE_YN            CHAR(1),
    AI_INPT_USER_ID                  VARCHAR2(64),
    AI_INPT_USER_NM                  VARCHAR2(300),
    AI_INPT_USER_RGS_DTM             VARCHAR2(20),
    AI_INPT_USER_YN                  CHAR(1),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD101TI PRIMARY KEY (AI_INPT_USER_ID)
);

COMMENT ON TABLE CSPD101TI IS '사용자 정보';
COMMENT ON COLUMN CSPD101TI.AI_INPT_AUT_CD IS 'AI 심사 권한 코드';
COMMENT ON COLUMN CSPD101TI.AI_INPT_MGPE_YN IS 'AI 심사 관리자 여부';
COMMENT ON COLUMN CSPD101TI.AI_INPT_SNPE_ENO IS 'AI 심사 승인자 직원번호';
COMMENT ON COLUMN CSPD101TI.AI_INPT_SRVC_USER_DSCD IS 'AI 심사 서비스 사용자 구분 코드';
COMMENT ON COLUMN CSPD101TI.AI_INPT_USER_END_DTM IS 'AI 심사 사용자 종료 일시';
COMMENT ON COLUMN CSPD101TI.AI_INPT_USER_ENO IS 'AI 심사 사용자 직원번호';
COMMENT ON COLUMN CSPD101TI.AI_INPT_USER_FA_RE_YN IS 'AI 심사 사용자 부재/대체 여부';
COMMENT ON COLUMN CSPD101TI.AI_INPT_USER_ID IS 'AI 심사 사용자 ID';
COMMENT ON COLUMN CSPD101TI.AI_INPT_USER_NM IS 'AI 심사 사용자명';
COMMENT ON COLUMN CSPD101TI.AI_INPT_USER_RGS_DTM IS 'AI 심사 사용자 등록 일시';
COMMENT ON COLUMN CSPD101TI.AI_INPT_USER_YN IS 'AI 심사 사용자 사용 여부';
COMMENT ON COLUMN CSPD101TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD101TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD101TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD102TI: WatchList 카테고리
-- ------------------------------------------------------------
CREATE TABLE CSPD102TI (
    AI_INPT_CTGR_END_DTM             VARCHAR2(20),
    AI_INPT_CTGR_ID                  VARCHAR2(64),
    AI_INPT_CTGR_NM                  VARCHAR2(300),
    AI_INPT_CTGR_RGS_DTM             VARCHAR2(20),
    AI_INPT_CTGR_TXT                 CLOB,
    AI_INPT_CTGR_YN                  CHAR(1),
    CTGR_CFCD                        VARCHAR2(32),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD102TI PRIMARY KEY (AI_INPT_CTGR_ID)
);

COMMENT ON TABLE CSPD102TI IS 'WatchList 카테고리';
COMMENT ON COLUMN CSPD102TI.AI_INPT_CTGR_END_DTM IS 'AI 심사 카테고리 종료 일시';
COMMENT ON COLUMN CSPD102TI.AI_INPT_CTGR_ID IS 'AI 심사 카테고리 ID';
COMMENT ON COLUMN CSPD102TI.AI_INPT_CTGR_NM IS 'AI 심사 카테고리명';
COMMENT ON COLUMN CSPD102TI.AI_INPT_CTGR_RGS_DTM IS 'AI 심사 카테고리 등록 일시';
COMMENT ON COLUMN CSPD102TI.AI_INPT_CTGR_TXT IS 'AI 심사 카테고리 내용';
COMMENT ON COLUMN CSPD102TI.AI_INPT_CTGR_YN IS 'AI 심사 카테고리 여부';
COMMENT ON COLUMN CSPD102TI.CTGR_CFCD IS '카테고리 분류 코드';
COMMENT ON COLUMN CSPD102TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD102TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD102TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD103TI: WatchList 목록
-- ------------------------------------------------------------
CREATE TABLE CSPD103TI (
    AI_INPT_CTGR_ID                  VARCHAR2(64),
    AI_INPT_LIST_DES_TXT             CLOB,
    AI_INPT_LIST_END_DTM             VARCHAR2(20),
    AI_INPT_LIST_ID                  VARCHAR2(64),
    AI_INPT_LIST_NM                  VARCHAR2(300),
    AI_INPT_LIST_RGS_DTM             VARCHAR2(20),
    AI_INPT_LIST_YN                  CHAR(1),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD103TI PRIMARY KEY (AI_INPT_LIST_ID)
);

COMMENT ON TABLE CSPD103TI IS 'WatchList 목록';
COMMENT ON COLUMN CSPD103TI.AI_INPT_CTGR_ID IS 'AI 심사 카테고리 ID';
COMMENT ON COLUMN CSPD103TI.AI_INPT_LIST_DES_TXT IS 'AI 심사 목록 설명 내용';
COMMENT ON COLUMN CSPD103TI.AI_INPT_LIST_END_DTM IS 'AI 심사 목록 종료 일시';
COMMENT ON COLUMN CSPD103TI.AI_INPT_LIST_ID IS 'AI 심사 목록 ID';
COMMENT ON COLUMN CSPD103TI.AI_INPT_LIST_NM IS 'AI 심사 목록명';
COMMENT ON COLUMN CSPD103TI.AI_INPT_LIST_RGS_DTM IS 'AI 심사 목록 등록 일시';
COMMENT ON COLUMN CSPD103TI.AI_INPT_LIST_YN IS 'AI 심사 목록 사용 여부';
COMMENT ON COLUMN CSPD103TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD103TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD103TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD104TI: WatchList 응답 텍스트
-- ------------------------------------------------------------
CREATE TABLE CSPD104TI (
    AI_INPT_CTGR_ID                  VARCHAR2(64),
    AI_INPT_LIST_ID                  VARCHAR2(64),
    AI_INPT_RSPT_TXT_DES_TXT         CLOB,
    AI_INPT_RSPT_TXT_END_DTM         VARCHAR2(20),
    AI_INPT_RSPT_TXT_RGS_DTM         VARCHAR2(20),
    AI_INPT_RSPT_TXT_SRNO            NUMBER(19),
    AI_INPT_RSPT_TXT_YN              CHAR(1),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD104TI PRIMARY KEY (AI_INPT_RSPT_TXT_SRNO)
);

COMMENT ON TABLE CSPD104TI IS 'WatchList 응답 텍스트';
COMMENT ON COLUMN CSPD104TI.AI_INPT_CTGR_ID IS 'AI 심사 카테고리 ID';
COMMENT ON COLUMN CSPD104TI.AI_INPT_LIST_ID IS 'AI 심사 목록 ID';
COMMENT ON COLUMN CSPD104TI.AI_INPT_RSPT_TXT_DES_TXT IS 'AI 심사 응답 텍스트 설명';
COMMENT ON COLUMN CSPD104TI.AI_INPT_RSPT_TXT_END_DTM IS 'AI 심사 응답 텍스트 종료 일시';
COMMENT ON COLUMN CSPD104TI.AI_INPT_RSPT_TXT_RGS_DTM IS 'AI 심사 응답 텍스트 등록 일시';
COMMENT ON COLUMN CSPD104TI.AI_INPT_RSPT_TXT_SRNO IS 'AI 심사 응답 텍스트 일련번호';
COMMENT ON COLUMN CSPD104TI.AI_INPT_RSPT_TXT_YN IS 'AI 심사 응답 텍스트 사용 여부';
COMMENT ON COLUMN CSPD104TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD104TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD104TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD105TI: 제재 룰 1단계
-- ------------------------------------------------------------
CREATE TABLE CSPD105TI (
    AI_INPT_LIST_ID                  VARCHAR2(64),
    AI_INPT_RULE_DSCD                VARCHAR2(32),
    AI_INPT_SNRL1_ID                 VARCHAR2(64),
    AI_INPT_SNRL1_NM                 VARCHAR2(300),
    INPT_SANCTION_NO                 NUMBER(19),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD105TI PRIMARY KEY (AI_INPT_SNRL1_ID)
);

COMMENT ON TABLE CSPD105TI IS '제재 룰 1단계';
COMMENT ON COLUMN CSPD105TI.AI_INPT_LIST_ID IS 'AI 심사 목록 ID';
COMMENT ON COLUMN CSPD105TI.AI_INPT_RULE_DSCD IS 'AI 심사 룰 구분 코드';
COMMENT ON COLUMN CSPD105TI.AI_INPT_SNRL1_ID IS 'AI 심사 제재 룰 1단계 ID';
COMMENT ON COLUMN CSPD105TI.AI_INPT_SNRL1_NM IS 'AI 심사 제재 룰 1단계명';
COMMENT ON COLUMN CSPD105TI.INPT_SANCTION_NO IS '심사 제재 번호';
COMMENT ON COLUMN CSPD105TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD105TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD105TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD106TI: 제재 룰 2단계
-- ------------------------------------------------------------
CREATE TABLE CSPD106TI (
    AI_INPT_LIST1_ID                 VARCHAR2(64),
    AI_INPT_LIST2_ID                 VARCHAR2(64),
    AI_INPT_LIST3_ID                 VARCHAR2(64),
    AI_INPT_LIST4_ID                 VARCHAR2(64),
    AI_INPT_RULE_DSCD                VARCHAR2(32),
    AI_INPT_SNRL2_ID                 VARCHAR2(64),
    AI_INPT_SNRL2_NM                 VARCHAR2(300),
    INPT_SANCTION1_NO                VARCHAR2(64),
    INPT_SANCTION2_NO                VARCHAR2(64),
    INPT_SANCTION3_NO                VARCHAR2(64),
    INPT_SANCTION4_NO                VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD106TI PRIMARY KEY (AI_INPT_SNRL2_ID)
);

COMMENT ON TABLE CSPD106TI IS '제재 룰 2단계';
COMMENT ON COLUMN CSPD106TI.AI_INPT_LIST1_ID IS 'AI 심사 목록1 ID';
COMMENT ON COLUMN CSPD106TI.AI_INPT_LIST2_ID IS 'AI 심사 목록2 ID';
COMMENT ON COLUMN CSPD106TI.AI_INPT_LIST3_ID IS 'AI 심사 목록3 ID';
COMMENT ON COLUMN CSPD106TI.AI_INPT_LIST4_ID IS 'AI 심사 목록4 ID';
COMMENT ON COLUMN CSPD106TI.AI_INPT_RULE_DSCD IS 'AI 심사 룰 구분 코드';
COMMENT ON COLUMN CSPD106TI.AI_INPT_SNRL2_ID IS 'AI 심사 제재 룰 2단계 ID';
COMMENT ON COLUMN CSPD106TI.AI_INPT_SNRL2_NM IS 'AI 심사 제재 룰 2단계명';
COMMENT ON COLUMN CSPD106TI.INPT_SANCTION1_NO IS '제재1 번호';
COMMENT ON COLUMN CSPD106TI.INPT_SANCTION2_NO IS '제재2 번호';
COMMENT ON COLUMN CSPD106TI.INPT_SANCTION3_NO IS '제재3 번호';
COMMENT ON COLUMN CSPD106TI.INPT_SANCTION4_NO IS '제재4 번호';
COMMENT ON COLUMN CSPD106TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD106TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD106TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD107TI: QA 대상 선정 정보
-- ------------------------------------------------------------
CREATE TABLE CSPD107TI (
    AI_INPT_IMEX_DSCD                VARCHAR2(32),
    AI_INPT_LIST_ID                  VARCHAR2(64),
    INPT_SANCTION_NO                 NUMBER(19),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    QLAS_ITM_TOT_CNT                 NUMBER(19),
    QLAS_SLBS_VLD_YN                 CHAR(1),
    QLAS_SLT_END_DTM                 VARCHAR2(20),
    QLAS_SLT_MNG_ID                  VARCHAR2(64),
    QLAS_SLT_RGS_DTM                 VARCHAR2(20),
    QLAS_VOLN_CHC_CNT                NUMBER(19),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD107TI PRIMARY KEY (AI_INPT_IMEX_DSCD, AI_INPT_LIST_ID)
);

COMMENT ON TABLE CSPD107TI IS 'QA 대상 선정 정보';
COMMENT ON COLUMN CSPD107TI.AI_INPT_IMEX_DSCD IS 'AI 심사 수출입 구분 코드';
COMMENT ON COLUMN CSPD107TI.AI_INPT_LIST_ID IS 'AI 심사 목록 ID';
COMMENT ON COLUMN CSPD107TI.INPT_SANCTION_NO IS '심사 제재 번호';
COMMENT ON COLUMN CSPD107TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD107TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD107TI.QLAS_ITM_TOT_CNT IS 'QA 항목 총 건수';
COMMENT ON COLUMN CSPD107TI.QLAS_SLBS_VLD_YN IS 'QA 선택 기준 유효 여부';
COMMENT ON COLUMN CSPD107TI.QLAS_SLT_END_DTM IS 'QA 선정 종료 일시';
COMMENT ON COLUMN CSPD107TI.QLAS_SLT_MNG_ID IS 'QA 선정 관리 ID';
COMMENT ON COLUMN CSPD107TI.QLAS_SLT_RGS_DTM IS 'QA 선정 등록 일시';
COMMENT ON COLUMN CSPD107TI.QLAS_VOLN_CHC_CNT IS 'QA 임의 선택 건수';
COMMENT ON COLUMN CSPD107TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD108TI: 메뉴 정보
-- ------------------------------------------------------------
CREATE TABLE CSPD108TI (
    AI_INPT_HGRN_MENU_ID             VARCHAR2(64),
    AI_INPT_MENU_ID                  VARCHAR2(64),
    AI_INPT_MENU_NM                  VARCHAR2(300),
    AI_INPT_MENU_NO                  VARCHAR2(64),
    AI_INPT_MENU_URL_NM              VARCHAR2(300),
    AI_INPT_MGPE_YN                  CHAR(1),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD108TI PRIMARY KEY (AI_INPT_MENU_ID)
);

COMMENT ON TABLE CSPD108TI IS '메뉴 정보';
COMMENT ON COLUMN CSPD108TI.AI_INPT_HGRN_MENU_ID IS 'AI 심사 상위 메뉴 ID';
COMMENT ON COLUMN CSPD108TI.AI_INPT_MENU_ID IS 'AI 심사 메뉴 ID';
COMMENT ON COLUMN CSPD108TI.AI_INPT_MENU_NM IS 'AI 심사 메뉴명';
COMMENT ON COLUMN CSPD108TI.AI_INPT_MENU_NO IS 'AI 심사 메뉴 번호';
COMMENT ON COLUMN CSPD108TI.AI_INPT_MENU_URL_NM IS 'AI 심사 메뉴 URL명';
COMMENT ON COLUMN CSPD108TI.AI_INPT_MGPE_YN IS 'AI 심사 관리자 여부';
COMMENT ON COLUMN CSPD108TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD108TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD108TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD109TI: 메뉴 권한 정보
-- ------------------------------------------------------------
CREATE TABLE CSPD109TI (
    AI_INPT_AUT_CD                   VARCHAR2(32),
    AI_INPT_AUT_ID                   NUMBER(19),
    AI_INPT_AUT_USG_YN               CHAR(1),
    AI_INPT_MENU_ID                  VARCHAR2(64),
    AI_INPT_RMRK_TXT                 CLOB,
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD109TI PRIMARY KEY (AI_INPT_AUT_ID)
);

COMMENT ON TABLE CSPD109TI IS '메뉴 권한 정보';
COMMENT ON COLUMN CSPD109TI.AI_INPT_AUT_CD IS 'AI 심사 권한 코드';
COMMENT ON COLUMN CSPD109TI.AI_INPT_AUT_ID IS 'AI 심사 권한 ID';
COMMENT ON COLUMN CSPD109TI.AI_INPT_AUT_USG_YN IS 'AI 심사 권한 사용 여부';
COMMENT ON COLUMN CSPD109TI.AI_INPT_MENU_ID IS 'AI 심사 메뉴 ID';
COMMENT ON COLUMN CSPD109TI.AI_INPT_RMRK_TXT IS 'AI 심사 비고 내용';
COMMENT ON COLUMN CSPD109TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD109TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD109TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD110TI: 승인 의견 메모
-- ------------------------------------------------------------
CREATE TABLE CSPD110TI (
    AI_INPT_APPV_OPI_END_DTM         VARCHAR2(20),
    AI_INPT_APPV_OPI_RGS_DTM         VARCHAR2(20),
    AI_INPT_APPV_OPI_SRNO            NUMBER(19),
    AI_INPT_APPV_OPI_TXT             CLOB,
    AI_INPT_APPV_OPI_USG_YN          CHAR(1),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD110TI PRIMARY KEY (AI_INPT_APPV_OPI_SRNO)
);

COMMENT ON TABLE CSPD110TI IS '승인 의견 메모';
COMMENT ON COLUMN CSPD110TI.AI_INPT_APPV_OPI_END_DTM IS 'AI 심사 승인 의견 종료 일시';
COMMENT ON COLUMN CSPD110TI.AI_INPT_APPV_OPI_RGS_DTM IS 'AI 심사 승인 의견 등록 일시';
COMMENT ON COLUMN CSPD110TI.AI_INPT_APPV_OPI_SRNO IS 'AI 심사 승인 의견 일련번호';
COMMENT ON COLUMN CSPD110TI.AI_INPT_APPV_OPI_TXT IS 'AI 심사 승인 의견 내용';
COMMENT ON COLUMN CSPD110TI.AI_INPT_APPV_OPI_USG_YN IS 'AI 심사 승인 의견 사용 여부';
COMMENT ON COLUMN CSPD110TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD110TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD110TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD111TI: 공통코드 그룹
-- ------------------------------------------------------------
CREATE TABLE CSPD111TI (
    AI_INPT_GRP_CD                   VARCHAR2(32),
    AI_INPT_GRP_END_DTM              VARCHAR2(20),
    AI_INPT_GRP_NM                   VARCHAR2(300),
    AI_INPT_GRP_STA_DTM              VARCHAR2(20),
    AI_INPT_GRP_USG_YN               CHAR(1),
    AI_INPT_RMRK_TXT                 CLOB,
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD111TI PRIMARY KEY (AI_INPT_GRP_CD)
);

COMMENT ON TABLE CSPD111TI IS '공통코드 그룹';
COMMENT ON COLUMN CSPD111TI.AI_INPT_GRP_CD IS 'AI 심사 그룹 코드';
COMMENT ON COLUMN CSPD111TI.AI_INPT_GRP_END_DTM IS 'AI 심사 그룹 종료 일시';
COMMENT ON COLUMN CSPD111TI.AI_INPT_GRP_NM IS 'AI 심사 그룹명';
COMMENT ON COLUMN CSPD111TI.AI_INPT_GRP_STA_DTM IS 'AI 심사 그룹 시작 일시';
COMMENT ON COLUMN CSPD111TI.AI_INPT_GRP_USG_YN IS 'AI 심사 그룹 사용 여부';
COMMENT ON COLUMN CSPD111TI.AI_INPT_RMRK_TXT IS 'AI 심사 비고 내용';
COMMENT ON COLUMN CSPD111TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD111TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD111TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD112TI: 공통코드 상세
-- ------------------------------------------------------------
CREATE TABLE CSPD112TI (
    AI_INPT_CMN_CD                   VARCHAR2(32),
    AI_INPT_CMN_CD_END_DTM           VARCHAR2(20),
    AI_INPT_CMN_CD_ENG_NM            VARCHAR2(300),
    AI_INPT_CMN_CD_NM                VARCHAR2(300),
    AI_INPT_CMN_CD_STA_DTM           VARCHAR2(20),
    AI_INPT_CMN_USG_YN               CHAR(1),
    AI_INPT_GRP_CD                   VARCHAR2(32),
    AI_INPT_INTF_ITM_NM              VARCHAR2(300),
    AI_INPT_RMRK_TXT                 CLOB,
    AI_INPT_SORT_SEQ                 NUMBER(19),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD112TI PRIMARY KEY (AI_INPT_GRP_CD, AI_INPT_CMN_CD)
);

COMMENT ON TABLE CSPD112TI IS '공통코드 상세';
COMMENT ON COLUMN CSPD112TI.AI_INPT_CMN_CD IS 'AI 심사 공통 코드';
COMMENT ON COLUMN CSPD112TI.AI_INPT_CMN_CD_END_DTM IS 'AI 심사 공통 코드 종료 일시';
COMMENT ON COLUMN CSPD112TI.AI_INPT_CMN_CD_ENG_NM IS 'AI 심사 공통 코드 영문명';
COMMENT ON COLUMN CSPD112TI.AI_INPT_CMN_CD_NM IS 'AI 심사 공통 코드명';
COMMENT ON COLUMN CSPD112TI.AI_INPT_CMN_CD_STA_DTM IS 'AI 심사 공통 코드 시작 일시';
COMMENT ON COLUMN CSPD112TI.AI_INPT_CMN_USG_YN IS 'AI 심사 공통 코드 사용 여부';
COMMENT ON COLUMN CSPD112TI.AI_INPT_GRP_CD IS 'AI 심사 그룹 코드';
COMMENT ON COLUMN CSPD112TI.AI_INPT_INTF_ITM_NM IS 'AI 심사 인터페이스 항목명';
COMMENT ON COLUMN CSPD112TI.AI_INPT_RMRK_TXT IS 'AI 심사 비고 내용';
COMMENT ON COLUMN CSPD112TI.AI_INPT_SORT_SEQ IS 'AI 심사 정렬 순서';
COMMENT ON COLUMN CSPD112TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD112TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD112TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD113TI: 제재 SQL 룰
-- ------------------------------------------------------------
CREATE TABLE CSPD113TI (
    AI_INPT_RSPT_SQL_TXT             CLOB,
    AI_INPT_SNRL3_ID                 VARCHAR2(64),
    AI_INPT_SNRL3_NM                 VARCHAR2(300),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD113TI PRIMARY KEY (AI_INPT_SNRL3_ID)
);

COMMENT ON TABLE CSPD113TI IS '제재 SQL 룰';
COMMENT ON COLUMN CSPD113TI.AI_INPT_RSPT_SQL_TXT IS 'AI 심사 응답 SQL 내용';
COMMENT ON COLUMN CSPD113TI.AI_INPT_SNRL3_ID IS 'AI 심사 제재 룰 3단계 ID';
COMMENT ON COLUMN CSPD113TI.AI_INPT_SNRL3_NM IS 'AI 심사 제재 룰 3단계명';
COMMENT ON COLUMN CSPD113TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD113TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD113TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD115TI: 국가 코드 정보
-- ------------------------------------------------------------
CREATE TABLE CSPD115TI (
    ENG_NL_ABRV_NM                   VARCHAR2(300),
    ENG_NL_NM                        VARCHAR2(300),
    KORL_NL_ABRV_NM                  VARCHAR2(300),
    KORL_NL_NM                       VARCHAR2(300),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    NACD                             VARCHAR2(32),
    NUTP_NACD                        VARCHAR2(32),
    RPRS_CD_YN                       CHAR(1),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD115TI PRIMARY KEY (NACD)
);

COMMENT ON TABLE CSPD115TI IS '국가 코드 정보';
COMMENT ON COLUMN CSPD115TI.ENG_NL_ABRV_NM IS '영문 국가 약어명';
COMMENT ON COLUMN CSPD115TI.ENG_NL_NM IS '영문 국가명';
COMMENT ON COLUMN CSPD115TI.KORL_NL_ABRV_NM IS '한글 국가 약어명';
COMMENT ON COLUMN CSPD115TI.KORL_NL_NM IS '한글 국가명';
COMMENT ON COLUMN CSPD115TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD115TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD115TI.NACD IS '국가 코드';
COMMENT ON COLUMN CSPD115TI.NUTP_NACD IS '국가 유형 국가 코드';
COMMENT ON COLUMN CSPD115TI.RPRS_CD_YN IS '대표 코드 여부';
COMMENT ON COLUMN CSPD115TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD116TI: 제재 룰 설정
-- ------------------------------------------------------------
CREATE TABLE CSPD116TI (
    AI_INPT_RULE_DSCD                VARCHAR2(32),
    AI_INPT_SNRL2_USG_YN             CHAR(1),
    AI_INPT_SNRL3_USG_YN             CHAR(1),
    AI_INPT_WORD_ACRD_RT             NUMBER(20,4),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD116TI PRIMARY KEY (AI_INPT_RULE_DSCD)
);

COMMENT ON TABLE CSPD116TI IS '제재 룰 설정';
COMMENT ON COLUMN CSPD116TI.AI_INPT_RULE_DSCD IS 'AI 심사 룰 구분 코드';
COMMENT ON COLUMN CSPD116TI.AI_INPT_SNRL2_USG_YN IS 'AI 심사 제재 룰 2단계 사용 여부';
COMMENT ON COLUMN CSPD116TI.AI_INPT_SNRL3_USG_YN IS 'AI 심사 제재 룰 3단계 사용 여부';
COMMENT ON COLUMN CSPD116TI.AI_INPT_WORD_ACRD_RT IS 'AI 심사 단어 일치율';
COMMENT ON COLUMN CSPD116TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD116TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD116TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD117TI: AI 심사용어 사전
-- ------------------------------------------------------------
CREATE TABLE CSPD117TI (
    AI_INPT_GRP_CD                   VARCHAR2(32),
    AI_INPT_RMRK_TXT                 CLOB,
    AI_INPT_WORD_INF_NM              VARCHAR2(300),
    AI_INPT_WORD_SRNO                NUMBER(19),
    AI_INPT_WORD_TXT                 CLOB,
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD117TI PRIMARY KEY (AI_INPT_WORD_SRNO)
);

COMMENT ON TABLE CSPD117TI IS 'AI 심사용어 사전';
COMMENT ON COLUMN CSPD117TI.AI_INPT_GRP_CD IS 'AI 심사 그룹 코드';
COMMENT ON COLUMN CSPD117TI.AI_INPT_RMRK_TXT IS 'AI 심사 비고 내용';
COMMENT ON COLUMN CSPD117TI.AI_INPT_WORD_INF_NM IS 'AI 심사 용어 정보명';
COMMENT ON COLUMN CSPD117TI.AI_INPT_WORD_SRNO IS 'AI 심사 용어 일련번호';
COMMENT ON COLUMN CSPD117TI.AI_INPT_WORD_TXT IS 'AI 심사 용어 내용';
COMMENT ON COLUMN CSPD117TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD117TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD117TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD118TI: 도시 및 항구 정보
-- ------------------------------------------------------------
CREATE TABLE CSPD118TI (
    CITY_PORT_DSCD                   VARCHAR2(32),
    CITY_SRNO                        NUMBER(19),
    ENG_CITY_NM                      VARCHAR2(300),
    ENG_CITY_RGN_NM                  VARCHAR2(300),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    NACD                             VARCHAR2(32),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD118TI PRIMARY KEY (CITY_SRNO)
);

COMMENT ON TABLE CSPD118TI IS '도시 및 항구 정보';
COMMENT ON COLUMN CSPD118TI.CITY_PORT_DSCD IS '도시/항구 구분 코드';
COMMENT ON COLUMN CSPD118TI.CITY_SRNO IS '도시 일련번호';
COMMENT ON COLUMN CSPD118TI.ENG_CITY_NM IS '영문 도시명';
COMMENT ON COLUMN CSPD118TI.ENG_CITY_RGN_NM IS '영문 도시 지역명';
COMMENT ON COLUMN CSPD118TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD118TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD118TI.NACD IS '국가 코드';
COMMENT ON COLUMN CSPD118TI.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD118TM: 영업일 및 휴일 정보
-- ------------------------------------------------------------
CREATE TABLE CSPD118TM (
    BAS_DT                           VARCHAR2(8),
    HLDY_DSCD                        VARCHAR2(32),
    HLDY_TXT                         CLOB,
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60),
    WKD_CD                           VARCHAR2(32)
,
    CONSTRAINT PK_CSPD118TM PRIMARY KEY (BAS_DT)
);

COMMENT ON TABLE CSPD118TM IS '영업일 및 휴일 정보';
COMMENT ON COLUMN CSPD118TM.BAS_DT IS '기준 일자';
COMMENT ON COLUMN CSPD118TM.HLDY_DSCD IS '휴일 구분 코드';
COMMENT ON COLUMN CSPD118TM.HLDY_TXT IS '휴일 내용';
COMMENT ON COLUMN CSPD118TM.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD118TM.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD118TM.TRN_LOG_SRNO IS '거래 로그 일련번호';
COMMENT ON COLUMN CSPD118TM.WKD_CD IS '요일 코드';

-- ------------------------------------------------------------
-- CSPD201TM: 수출 원장
-- ------------------------------------------------------------
CREATE TABLE CSPD201TM (
    CSNO                             VARCHAR2(255),
    CUS_KORL_NM                      VARCHAR2(300),
    CUS_ENG_NM                       VARCHAR2(300),
    FX_ACNO                          VARCHAR2(64),
    XPBY_COL_AM                      NUMBER(20,4),
    XPBY_COL_CTR_CUCD                VARCHAR2(255),
    XPO_CVRG_MK_SQ                   NUMBER(19),
    INPT_ATMC_REQ_DSCD               VARCHAR2(32),
    XPO_CVRG_MTBR_MK_DT              VARCHAR2(8),
    TRN_OPR_NO                       VARCHAR2(64),
    INPT_ATMC_BIZ_DSCD               VARCHAR2(32),
    KRBR_NM                          VARCHAR2(300),
    DACC_BRCD                        VARCHAR2(32),
    XPO_PTN_NACD                     VARCHAR2(32),
    HS_CD                            VARCHAR2(32)
,
    CONSTRAINT PK_CSPD201TM PRIMARY KEY (XPO_CVRG_MK_SQ)
);

COMMENT ON TABLE CSPD201TM IS '수출 원장';
COMMENT ON COLUMN CSPD201TM.CSNO IS '고객번호';
COMMENT ON COLUMN CSPD201TM.CUS_KORL_NM IS '고객 한글명';
COMMENT ON COLUMN CSPD201TM.CUS_ENG_NM IS '고객 영문명';
COMMENT ON COLUMN CSPD201TM.FX_ACNO IS '외환 계좌번호';
COMMENT ON COLUMN CSPD201TM.XPBY_COL_AM IS '수출대금 추심 금액';
COMMENT ON COLUMN CSPD201TM.XPBY_COL_CTR_CUCD IS '수출대금 추심 계약 통화 코드';
COMMENT ON COLUMN CSPD201TM.XPO_CVRG_MK_SQ IS '수출 커버링 작성 순번';
COMMENT ON COLUMN CSPD201TM.INPT_ATMC_REQ_DSCD IS '심사 자동화 요청 구분 코드';
COMMENT ON COLUMN CSPD201TM.XPO_CVRG_MTBR_MK_DT IS '수출 커버링 모점 작성 일자';
COMMENT ON COLUMN CSPD201TM.TRN_OPR_NO IS '조작자 사번';
COMMENT ON COLUMN CSPD201TM.INPT_ATMC_BIZ_DSCD IS '심사 자동화 업무 구분 코드';
COMMENT ON COLUMN CSPD201TM.KRBR_NM IS '영업점명';
COMMENT ON COLUMN CSPD201TM.DACC_BRCD IS '일계점코드(영업점코드)';
COMMENT ON COLUMN CSPD201TM.XPO_PTN_NACD IS '수출상대국코드';
COMMENT ON COLUMN CSPD201TM.HS_CD IS 'HS코드';

-- ------------------------------------------------------------
-- CSPD202TM: 수입 원장
-- ------------------------------------------------------------
CREATE TABLE CSPD202TM (
    CSNO                             VARCHAR2(255),
    CUS_KORL_NM                      VARCHAR2(300),
    CUS_ENG_NM                       VARCHAR2(300),
    FX_ACNO                          VARCHAR2(64),
    TDOC_RCP_AM                      NUMBER(20,4),
    TDOC_RCP_CUCD                    VARCHAR2(255),
    TDOC_RCP_SRNO                    NUMBER(19),
    TDOC_RCP_DT                      VARCHAR2(8),
    INPT_ATMC_REQ_DSCD               VARCHAR2(32),
    TRN_OPR_NO                       VARCHAR2(64),
    INPT_ATMC_BIZ_DSCD               VARCHAR2(32),
    KRBR_NM                          VARCHAR2(300),
    DACC_BRCD                        VARCHAR2(32),
    XPO_NACD                         VARCHAR2(32),
    HS_CD                            VARCHAR2(32)
,
    CONSTRAINT PK_CSPD202TM PRIMARY KEY (TDOC_RCP_SRNO)
);

COMMENT ON TABLE CSPD202TM IS '수입 원장';
COMMENT ON COLUMN CSPD202TM.CSNO IS '고객번호';
COMMENT ON COLUMN CSPD202TM.CUS_KORL_NM IS '고객 한글명';
COMMENT ON COLUMN CSPD202TM.CUS_ENG_NM IS '고객 영문명';
COMMENT ON COLUMN CSPD202TM.FX_ACNO IS '외환 계좌번호';
COMMENT ON COLUMN CSPD202TM.TDOC_RCP_AM IS '무역서류 접수 금액';
COMMENT ON COLUMN CSPD202TM.TDOC_RCP_CUCD IS '무역서류 접수 통화 코드';
COMMENT ON COLUMN CSPD202TM.TDOC_RCP_SRNO IS '무역서류 접수 일련번호';
COMMENT ON COLUMN CSPD202TM.TDOC_RCP_DT IS '무역서류 접수 일자';
COMMENT ON COLUMN CSPD202TM.INPT_ATMC_REQ_DSCD IS '심사 자동화 요청 구분 코드';
COMMENT ON COLUMN CSPD202TM.TRN_OPR_NO IS '조작자 사번';
COMMENT ON COLUMN CSPD202TM.INPT_ATMC_BIZ_DSCD IS '심사 자동화 업무 구분 코드';
COMMENT ON COLUMN CSPD202TM.KRBR_NM IS '영업점명';
COMMENT ON COLUMN CSPD202TM.DACC_BRCD IS '일계점코드(영업점코드)';
COMMENT ON COLUMN CSPD202TM.XPO_NACD IS '수출상대국코드';
COMMENT ON COLUMN CSPD202TM.HS_CD IS 'HS코드';

-- ------------------------------------------------------------
-- CSPD810TH: 로그인 이력
-- ------------------------------------------------------------
CREATE TABLE CSPD810TH (
    AI_INPT_LGIN_DTM                 VARCHAR2(20),
    AI_INPT_LGIN_HST_NO              VARCHAR2(64),
    AI_INPT_LGIN_USER_MCHR_NM        VARCHAR2(300),
    AI_INPT_LGIN_USER_NO             VARCHAR2(64),
    AI_INPT_LGIN_USG_IPAD            VARCHAR2(255),
    AI_INPT_LGIN_YN                  CHAR(1),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD810TH PRIMARY KEY (AI_INPT_LGIN_HST_NO)
);

COMMENT ON TABLE CSPD810TH IS '로그인 이력';
COMMENT ON COLUMN CSPD810TH.AI_INPT_LGIN_DTM IS 'AI 심사 로그인 일시';
COMMENT ON COLUMN CSPD810TH.AI_INPT_LGIN_HST_NO IS 'AI 심사 로그인 이력 번호';
COMMENT ON COLUMN CSPD810TH.AI_INPT_LGIN_USER_MCHR_NM IS 'AI 심사 로그인 사용자 기기명';
COMMENT ON COLUMN CSPD810TH.AI_INPT_LGIN_USER_NO IS 'AI 심사 로그인 사용자 번호';
COMMENT ON COLUMN CSPD810TH.AI_INPT_LGIN_USG_IPAD IS 'AI 심사 로그인 사용 IP 주소';
COMMENT ON COLUMN CSPD810TH.AI_INPT_LGIN_YN IS 'AI 심사 로그인 여부';
COMMENT ON COLUMN CSPD810TH.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD810TH.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD810TH.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD811TH: 프로그램 사용 이력
-- ------------------------------------------------------------
CREATE TABLE CSPD811TH (
    AI_INPT_CNCT_ACTI_CD             VARCHAR2(32),
    AI_INPT_CNCT_FLD_CD              VARCHAR2(32),
    AI_INPT_CNCT_IPAD                VARCHAR2(255),
    AI_INPT_CNCT_MCHR_NM             VARCHAR2(300),
    AI_INPT_CNCT_PARM_TXT            CLOB,
    AI_INPT_CNCT_SCRN_NO             VARCHAR2(64),
    AI_INPT_CNCT_URL_NM              VARCHAR2(300),
    AI_INPT_CNCT_USER_NO             VARCHAR2(64),
    AI_INPT_PGM_USG_HST_NO           VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    TRN_LOG_SRNO                     VARCHAR2(60)
,
    CONSTRAINT PK_CSPD811TH PRIMARY KEY (AI_INPT_PGM_USG_HST_NO)
);

COMMENT ON TABLE CSPD811TH IS '프로그램 사용 이력';
COMMENT ON COLUMN CSPD811TH.AI_INPT_CNCT_ACTI_CD IS 'AI 심사 접속 행위 코드';
COMMENT ON COLUMN CSPD811TH.AI_INPT_CNCT_FLD_CD IS 'AI 심사 접속 필드 코드';
COMMENT ON COLUMN CSPD811TH.AI_INPT_CNCT_IPAD IS 'AI 심사 접속 IP 주소';
COMMENT ON COLUMN CSPD811TH.AI_INPT_CNCT_MCHR_NM IS 'AI 심사 접속 기기명';
COMMENT ON COLUMN CSPD811TH.AI_INPT_CNCT_PARM_TXT IS 'AI 심사 접속 파라미터 내용';
COMMENT ON COLUMN CSPD811TH.AI_INPT_CNCT_SCRN_NO IS 'AI 심사 접속 화면 번호';
COMMENT ON COLUMN CSPD811TH.AI_INPT_CNCT_URL_NM IS 'AI 심사 접속 URL명';
COMMENT ON COLUMN CSPD811TH.AI_INPT_CNCT_USER_NO IS 'AI 심사 접속 사용자 번호';
COMMENT ON COLUMN CSPD811TH.AI_INPT_PGM_USG_HST_NO IS 'AI 심사 프로그램 사용 이력 번호';
COMMENT ON COLUMN CSPD811TH.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD811TH.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD811TH.TRN_LOG_SRNO IS '거래 로그 일련번호';

-- ------------------------------------------------------------
-- CSPD900TI: 재처리 상태 정보
-- ------------------------------------------------------------
CREATE TABLE CSPD900TI (
    AI_INPT_PRC_DSCD                 VARCHAR2(32),
    AI_SYS_INPT_PRG_STCD             VARCHAR2(32),
    AI_INPT_SVR_INF_TXT              VARCHAR2(300),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    LST_DB_CHG_ID                    VARCHAR2(64),
    RPROC_TCN                        NUMBER(19),
    INPT_MST_SRNO                    NUMBER(19)
,
    CONSTRAINT PK_CSPD900TI PRIMARY KEY (INPT_MST_SRNO)
);

COMMENT ON TABLE CSPD900TI IS '재처리 상태 정보';
COMMENT ON COLUMN CSPD900TI.AI_INPT_PRC_DSCD IS 'AI 심사 처리 구분 코드';
COMMENT ON COLUMN CSPD900TI.AI_SYS_INPT_PRG_STCD IS 'AI 시스템 심사 진행 상태 코드';
COMMENT ON COLUMN CSPD900TI.AI_INPT_SVR_INF_TXT IS 'AI 심사 수행 서버 정보';
COMMENT ON COLUMN CSPD900TI.LST_DB_CHG_DTM IS '최종 DB 변경 일시';
COMMENT ON COLUMN CSPD900TI.LST_DB_CHG_ID IS '최종 DB 변경 ID';
COMMENT ON COLUMN CSPD900TI.RPROC_TCN IS '재처리 차수';
COMMENT ON COLUMN CSPD900TI.INPT_MST_SRNO IS '심사 마스터 일련번호';

