-- ============================================================
-- SCR-7050-v2 사용자 권한 관리 — 테이블 + 시드 (fix)
-- Tibero / Oracle
-- 실행: 03_test_data 이후, 27_qa_integ_v2 / 07_menu_role_test_data 이전
--       00_drop → 01_ddl → 02_sequence → 03_test_data → 26_task_auth_v2 → 27_qa_integ_v2 → 07 → 04~06
-- 운영 실데이터 이관: 26 적용 후 sql/30_task_auth_mig.sql
--       docs/to-be/업무권한_TO-BE_데이터_마이그레이션.md
-- 런타임 소스 의존: TaskAuth_SQL (selectCanActYn/selectTaskPolicy/countUserTaskRoleForTask)
--                   CommonRevertDetail_SQL (selectStdInfo TASK_CD/APPV_DEPTH)
-- 변경 목록: docs/to-be/권한_TO-BE_전환_변경_목록.md
-- 문서: docs/wireframes/ui/task-authV2/docs/DB-CRUD-GUIDE.md
--
-- 번호: 119~124, 127  (126 = 항목검출설정 예약, 사용 금지)
-- 물리 FK 없음 (프로젝트 관례). 조인키 = AI_INPT_USER_ENO, AI_INPT_TASK_CD
-- PL/SQL·슬래시(/) 없이 DDL 만 사용. DROP 은 00_drop.sql.
-- ============================================================

-- ------------------------------------------------------------
-- 0) 시퀀스
--    00_drop 이 CSPD120~123 을 이미 삭제함. PL/SQL·슬래시(/) 없이 DDL 만 사용.
--    이미 있으면: DROP SEQUENCE CSPD120TI_SG01; 을 먼저 실행한 뒤 이어서 실행
-- ------------------------------------------------------------
CREATE SEQUENCE CSPD120TI_SG01
    START WITH 1000
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE CSPD121TI_SG01
    START WITH 1000
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE CSPD122TI_SG01
    START WITH 1000
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE CSPD123TH_SG01
    START WITH 1000
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


-- ------------------------------------------------------------
-- 1) ALTER CSPD101TI
-- ------------------------------------------------------------
ALTER TABLE CSPD101TI ADD AI_INPT_USER_TYP_CD VARCHAR2(32);
ALTER TABLE CSPD101TI ADD AI_INPT_BRCD VARCHAR2(32);
ALTER TABLE CSPD101TI ADD AI_INPT_PREV_BRCD VARCHAR2(32);
ALTER TABLE CSPD101TI ADD AI_INPT_BRCD_CHG_DTM VARCHAR2(20);

COMMENT ON COLUMN CSPD101TI.AI_INPT_USER_TYP_CD IS '사용자유형 (RVW/GEN/QA/IT)';
COMMENT ON COLUMN CSPD101TI.AI_INPT_BRCD IS '소속점코드';
COMMENT ON COLUMN CSPD101TI.AI_INPT_PREV_BRCD IS '직전 소속점코드 (변경 감지)';
COMMENT ON COLUMN CSPD101TI.AI_INPT_BRCD_CHG_DTM IS '소속점 변경 일시';

CREATE UNIQUE INDEX UK_CSPD101TI_ENO ON CSPD101TI (AI_INPT_USER_ENO);

-- ------------------------------------------------------------
-- 2) CSPD119TI 업무 마스터
-- ------------------------------------------------------------
CREATE TABLE CSPD119TI (
    AI_INPT_TASK_CD                  VARCHAR2(32)   NOT NULL,
    AI_INPT_TASK_NM                  VARCHAR2(300)  NOT NULL,
    AI_INPT_TASK_GRP_CD              VARCHAR2(32)   NOT NULL,
    INPT_ATMC_BIZ_DSCD               VARCHAR2(32),
    AI_INPT_TASK_SORT_SEQ            NUMBER(19),
    AI_INPT_DUAL_ROLE_YN             CHAR(1)        DEFAULT 'N' NOT NULL,
    AI_INPT_APPROV_DEPTH             CHAR(1)        DEFAULT '2' NOT NULL,
    AI_INPT_AI_STP_YN                CHAR(1)        DEFAULT 'N' NOT NULL,
    AI_INPT_TASK_USG_YN              CHAR(1)        DEFAULT 'Y' NOT NULL,
    AI_INPT_RMRK_TXT                 VARCHAR2(1000),
    TRN_LOG_SRNO                     VARCHAR2(60),
    LST_DB_CHG_ID                    VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    CONSTRAINT PK_CSPD119TI PRIMARY KEY (AI_INPT_TASK_CD),
    CONSTRAINT UK_CSPD119TI_01 UNIQUE (INPT_ATMC_BIZ_DSCD),
    CONSTRAINT CK_CSPD119TI_01 CHECK (AI_INPT_DUAL_ROLE_YN IN ('Y', 'N')),
    CONSTRAINT CK_CSPD119TI_02 CHECK (AI_INPT_APPROV_DEPTH IN ('1', '2')),
    CONSTRAINT CK_CSPD119TI_03 CHECK (AI_INPT_AI_STP_YN IN ('Y', 'N'))
);

COMMENT ON TABLE  CSPD119TI IS '업무(Task) 마스터 — 겸임·기본Depth·AI 1차심사';
COMMENT ON COLUMN CSPD119TI.AI_INPT_TASK_CD IS '업무 코드';
COMMENT ON COLUMN CSPD119TI.AI_INPT_TASK_NM IS '업무명';
COMMENT ON COLUMN CSPD119TI.AI_INPT_TASK_GRP_CD IS '업무군 (SHIP/BPR_NEW/BPR_SANC)';
COMMENT ON COLUMN CSPD119TI.INPT_ATMC_BIZ_DSCD IS '심사 자동화 업무 구분 코드';
COMMENT ON COLUMN CSPD119TI.AI_INPT_DUAL_ROLE_YN IS '동일건 C1/C2 겸임 가능 여부';
COMMENT ON COLUMN CSPD119TI.AI_INPT_APPROV_DEPTH IS '기본 심사단계 (1=C1완료, 2=C1-C2)';
COMMENT ON COLUMN CSPD119TI.AI_INPT_AI_STP_YN IS '조건부 AI 1차심사 지정 여부';
COMMENT ON COLUMN CSPD119TI.AI_INPT_TASK_USG_YN IS '사용 여부';

CREATE INDEX IDX_CSPD119TI_01 ON CSPD119TI (AI_INPT_TASK_GRP_CD, AI_INPT_TASK_USG_YN, AI_INPT_TASK_SORT_SEQ);

-- ------------------------------------------------------------
-- 3) CSPD120TI 사용자 x 업무 매트릭스
-- ------------------------------------------------------------
CREATE TABLE CSPD120TI (
    AI_INPT_TASK_ROLE_ID             NUMBER(19)     NOT NULL,
    AI_INPT_USER_ENO                 VARCHAR2(64)   NOT NULL,
    AI_INPT_TASK_CD                  VARCHAR2(32)   NOT NULL,
    AI_INPT_C1_YN                    CHAR(1)        DEFAULT 'N' NOT NULL,
    AI_INPT_C2_YN                    CHAR(1)        DEFAULT 'N' NOT NULL,
    AI_INPT_DFLT_C2_ENO              VARCHAR2(64),
    AI_INPT_ROLE_STA_DTM             VARCHAR2(20)   NOT NULL,
    AI_INPT_ROLE_END_DTM             VARCHAR2(20)   DEFAULT '99991231235959' NOT NULL,
    AI_INPT_ROLE_USG_YN              CHAR(1)        DEFAULT 'Y' NOT NULL,
    AI_INPT_RMRK_TXT                 VARCHAR2(1000),
    TRN_LOG_SRNO                     VARCHAR2(60),
    LST_DB_CHG_ID                    VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    CONSTRAINT PK_CSPD120TI PRIMARY KEY (AI_INPT_TASK_ROLE_ID),
    CONSTRAINT UK_CSPD120TI_01 UNIQUE (AI_INPT_USER_ENO, AI_INPT_TASK_CD),
    CONSTRAINT CK_CSPD120TI_01 CHECK (AI_INPT_C1_YN IN ('Y', 'N')),
    CONSTRAINT CK_CSPD120TI_02 CHECK (AI_INPT_C2_YN IN ('Y', 'N'))
);

COMMENT ON TABLE  CSPD120TI IS '업무별 사용자 권한 매트릭스 (C1/C2 체크)';
COMMENT ON COLUMN CSPD120TI.AI_INPT_C1_YN IS 'C1 1차심사 권한';
COMMENT ON COLUMN CSPD120TI.AI_INPT_C2_YN IS 'C2 2차결재 권한';
COMMENT ON COLUMN CSPD120TI.AI_INPT_DFLT_C2_ENO IS '기본 결재자 직원번호 (AUTO=풀 배정)';

CREATE INDEX IDX_CSPD120TI_01 ON CSPD120TI (AI_INPT_USER_ENO, AI_INPT_ROLE_USG_YN);
CREATE INDEX IDX_CSPD120TI_02 ON CSPD120TI (AI_INPT_TASK_CD, AI_INPT_C1_YN, AI_INPT_C2_YN);

-- ------------------------------------------------------------
-- 4) CSPD121TI 승인 Depth 조건부 규칙 (SCR-7052)
-- ------------------------------------------------------------
CREATE TABLE CSPD121TI (
    AI_INPT_DEPTH_RULE_ID            NUMBER(19)     NOT NULL,
    AI_INPT_TASK_CD                  VARCHAR2(32),
    AI_INPT_RULE_PRIO                NUMBER(19)     DEFAULT 100 NOT NULL,
    AI_INPT_COND_TYPE                VARCHAR2(32)   NOT NULL,
    AI_INPT_COND_OPERATOR            VARCHAR2(32)   NOT NULL,
    AI_INPT_COND_VALUE               VARCHAR2(500)  NOT NULL,
    AI_INPT_APPROV_DEPTH             CHAR(1)        NOT NULL,
    AI_INPT_RULE_USG_YN              CHAR(1)        DEFAULT 'Y' NOT NULL,
    AI_INPT_RMRK_TXT                 VARCHAR2(1000),
    TRN_LOG_SRNO                     VARCHAR2(60),
    LST_DB_CHG_ID                    VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    CONSTRAINT PK_CSPD121TI PRIMARY KEY (AI_INPT_DEPTH_RULE_ID),
    CONSTRAINT CK_CSPD121TI_01 CHECK (AI_INPT_APPROV_DEPTH IN ('1', '2'))
);

COMMENT ON TABLE  CSPD121TI IS '승인 Depth 조건부 규칙 (SCR-7052). 기본값은 CSPD119TI';
COMMENT ON COLUMN CSPD121TI.AI_INPT_TASK_CD IS '업무코드 NULL=공통';
COMMENT ON COLUMN CSPD121TI.AI_INPT_APPROV_DEPTH IS '승인 Depth (1=C1단독, 2=C1-C2)';

CREATE INDEX IDX_CSPD121TI_01 ON CSPD121TI (AI_INPT_TASK_CD, AI_INPT_RULE_USG_YN, AI_INPT_RULE_PRIO);

-- ------------------------------------------------------------
-- 5) CSPD122TI 사용자 화면 접근 (SCR-7050 v1)
-- ------------------------------------------------------------
CREATE TABLE CSPD122TI (
    AI_INPT_SCRN_ACS_ID              NUMBER(19)     NOT NULL,
    AI_INPT_USER_ENO                 VARCHAR2(64)   NOT NULL,
    AI_INPT_SCRN_NO                  VARCHAR2(32)   NOT NULL,
    AI_INPT_SCRN_ACS_YN              CHAR(1)        DEFAULT 'Y' NOT NULL,
    AI_INPT_RMRK_TXT                 VARCHAR2(1000),
    TRN_LOG_SRNO                     VARCHAR2(60),
    LST_DB_CHG_ID                    VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    CONSTRAINT PK_CSPD122TI PRIMARY KEY (AI_INPT_SCRN_ACS_ID),
    CONSTRAINT UK_CSPD122TI_01 UNIQUE (AI_INPT_USER_ENO, AI_INPT_SCRN_NO)
);

COMMENT ON TABLE CSPD122TI IS '사용자 화면별 접근권한 예외 (7050 v1)';
CREATE INDEX IDX_CSPD122TI_01 ON CSPD122TI (AI_INPT_USER_ENO, AI_INPT_SCRN_ACS_YN);

-- ------------------------------------------------------------
-- 6) CSPD123TH 권한 변경 이력
-- ------------------------------------------------------------
CREATE TABLE CSPD123TH (
    AI_INPT_AUTH_CHG_SRNO            NUMBER(19)     NOT NULL,
    AI_INPT_CHG_TYP_CD               VARCHAR2(32)   NOT NULL,
    AI_INPT_USER_ENO                 VARCHAR2(64),
    AI_INPT_TASK_CD                  VARCHAR2(32),
    AI_INPT_BF_CHG_TXT               CLOB,
    AI_INPT_AF_CHG_TXT               CLOB,
    AI_INPT_CHG_USER_ENO             VARCHAR2(64)   NOT NULL,
    AI_INPT_CHG_DTM                  VARCHAR2(20)   NOT NULL,
    TRN_LOG_SRNO                     VARCHAR2(60),
    LST_DB_CHG_ID                    VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    CONSTRAINT PK_CSPD123TH PRIMARY KEY (AI_INPT_AUTH_CHG_SRNO)
);

COMMENT ON TABLE  CSPD123TH IS '권한·역할·STP 변경 이력';
COMMENT ON COLUMN CSPD123TH.AI_INPT_CHG_TYP_CD IS 'USER_TYP/MATRIX/QA_PROF/TASK_POL/STP_CFG/BRCD_GEN/SCRN_ACS/DEPTH_RULE';

CREATE INDEX IDX_CSPD123TH_01 ON CSPD123TH (AI_INPT_USER_ENO, AI_INPT_CHG_DTM);
CREATE INDEX IDX_CSPD123TH_02 ON CSPD123TH (AI_INPT_CHG_TYP_CD, AI_INPT_CHG_DTM);

-- ------------------------------------------------------------
-- 7) CSPD124TI QA 권한 프로필
-- ------------------------------------------------------------
CREATE TABLE CSPD124TI (
    AI_INPT_USER_ENO                 VARCHAR2(64)   NOT NULL,
    AI_INPT_QA1_YN                   CHAR(1)        DEFAULT 'N' NOT NULL,
    AI_INPT_QA2_YN                   CHAR(1)        DEFAULT 'N' NOT NULL,
    AI_INPT_DFLT_QA2_ENO             VARCHAR2(64),
    AI_INPT_QA_EXP_YN                CHAR(1)        DEFAULT 'N' NOT NULL,
    AI_INPT_QA_WRK_YN                CHAR(1)        DEFAULT 'N' NOT NULL,
    AI_INPT_QA_SW_YN                 CHAR(1)        DEFAULT 'N' NOT NULL,
    AI_INPT_RMRK_TXT                 VARCHAR2(1000),
    TRN_LOG_SRNO                     VARCHAR2(60),
    LST_DB_CHG_ID                    VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    CONSTRAINT PK_CSPD124TI PRIMARY KEY (AI_INPT_USER_ENO),
    CONSTRAINT CK_CSPD124TI_01 CHECK (AI_INPT_QA1_YN IN ('Y', 'N')),
    CONSTRAINT CK_CSPD124TI_02 CHECK (AI_INPT_QA2_YN IN ('Y', 'N'))
);

COMMENT ON TABLE  CSPD124TI IS 'QA 권한 프로필 (QA1 점검 / QA2 검토 / 대상업무)';
COMMENT ON COLUMN CSPD124TI.AI_INPT_QA1_YN IS 'QA1 점검자 (결과 입력·수정)';
COMMENT ON COLUMN CSPD124TI.AI_INPT_QA2_YN IS 'QA2 검토 승인자';
COMMENT ON COLUMN CSPD124TI.AI_INPT_DFLT_QA2_ENO IS '기본 검토자 (AUTO=자동배정)';
COMMENT ON COLUMN CSPD124TI.AI_INPT_QA_EXP_YN IS 'QA 대상 수출입';
COMMENT ON COLUMN CSPD124TI.AI_INPT_QA_WRK_YN IS 'QA 대상 워크';
COMMENT ON COLUMN CSPD124TI.AI_INPT_QA_SW_YN IS 'QA 대상 SafeWatch';

-- ------------------------------------------------------------
-- 8) CSPD127TI AI 1차심사(STP) 공통 설정
-- ------------------------------------------------------------
CREATE TABLE CSPD127TI (
    AI_INPT_STP_CFG_ID               VARCHAR2(32)   NOT NULL,
    AI_INPT_STP_ACTV_YN              CHAR(1)        DEFAULT 'N' NOT NULL,
    AI_INPT_ITM_COND_CD              VARCHAR2(32)   DEFAULT 'CLEAN' NOT NULL,
    AI_INPT_TT_COND_CD               VARCHAR2(32)   DEFAULT 'CLEAN' NOT NULL,
    AI_INPT_SW_COND_CD               VARCHAR2(32)   DEFAULT 'CLEAN' NOT NULL,
    AI_INPT_AMT_CCY_CD               VARCHAR2(8)    DEFAULT 'USD',
    AI_INPT_AMT_CAP                  NUMBER(19,2),
    AI_INPT_QA_SMPL_RT               NUMBER(5,2)    DEFAULT 20,
    AI_INPT_KEEP_C2_YN               CHAR(1)        DEFAULT 'Y' NOT NULL,
    AI_INPT_RMRK_TXT                 VARCHAR2(1000),
    TRN_LOG_SRNO                     VARCHAR2(60),
    LST_DB_CHG_ID                    VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    CONSTRAINT PK_CSPD127TI PRIMARY KEY (AI_INPT_STP_CFG_ID),
    CONSTRAINT CK_CSPD127TI_01 CHECK (AI_INPT_STP_ACTV_YN IN ('Y', 'N')),
    CONSTRAINT CK_CSPD127TI_02 CHECK (AI_INPT_KEEP_C2_YN IN ('Y', 'N'))
);

COMMENT ON TABLE  CSPD127TI IS '조건부 AI 1차심사 공통 설정 (싱글톤 GLOBAL)';
COMMENT ON COLUMN CSPD127TI.AI_INPT_STP_ACTV_YN IS 'Y=지정 업무만 활성, N=전체 비활성';
COMMENT ON COLUMN CSPD127TI.AI_INPT_AMT_CAP IS '금액 상한 (통화=AMT_CCY_CD)';
COMMENT ON COLUMN CSPD127TI.AI_INPT_QA_SMPL_RT IS '자동심사 건 QA 샘플 비율(%)';
COMMENT ON COLUMN CSPD127TI.AI_INPT_KEEP_C2_YN IS '자동 건도 C2 결재 유지';

-- ------------------------------------------------------------
-- 9) ALTER CSPD001TM / CSPD005TH
-- ------------------------------------------------------------
ALTER TABLE CSPD001TM ADD AI_INPT_TASK_CD VARCHAR2(32);
ALTER TABLE CSPD001TM ADD AI_INPT_APPV_DEPTH_CD CHAR(1);
ALTER TABLE CSPD001TM ADD AI_INPT_AI_STP_YN CHAR(1) DEFAULT 'N';

COMMENT ON COLUMN CSPD001TM.AI_INPT_TASK_CD IS '업무 코드 (CSPD119TI)';
COMMENT ON COLUMN CSPD001TM.AI_INPT_APPV_DEPTH_CD IS '확정 승인 Depth (1/2)';
COMMENT ON COLUMN CSPD001TM.AI_INPT_AI_STP_YN IS 'C1 AI 자동처리 여부';

CREATE INDEX IDX_CSPD001TM_TASK ON CSPD001TM (AI_INPT_TASK_CD, AI_INPT_APPV_DEPTH_CD);

ALTER TABLE CSPD005TH ADD AI_INPT_STAGE_ROLE_CD VARCHAR2(32);
ALTER TABLE CSPD005TH ADD AI_INPT_APPROV_DEPTH_CD CHAR(1);
ALTER TABLE CSPD005TH ADD AI_INPT_FINAL_YN CHAR(1) DEFAULT 'N';
ALTER TABLE CSPD005TH ADD AI_INPT_AI_STP_YN CHAR(1) DEFAULT 'N';

COMMENT ON COLUMN CSPD005TH.AI_INPT_STAGE_ROLE_CD IS '처리 단계 (C1/C2/QA1/QA2)';
COMMENT ON COLUMN CSPD005TH.AI_INPT_APPROV_DEPTH_CD IS '승인 Depth (1/2)';
COMMENT ON COLUMN CSPD005TH.AI_INPT_FINAL_YN IS '최종 승인 여부';
COMMENT ON COLUMN CSPD005TH.AI_INPT_AI_STP_YN IS 'AI 자동 C1 여부';

-- ------------------------------------------------------------
-- 10) 시드 — 목업 17업무 + STP GLOBAL
-- ------------------------------------------------------------
DELETE FROM CSPD119TI;
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('SHIP_IMP',        '수입',                         'SHIP',     'SHIP_IMP',        10, 'N', '2', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('SHIP_EXP',        '수출',                         'SHIP',     'SHIP_EXP',        20, 'N', '2', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRN_HI_RISK',    '고위험대상 SANCTION 심사의뢰', 'BPR_NEW',  'BPRN_HI_RISK',    30, 'N', '2', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRN_IRAN_KRW',   '이란원화결제타발지급',         'BPR_NEW',  'BPRN_IRAN_KRW',   40, 'N', '2', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRN_IRAN_BYPASS','이란 등 우회주의국가 타발지급','BPR_NEW',  'BPRN_IRAN_BYPASS',50, 'N', '2', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRN_RU',         '러시아관련 외환거래 사전검토', 'BPR_NEW',  'BPRN_RU',         60, 'N', '2', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRN_SSI',        'SSI심화검토 및 BIS LIST 검토', 'BPR_NEW',  'BPRN_SSI',        70, 'N', '2', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRN_TRADE',      '무역안보관리원 의뢰건',         'BPR_NEW',  'BPRN_TRADE',      80, 'N', '2', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRS_EXP_BILL',   '수출환어음매입',               'BPR_SANC', 'BPRS_EXP_BILL',   90, 'Y', '1', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRS_EXP_COLL',   '수출환어음추심',               'BPR_SANC', 'BPRS_EXP_COLL',  100, 'Y', '1', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRS_MAIL_LC',    'MAIL L/C',                    'BPR_SANC', 'BPRS_MAIL_LC',   110, 'Y', '1', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRS_IMP_LC',     '수입신용장개설',               'BPR_SANC', 'BPRS_IMP_LC',    120, 'Y', '1', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRS_IMP_LC_AMD', '수입신용장조건변경',           'BPR_SANC', 'BPRS_IMP_LC_AMD',130, 'Y', '1', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRS_LG',         '수입화환물선취보증(L/G)',      'BPR_SANC', 'BPRS_LG',        140, 'Y', '1', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRS_REMIT',      '당발송금',                     'BPR_SANC', 'BPRS_REMIT',     150, 'Y', '2', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRS_FG',         '외화지급보증신규',             'BPR_SANC', 'BPRS_FG',        160, 'Y', '1', 'N', 'Y', 'SYSTEM', '20260815120000');
INSERT INTO CSPD119TI (AI_INPT_TASK_CD, AI_INPT_TASK_NM, AI_INPT_TASK_GRP_CD, INPT_ATMC_BIZ_DSCD, AI_INPT_TASK_SORT_SEQ, AI_INPT_DUAL_ROLE_YN, AI_INPT_APPROV_DEPTH, AI_INPT_AI_STP_YN, AI_INPT_TASK_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('BPRS_FX_REQ',     '외환업무요청',                 'BPR_SANC', 'BPRS_FX_REQ',    170, 'Y', '2', 'N', 'Y', 'SYSTEM', '20260815120000');

DELETE FROM CSPD127TI;
INSERT INTO CSPD127TI (
    AI_INPT_STP_CFG_ID, AI_INPT_STP_ACTV_YN,
    AI_INPT_ITM_COND_CD, AI_INPT_TT_COND_CD, AI_INPT_SW_COND_CD,
    AI_INPT_AMT_CCY_CD, AI_INPT_AMT_CAP, AI_INPT_QA_SMPL_RT, AI_INPT_KEEP_C2_YN,
    AI_INPT_RMRK_TXT, LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    'GLOBAL', 'N',
    'CLEAN', 'CLEAN', 'CLEAN',
    'USD', 50000, 20, 'Y',
    '준법·내부통제 협의 승인 후 활성', 'SYSTEM', '20260815120000'
);

-- 메뉴: 사용자 권한 관리 [7045]
MERGE INTO CSPD108TI t
USING (SELECT '701200' AS ID FROM DUAL) s
   ON (t.AI_INPT_MENU_ID = s.ID)
 WHEN NOT MATCHED THEN INSERT (
    AI_INPT_MENU_ID, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_NM, AI_INPT_MENU_NO,
    AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
    '701200', '700000', '사용자 권한 관리', '7045',
    '/admin/taskAuth', 'Y', '48', 'SYSTEM', '20260815120000'
 );

MERGE INTO CSPD112TI t
USING (SELECT '165' AS GRP, '7045' AS CD FROM DUAL) s
   ON (t.AI_INPT_GRP_CD = s.GRP AND t.AI_INPT_CMN_CD = s.CD)
 WHEN NOT MATCHED THEN INSERT (
    AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM,
    AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT,
    AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
    '165', '7045', '사용자 권한 관리', 'Task Auth',
    '20200101000000', '99991231235959', 'Y', '화면-7045',
    '사용자권한', '40', '86', 'SYSTEM', '20260815120000'
 );

-- 메뉴등록(7031) 3단 트리: ROOT 000000 → 대메뉴(x00000) → 화면
-- CommonMenu_SQL 은 000000 을 LNB 에서 제외. selectListTopMenu 는 DEPTH=2 만 콤보에 표시.
MERGE INTO CSPD108TI t
USING (SELECT '000000' AS ID FROM DUAL) s
   ON (t.AI_INPT_MENU_ID = s.ID)
 WHEN NOT MATCHED THEN INSERT (
    AI_INPT_MENU_ID, AI_INPT_HGRN_MENU_ID, AI_INPT_MENU_NM, AI_INPT_MENU_NO,
    AI_INPT_MENU_URL_NM, AI_INPT_MGPE_YN, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
    '000000', NULL, 'ROOT', NULL, NULL, 'N', '0', 'SYSTEM', '20260815120000'
 );

UPDATE CSPD108TI
   SET AI_INPT_HGRN_MENU_ID = '000000'
 WHERE AI_INPT_MENU_ID IN (
       '100000', '200000', '300000', '400000',
       '500000', '600000', '700000', '800000'
 )
   AND AI_INPT_HGRN_MENU_ID IS NULL;

-- 시스템관리(8xxx)는 관리자 화면(MGPE=Y)이 아님. AUT=05 전용.
-- CommonMenu 는 비관리자에게 MGPE=Y 를 숨기고, 자식이 없으면 대메뉴도 접음.
UPDATE CSPD108TI
   SET AI_INPT_MGPE_YN = 'N',
       LST_DB_CHG_ID = 'SYSTEM',
       LST_DB_CHG_DTM = '20260815120000'
 WHERE AI_INPT_MENU_ID LIKE '8%';

MERGE INTO CSPD109TI t
USING (
    SELECT 189 AS AUT_ID, '701200' AS MENU_ID, '01' AS AUT_CD FROM DUAL UNION ALL
    SELECT 190, '701200', '02' FROM DUAL UNION ALL
    SELECT 191, '701200', '03' FROM DUAL UNION ALL
    SELECT 192, '701200', '04' FROM DUAL
) s ON (t.AI_INPT_AUT_ID = s.AUT_ID)
 WHEN NOT MATCHED THEN INSERT (
    AI_INPT_AUT_ID, AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN,
    AI_INPT_RMRK_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
    s.AUT_ID, s.MENU_ID, s.AUT_CD, 'Y',
    '7050-v2 사용자 권한', TO_CHAR(s.AUT_ID), 'SYSTEM', '20260815120000'
 );

-- 권한코드 05 시스템관리자 (grp 120)
MERGE INTO CSPD112TI t
USING (SELECT '120' AS GRP, '05' AS CD FROM DUAL) s
   ON (t.AI_INPT_GRP_CD = s.GRP AND t.AI_INPT_CMN_CD = s.CD)
 WHEN MATCHED THEN UPDATE SET
       AI_INPT_CMN_CD_NM = '시스템관리자',
       AI_INPT_CMN_CD_ENG_NM = 'System Admin',
       AI_INPT_RMRK_TXT = '권한-시스템관리자',
       AI_INPT_INTF_ITM_NM = '시스템관리자',
       AI_INPT_CMN_USG_YN = 'Y',
       LST_DB_CHG_ID = 'SYSTEM',
       LST_DB_CHG_DTM = '20260815120000'
 WHEN NOT MATCHED THEN INSERT (
    AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM,
    AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT,
    AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
    '120', '05', '시스템관리자', 'System Admin',
    '20200101000000', '99991231235959', 'Y', '권한-시스템관리자',
    '시스템관리자', '5', '200', 'SYSTEM', '20260815120000'
 );

-- AUT 05 × 전 메뉴. 시스템관리(8xxx)만 Y. 07 에서 역할별로 재확인.
INSERT INTO CSPD109TI (
    AI_INPT_AUT_ID, AI_INPT_MENU_ID, AI_INPT_AUT_CD, AI_INPT_AUT_USG_YN,
    AI_INPT_RMRK_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
)
SELECT 200 + ROWNUM,
       m.AI_INPT_MENU_ID,
       '05',
       CASE WHEN m.AI_INPT_MENU_ID LIKE '8%' THEN 'Y' ELSE 'N' END,
       '05-시스템관리자',
       TO_CHAR(200 + ROWNUM),
       'SYSTEM',
       '20260815120000'
  FROM CSPD108TI m
 WHERE NOT EXISTS (
       SELECT 1 FROM CSPD109TI x
        WHERE x.AI_INPT_AUT_CD = '05'
          AND x.AI_INPT_MENU_ID = m.AI_INPT_MENU_ID
 );

UPDATE CSPD109TI
   SET AI_INPT_AUT_USG_YN = CASE WHEN AI_INPT_MENU_ID LIKE '8%' THEN 'Y' ELSE 'N' END,
       AI_INPT_RMRK_TXT = '05-시스템관리자',
       LST_DB_CHG_ID = 'SYSTEM',
       LST_DB_CHG_DTM = '20260815120000'
 WHERE AI_INPT_AUT_CD = '05';

-- 테스트 계정 (03_test_data 이후)
--   review01    E10001  김심사    RVW  AUT=01           0203  전체 C1
--   approv01    E10002  이결재    RVW  AUT=02           0203  선적 C2 / 신규 BPR C1
--   qauser01    E10003  박QA      QA   AUT=03           0203  QA 프로필
--   admin01     E10004  최관리    RVW  AUT=01 + MGPE=Y  0203  전체 C2 + 관리자(7xxx)
--   general01   E10005  정일반    GEN  AUT=04           1877  권한 없음
--   sysadmin01  E10006  한시스템  IT   AUT=05 + MGPE=Y  0203  시스템관리자(8xxx)
--     ※ 관리자(admin01)와 시스템관리자(sysadmin01)는 다름. 로그인은 AUT_CD 단일값.
UPDATE CSPD101TI SET AI_INPT_USER_TYP_CD = NVL(AI_INPT_USER_TYP_CD, 'RVW'), AI_INPT_BRCD = NVL(AI_INPT_BRCD, '0203') WHERE AI_INPT_USER_ENO = 'E10001';
UPDATE CSPD101TI SET AI_INPT_USER_TYP_CD = NVL(AI_INPT_USER_TYP_CD, 'RVW'), AI_INPT_BRCD = NVL(AI_INPT_BRCD, '0203'), AI_INPT_AUT_CD = '02' WHERE AI_INPT_USER_ENO = 'E10002';
UPDATE CSPD101TI SET AI_INPT_USER_TYP_CD = NVL(AI_INPT_USER_TYP_CD, 'QA'),  AI_INPT_BRCD = NVL(AI_INPT_BRCD, '0203') WHERE AI_INPT_USER_ENO = 'E10003';
UPDATE CSPD101TI SET
       AI_INPT_USER_TYP_CD = NVL(AI_INPT_USER_TYP_CD, 'RVW'),
       AI_INPT_AUT_CD      = '01',
       AI_INPT_MGPE_YN     = 'Y',
       AI_INPT_BRCD        = NVL(AI_INPT_BRCD, '0203')
 WHERE AI_INPT_USER_ENO = 'E10004';

MERGE INTO CSPD101TI t
USING (SELECT 'general01' AS USER_ID FROM DUAL) s
   ON (t.AI_INPT_USER_ID = s.USER_ID)
 WHEN NOT MATCHED THEN INSERT (
    AI_INPT_USER_ID, AI_INPT_USER_ENO, AI_INPT_AUT_CD, AI_INPT_MGPE_YN, AI_INPT_USER_NM,
    AI_INPT_USER_YN, AI_INPT_USER_FA_RE_YN, AI_INPT_USER_RGS_DTM, AI_INPT_USER_END_DTM,
    AI_INPT_SRVC_USER_DSCD, AI_INPT_USER_TYP_CD, AI_INPT_BRCD, AI_INPT_PREV_BRCD, AI_INPT_BRCD_CHG_DTM,
    TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
    'general01', 'E10005', '04', 'N', '정일반',
    'Y', 'N', '20200101000000', '99991231235959',
    '01', 'GEN', '1877', '0203', '20260801120000',
    '5', 'SYSTEM', '20250115120000'
 );

MERGE INTO CSPD101TI t
USING (SELECT 'sysadmin01' AS USER_ID FROM DUAL) s
   ON (t.AI_INPT_USER_ID = s.USER_ID)
 WHEN MATCHED THEN UPDATE SET
       AI_INPT_USER_ENO    = 'E10006',
       AI_INPT_AUT_CD      = '05',
       AI_INPT_MGPE_YN     = 'Y',
       AI_INPT_USER_NM     = '한시스템',
       AI_INPT_USER_TYP_CD = 'IT',
       AI_INPT_BRCD        = NVL(t.AI_INPT_BRCD, '0203'),
       LST_DB_CHG_ID       = 'SYSTEM',
       LST_DB_CHG_DTM      = '20260815120000'
 WHEN NOT MATCHED THEN INSERT (
    AI_INPT_USER_ID, AI_INPT_USER_ENO, AI_INPT_AUT_CD, AI_INPT_MGPE_YN, AI_INPT_USER_NM,
    AI_INPT_USER_YN, AI_INPT_USER_FA_RE_YN, AI_INPT_USER_RGS_DTM, AI_INPT_USER_END_DTM,
    AI_INPT_SRVC_USER_DSCD, AI_INPT_USER_TYP_CD, AI_INPT_BRCD,
    TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
    'sysadmin01', 'E10006', '05', 'Y', '한시스템',
    'Y', 'N', '20200101000000', '99991231235959',
    '01', 'IT', '0203',
    '6', 'SYSTEM', '20260815120000'
 );

DELETE FROM CSPD120TI WHERE AI_INPT_USER_ENO IN ('E10001', 'E10002', 'E10004');
INSERT INTO CSPD120TI (AI_INPT_TASK_ROLE_ID, AI_INPT_USER_ENO, AI_INPT_TASK_CD, AI_INPT_C1_YN, AI_INPT_C2_YN, AI_INPT_DFLT_C2_ENO, AI_INPT_ROLE_STA_DTM, AI_INPT_ROLE_END_DTM, AI_INPT_ROLE_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
SELECT CSPD120TI_SG01.NEXTVAL, 'E10001', AI_INPT_TASK_CD,
       'Y', CASE WHEN AI_INPT_TASK_GRP_CD = 'BPR_SANC' THEN 'Y' ELSE 'N' END,
       CASE WHEN AI_INPT_APPROV_DEPTH = '2' AND AI_INPT_TASK_GRP_CD <> 'BPR_SANC' THEN 'AUTO' ELSE NULL END,
       '20260815120000', '99991231235959', 'Y', 'SYSTEM', '20260815120000'
  FROM CSPD119TI WHERE AI_INPT_TASK_USG_YN = 'Y';
INSERT INTO CSPD120TI (AI_INPT_TASK_ROLE_ID, AI_INPT_USER_ENO, AI_INPT_TASK_CD, AI_INPT_C1_YN, AI_INPT_C2_YN, AI_INPT_DFLT_C2_ENO, AI_INPT_ROLE_STA_DTM, AI_INPT_ROLE_END_DTM, AI_INPT_ROLE_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
SELECT CSPD120TI_SG01.NEXTVAL, 'E10002', AI_INPT_TASK_CD,
       CASE WHEN AI_INPT_TASK_GRP_CD = 'BPR_NEW' THEN 'Y' ELSE 'N' END,
       CASE WHEN AI_INPT_TASK_GRP_CD = 'SHIP' THEN 'Y' ELSE 'N' END,
       CASE WHEN AI_INPT_TASK_GRP_CD = 'BPR_NEW' THEN 'AUTO' ELSE NULL END,
       '20260815120000', '99991231235959', 'Y', 'SYSTEM', '20260815120000'
  FROM CSPD119TI WHERE AI_INPT_TASK_USG_YN = 'Y' AND AI_INPT_TASK_GRP_CD IN ('SHIP', 'BPR_NEW');
INSERT INTO CSPD120TI (AI_INPT_TASK_ROLE_ID, AI_INPT_USER_ENO, AI_INPT_TASK_CD, AI_INPT_C1_YN, AI_INPT_C2_YN, AI_INPT_DFLT_C2_ENO, AI_INPT_ROLE_STA_DTM, AI_INPT_ROLE_END_DTM, AI_INPT_ROLE_USG_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM)
SELECT CSPD120TI_SG01.NEXTVAL, 'E10004', AI_INPT_TASK_CD,
       'N', 'Y', NULL,
       '20260815120000', '99991231235959', 'Y', 'SYSTEM', '20260815120000'
  FROM CSPD119TI WHERE AI_INPT_TASK_USG_YN = 'Y';

MERGE INTO CSPD124TI t
USING (SELECT 'E10003' AS ENO FROM DUAL) s
   ON (t.AI_INPT_USER_ENO = s.ENO)
 WHEN MATCHED THEN UPDATE SET
       AI_INPT_QA1_YN = 'Y', AI_INPT_QA_EXP_YN = 'Y', AI_INPT_QA_WRK_YN = 'Y',
       AI_INPT_DFLT_QA2_ENO = NVL(AI_INPT_DFLT_QA2_ENO, 'AUTO')
 WHEN NOT MATCHED THEN INSERT (
       AI_INPT_USER_ENO, AI_INPT_QA1_YN, AI_INPT_QA2_YN, AI_INPT_DFLT_QA2_ENO,
       AI_INPT_QA_EXP_YN, AI_INPT_QA_WRK_YN, AI_INPT_QA_SW_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
       'E10003', 'Y', 'N', 'AUTO', 'Y', 'Y', 'N', 'SYSTEM', '20260815120000'
 );

COMMIT;
