-- ============================================================
-- SCR-3010-v2 통합 QA — 테이블 + 시드
-- Tibero / Oracle
-- 실행: 26_task_auth_v2.sql 이후, 07_menu_role_test_data 이전
--       00_drop → 01_ddl → 02_sequence → 03_test_data
--       → 26_task_auth_v2 → 27_qa_integ_v2 → 07 → 04~06
-- 문서: docs/wireframes/ui/qa-safewatchV1/docs/DB-CRUD-GUIDE.md
--
-- 번호: 125, 128, 129 + ALTER 119/107
--   126 = 항목검출설정 예약, 127 = STP, 130~133 = KG — 사용 금지
-- 물리 FK 없음 (프로젝트 관례). PL/SQL·슬래시(/) 없이 DDL 만 사용.
-- DROP 은 00_drop.sql.
-- ============================================================

-- ------------------------------------------------------------
-- 0) 시퀀스 (시드는 1~5 고정. 런타임은 1000부터)
-- ------------------------------------------------------------
CREATE SEQUENCE CSPD125TM_SG01 START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CSPD128TI_SG01 START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CSPD129TH_SG01 START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ------------------------------------------------------------
-- 1) CSPD128TI SafeWatch QA 수기등록 대상
-- ------------------------------------------------------------
CREATE TABLE CSPD128TI (
    AI_INPT_SW_QA_SRNO               NUMBER(19)     NOT NULL,
    AI_INPT_SW_REFNO                 VARCHAR2(64)   NOT NULL,
    FILT_DTCT_NO                     VARCHAR2(64),
    INPT_MST_SRNO                    NUMBER(19),
    AI_INPT_CUST_NO                  VARCHAR2(64)   NOT NULL,
    AI_INPT_CUST_NM                  VARCHAR2(300)  NOT NULL,
    AI_INPT_SW_ORIG_RST_CD           VARCHAR2(32),
    AI_INPT_SW_RMRK_TXT              VARCHAR2(1000),
    AI_INPT_SW_USG_YN                CHAR(1)        DEFAULT 'Y' NOT NULL,
    AI_INPT_RGS_ENO                  VARCHAR2(64)   NOT NULL,
    AI_INPT_RGS_DTM                  VARCHAR2(20)   NOT NULL,
    TRN_LOG_SRNO                     VARCHAR2(60),
    LST_DB_CHG_ID                    VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    CONSTRAINT PK_CSPD128TI PRIMARY KEY (AI_INPT_SW_QA_SRNO),
    CONSTRAINT CK_CSPD128TI_01 CHECK (AI_INPT_SW_USG_YN IN ('Y', 'N'))
);

COMMENT ON TABLE  CSPD128TI IS 'SafeWatch QA 수기등록 대상 — 심사건 없는 SW QA 원장';
COMMENT ON COLUMN CSPD128TI.AI_INPT_SW_QA_SRNO IS 'SafeWatch QA 대상 일련번호';
COMMENT ON COLUMN CSPD128TI.AI_INPT_SW_REFNO IS '화면 REF (권장 SW-숫자)';
COMMENT ON COLUMN CSPD128TI.FILT_DTCT_NO IS '기존 CSPD007TL 탐지번호 (선택)';
COMMENT ON COLUMN CSPD128TI.INPT_MST_SRNO IS '심사건 번호. 목업 수기건은 NULL';
COMMENT ON COLUMN CSPD128TI.AI_INPT_CUST_NO IS '고객번호';
COMMENT ON COLUMN CSPD128TI.AI_INPT_CUST_NM IS '고객명';
COMMENT ON COLUMN CSPD128TI.AI_INPT_SW_ORIG_RST_CD IS '원 SafeWatch 결과 (목록 S/W 열)';
COMMENT ON COLUMN CSPD128TI.AI_INPT_SW_USG_YN IS '사용 여부';
COMMENT ON COLUMN CSPD128TI.AI_INPT_RGS_ENO IS '등록자 직원번호';
COMMENT ON COLUMN CSPD128TI.AI_INPT_RGS_DTM IS '등록 일시';

-- 사용중 REF 중복은 애플리케이션에서 검사 (USG_YN=Y).
-- Tibero 는 CASE 함수기반 UNIQUE INDEX 미지원.
CREATE INDEX IDX_CSPD128TI_01 ON CSPD128TI (AI_INPT_CUST_NO, AI_INPT_SW_USG_YN);
CREATE INDEX IDX_CSPD128TI_02 ON CSPD128TI (FILT_DTCT_NO);
CREATE INDEX IDX_CSPD128TI_03 ON CSPD128TI (AI_INPT_SW_REFNO, AI_INPT_SW_USG_YN);

-- ------------------------------------------------------------
-- 2) CSPD125TM QA 통합점검 마스터
-- ------------------------------------------------------------
CREATE TABLE CSPD125TM (
    AI_INPT_QA_SRNO                  NUMBER(19)     NOT NULL,
    AI_INPT_QA_BIZ_GRP_CD            VARCHAR2(32)   NOT NULL,
    AI_INPT_QA_SRC_CD                VARCHAR2(32)   NOT NULL,
    AI_INPT_QA_TASK_NM               VARCHAR2(300),
    AI_INPT_TASK_CD                  VARCHAR2(32),
    INPT_MST_SRNO                    NUMBER(19),
    AI_INPT_SW_QA_SRNO               NUMBER(19),
    AI_INPT_QA_EXEC_DT               VARCHAR2(8)    NOT NULL,
    AI_INPT_QA_INSP_DT               VARCHAR2(8),
    QLAS_CRPE_ENO                    VARCHAR2(64),
    QLAS_SNPE_ENO                    VARCHAR2(64),
    AI_INPT_TT_QA_RST_CD             VARCHAR2(32),
    AI_INPT_ITM_QA_RST_CD            VARCHAR2(32),
    AI_INPT_SW_QA_RST_CD             VARCHAR2(32),
    AI_INPT_QA_INTG_RST_CD           VARCHAR2(32)   DEFAULT 'ING' NOT NULL,
    AI_INPT_QA_MSG_TXT               CLOB,
    AI_INPT_QA_STCD                  VARCHAR2(32)   DEFAULT 'ING' NOT NULL,
    AI_INPT_QA_USG_YN                CHAR(1)        DEFAULT 'Y' NOT NULL,
    AI_INPT_ACT_CD                   VARCHAR2(32),
    AI_INPT_ACT_DTM                  VARCHAR2(20),
    AI_INPT_ACT_RMRK_TXT             VARCHAR2(1000),
    TRN_LOG_SRNO                     VARCHAR2(60),
    LST_DB_CHG_ID                    VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    CONSTRAINT PK_CSPD125TM PRIMARY KEY (AI_INPT_QA_SRNO),
    CONSTRAINT CK_CSPD125TM_01 CHECK (AI_INPT_QA_BIZ_GRP_CD IN ('EXP', 'WRK', 'SW')),
    CONSTRAINT CK_CSPD125TM_02 CHECK (AI_INPT_QA_SRC_CD IN ('SMPL', 'HNDG')),
    CONSTRAINT CK_CSPD125TM_03 CHECK (AI_INPT_QA_USG_YN IN ('Y', 'N')),
    CONSTRAINT CK_CSPD125TM_04 CHECK (AI_INPT_QA_STCD IN ('ING', 'DONE')),
    CONSTRAINT CK_CSPD125TM_05 CHECK (
        (AI_INPT_QA_BIZ_GRP_CD = 'SW' AND AI_INPT_SW_QA_SRNO IS NOT NULL AND INPT_MST_SRNO IS NULL)
     OR (AI_INPT_QA_BIZ_GRP_CD IN ('EXP', 'WRK') AND INPT_MST_SRNO IS NOT NULL AND AI_INPT_SW_QA_SRNO IS NULL)
    )
);

COMMENT ON TABLE  CSPD125TM IS 'QA 통합점검 마스터 — 수출입·워크·SafeWatch 1테이블';
COMMENT ON COLUMN CSPD125TM.AI_INPT_QA_SRNO IS 'QA 점검 일련번호';
COMMENT ON COLUMN CSPD125TM.AI_INPT_QA_BIZ_GRP_CD IS '업무구분 EXP/WRK/SW';
COMMENT ON COLUMN CSPD125TM.AI_INPT_QA_SRC_CD IS '출처 SMPL=샘플링 HNDG=수기등록';
COMMENT ON COLUMN CSPD125TM.AI_INPT_QA_TASK_NM IS '구분(업무명) 스냅샷';
COMMENT ON COLUMN CSPD125TM.AI_INPT_TASK_CD IS '업무코드 (119). 수출입·워크만';
COMMENT ON COLUMN CSPD125TM.INPT_MST_SRNO IS '심사건. 수출입·워크만';
COMMENT ON COLUMN CSPD125TM.AI_INPT_SW_QA_SRNO IS 'SafeWatch 수기대상. SW만';
COMMENT ON COLUMN CSPD125TM.AI_INPT_QA_EXEC_DT IS '실행일자';
COMMENT ON COLUMN CSPD125TM.AI_INPT_QA_INSP_DT IS '점검일자';
COMMENT ON COLUMN CSPD125TM.QLAS_CRPE_ENO IS 'QA1 점검자 직원번호';
COMMENT ON COLUMN CSPD125TM.QLAS_SNPE_ENO IS 'QA2 검토자 직원번호';
COMMENT ON COLUMN CSPD125TM.AI_INPT_TT_QA_RST_CD IS '문면점검결과';
COMMENT ON COLUMN CSPD125TM.AI_INPT_ITM_QA_RST_CD IS '항목점검결과';
COMMENT ON COLUMN CSPD125TM.AI_INPT_SW_QA_RST_CD IS 'SafeWatch점검결과';
COMMENT ON COLUMN CSPD125TM.AI_INPT_QA_INTG_RST_CD IS '통합점검결과 (서버 재계산)';
COMMENT ON COLUMN CSPD125TM.AI_INPT_QA_MSG_TXT IS '전달멘트(지적내용)';
COMMENT ON COLUMN CSPD125TM.AI_INPT_QA_STCD IS '진행상태 ING/DONE';
COMMENT ON COLUMN CSPD125TM.AI_INPT_ACT_CD IS '사후조치 코드 (협의 중, NULL 허용)';

CREATE INDEX IDX_CSPD125TM_01 ON CSPD125TM (AI_INPT_QA_BIZ_GRP_CD, AI_INPT_QA_EXEC_DT, AI_INPT_QA_USG_YN);
CREATE INDEX IDX_CSPD125TM_02 ON CSPD125TM (AI_INPT_QA_INTG_RST_CD, AI_INPT_QA_STCD);
CREATE INDEX IDX_CSPD125TM_03 ON CSPD125TM (INPT_MST_SRNO, AI_INPT_QA_EXEC_DT);
CREATE INDEX IDX_CSPD125TM_04 ON CSPD125TM (AI_INPT_SW_QA_SRNO);
CREATE INDEX IDX_CSPD125TM_05 ON CSPD125TM (QLAS_CRPE_ENO, AI_INPT_QA_STCD);
CREATE INDEX IDX_CSPD125TM_06 ON CSPD125TM (AI_INPT_TASK_CD, AI_INPT_QA_BIZ_GRP_CD);
CREATE INDEX IDX_CSPD125TM_07 ON CSPD125TM (AI_INPT_SW_QA_SRNO, AI_INPT_QA_EXEC_DT, AI_INPT_QA_USG_YN);

-- ------------------------------------------------------------
-- 3) CSPD129TH QA 점검·사후조치 이력
-- ------------------------------------------------------------
CREATE TABLE CSPD129TH (
    AI_INPT_QA_HST_SRNO              NUMBER(19)     NOT NULL,
    AI_INPT_QA_SRNO                  NUMBER(19)     NOT NULL,
    AI_INPT_QA_HST_TYP_CD            VARCHAR2(32)   NOT NULL,
    AI_INPT_TT_QA_RST_CD             VARCHAR2(32),
    AI_INPT_ITM_QA_RST_CD            VARCHAR2(32),
    AI_INPT_SW_QA_RST_CD             VARCHAR2(32),
    AI_INPT_QA_INTG_RST_CD           VARCHAR2(32),
    AI_INPT_ACT_CD                   VARCHAR2(32),
    AI_INPT_QA_MSG_TXT               CLOB,
    AI_INPT_CHG_USER_ENO             VARCHAR2(64)   NOT NULL,
    AI_INPT_CHG_DTM                  VARCHAR2(20)   NOT NULL,
    LST_DB_CHG_ID                    VARCHAR2(64),
    LST_DB_CHG_DTM                   VARCHAR2(20),
    CONSTRAINT PK_CSPD129TH PRIMARY KEY (AI_INPT_QA_HST_SRNO),
    CONSTRAINT CK_CSPD129TH_01 CHECK (AI_INPT_QA_HST_TYP_CD IN ('ADD', 'SAVE', 'ACT', 'DEL'))
);

COMMENT ON TABLE  CSPD129TH IS 'QA 점검·사후조치 이력';
COMMENT ON COLUMN CSPD129TH.AI_INPT_QA_HST_SRNO IS 'QA 이력 일련번호';
COMMENT ON COLUMN CSPD129TH.AI_INPT_QA_SRNO IS 'QA 점검 일련번호';
COMMENT ON COLUMN CSPD129TH.AI_INPT_QA_HST_TYP_CD IS '이력유형 ADD/SAVE/ACT/DEL';
COMMENT ON COLUMN CSPD129TH.AI_INPT_CHG_USER_ENO IS '처리자 직원번호';
COMMENT ON COLUMN CSPD129TH.AI_INPT_CHG_DTM IS '처리 일시';

CREATE INDEX IDX_CSPD129TH_01 ON CSPD129TH (AI_INPT_QA_SRNO, AI_INPT_CHG_DTM DESC);

-- ------------------------------------------------------------
-- 4) ALTER CSPD119TI — QA 탭 매핑
-- ------------------------------------------------------------
ALTER TABLE CSPD119TI ADD AI_INPT_QA_BIZ_GRP_CD VARCHAR2(32);
COMMENT ON COLUMN CSPD119TI.AI_INPT_QA_BIZ_GRP_CD IS 'QA 탭 EXP/WRK. NULL=샘플링 제외';

UPDATE CSPD119TI SET AI_INPT_QA_BIZ_GRP_CD = 'EXP' WHERE AI_INPT_TASK_GRP_CD = 'SHIP';
UPDATE CSPD119TI SET AI_INPT_QA_BIZ_GRP_CD = 'WRK' WHERE AI_INPT_TASK_GRP_CD IN ('BPR_NEW', 'BPR_SANC');

CREATE INDEX IDX_CSPD119TI_02 ON CSPD119TI (AI_INPT_QA_BIZ_GRP_CD, AI_INPT_TASK_USG_YN);

-- ------------------------------------------------------------
-- 5) ALTER CSPD107TI — 샘플 목표 (수출입 30 / 워크 20)
-- ------------------------------------------------------------
ALTER TABLE CSPD107TI ADD AI_INPT_QA_BIZ_GRP_CD VARCHAR2(32);
COMMENT ON COLUMN CSPD107TI.AI_INPT_QA_BIZ_GRP_CD IS 'QA 탭 EXP/WRK. SW 미사용';

UPDATE CSPD107TI
   SET AI_INPT_QA_BIZ_GRP_CD = 'EXP',
       QLAS_ITM_TOT_CNT = CASE AI_INPT_IMEX_DSCD
                            WHEN '01' THEN 15
                            WHEN '02' THEN 15
                            WHEN '1' THEN 15
                            WHEN '2' THEN 15
                            ELSE QLAS_ITM_TOT_CNT
                          END
 WHERE AI_INPT_IMEX_DSCD IN ('1', '2', '01', '02');

MERGE INTO CSPD107TI t
USING (SELECT '3' AS IMEX, 'WRK' AS LIST_ID FROM DUAL) s
   ON (t.AI_INPT_IMEX_DSCD = s.IMEX AND t.AI_INPT_LIST_ID = s.LIST_ID)
 WHEN NOT MATCHED THEN INSERT (
        AI_INPT_IMEX_DSCD, AI_INPT_LIST_ID, AI_INPT_QA_BIZ_GRP_CD,
        QLAS_ITM_TOT_CNT, QLAS_VOLN_CHC_CNT, QLAS_SLBS_VLD_YN,
        QLAS_SLT_RGS_DTM, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
        '3', 'WRK', 'WRK',
        20, 5, 'Y',
        '20260815120000', 'SYSTEM', '20260815120000'
 );

-- ------------------------------------------------------------
-- 6) 공통코드 140~145, 170 RELEASE/CLEAN
-- ------------------------------------------------------------
DELETE FROM CSPD112TI WHERE AI_INPT_GRP_CD IN ('140', '141', '142', '143', '144', '145');
DELETE FROM CSPD111TI WHERE AI_INPT_GRP_CD IN ('140', '141', '142', '143', '144', '145');

INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_STA_DTM, AI_INPT_GRP_END_DTM, AI_INPT_GRP_USG_YN, AI_INPT_RMRK_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('140', 'QA업무구분', '20200101000000', '99991231235959', 'Y', '3010-v2 탭', 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_STA_DTM, AI_INPT_GRP_END_DTM, AI_INPT_GRP_USG_YN, AI_INPT_RMRK_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('141', 'QA출처', '20200101000000', '99991231235959', 'Y', '샘플링/수기', 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_STA_DTM, AI_INPT_GRP_END_DTM, AI_INPT_GRP_USG_YN, AI_INPT_RMRK_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('142', 'QA점검결과', '20200101000000', '99991231235959', 'Y', '문면·항목·SW·통합', 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_STA_DTM, AI_INPT_GRP_END_DTM, AI_INPT_GRP_USG_YN, AI_INPT_RMRK_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('143', 'QA사후조치', '20200101000000', '99991231235959', 'Y', '협의중 트리거 미연결', 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_STA_DTM, AI_INPT_GRP_END_DTM, AI_INPT_GRP_USG_YN, AI_INPT_RMRK_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('144', 'QA이력유형', '20200101000000', '99991231235959', 'Y', '129TH', 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD111TI (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_STA_DTM, AI_INPT_GRP_END_DTM, AI_INPT_GRP_USG_YN, AI_INPT_RMRK_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('145', 'QA진행상태', '20200101000000', '99991231235959', 'Y', 'ING/DONE', 'QA125', 'SYSTEM', '20260815120000');

INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('140', 'EXP', '수출입', 'ExportImport', '20200101000000', '99991231235959', 'Y', '탭', '수출입', 1, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('140', 'WRK', '워크', 'Workflow', '20200101000000', '99991231235959', 'Y', '탭', '워크', 2, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('140', 'SW', 'SafeWatch', 'SafeWatch', '20200101000000', '99991231235959', 'Y', '수기등록', 'SafeWatch', 3, 'QA125', 'SYSTEM', '20260815120000');

INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('141', 'SMPL', '샘플링', 'Sampling', '20200101000000', '99991231235959', 'Y', '수출입·워크', '샘플링', 1, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('141', 'HNDG', '수기등록', 'Manual', '20200101000000', '99991231235959', 'Y', 'SafeWatch', '수기등록', 2, 'QA125', 'SYSTEM', '20260815120000');

INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('142', 'ING', '점검중(미완료)', 'InProgress', '20200101000000', '99991231235959', 'Y', '미입력 포함', '점검중', 0, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('142', 'PASS', '통과-이슈없음', 'Pass', '20200101000000', '99991231235959', 'Y', '서열1', '통과', 1, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('142', 'MINOR', '통과-일부개선필요', 'PassMinor', '20200101000000', '99991231235959', 'Y', '서열2', '일부개선', 2, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('142', 'FAIL_PROC', '미통과-절차상 오류', 'FailProcedure', '20200101000000', '99991231235959', 'Y', '서열3 재필터링 권고', '절차오류', 3, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('142', 'FAIL_LEGAL', '미통과-잠재적 법적 우려사항', 'FailLegal', '20200101000000', '99991231235959', 'Y', '서열4 준법보고 권고', '법적우려', 4, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('142', 'NA', '해당사항없음', 'NotApplicable', '20200101000000', '99991231235959', 'Y', '서열계산 무시', '해당없음', 9, 'QA125', 'SYSTEM', '20260815120000');

INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('143', 'NONE', '조치없음', 'None', '20200101000000', '99991231235959', 'Y', '통과', '없음', 1, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('143', 'REFILTER', '필터링 재시행', 'Refilter', '20200101000000', '99991231235959', 'Y', '절차상오류 권고', '재필터', 2, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('143', 'COMPL_RPT', '준법지원부 보고', 'ComplianceReport', '20200101000000', '99991231235959', 'Y', '법적우려 권고', '준법보고', 3, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('143', 'EDUC', '직원 교육', 'Education', '20200101000000', '99991231235959', 'Y', '법적우려 부가', '교육', 4, 'QA125', 'SYSTEM', '20260815120000');

INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('144', 'ADD', '등록', 'Add', '20200101000000', '99991231235959', 'Y', NULL, '등록', 1, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('144', 'SAVE', '점검저장', 'Save', '20200101000000', '99991231235959', 'Y', NULL, '저장', 2, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('144', 'ACT', '사후조치', 'Action', '20200101000000', '99991231235959', 'Y', '협의중', '조치', 3, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('144', 'DEL', '논리삭제', 'Delete', '20200101000000', '99991231235959', 'Y', NULL, '삭제', 4, 'QA125', 'SYSTEM', '20260815120000');

INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('145', 'ING', '점검중(미완료)', 'InProgress', '20200101000000', '99991231235959', 'Y', NULL, '점검중', 1, 'QA125', 'SYSTEM', '20260815120000');
INSERT INTO CSPD112TI (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
VALUES ('145', 'DONE', '점검완료', 'Done', '20200101000000', '99991231235959', 'Y', NULL, '완료', 2, 'QA125', 'SYSTEM', '20260815120000');

MERGE INTO CSPD112TI t
USING (SELECT '170' AS GRP, 'RELEASE' AS CD FROM DUAL) s
   ON (t.AI_INPT_GRP_CD = s.GRP AND t.AI_INPT_CMN_CD = s.CD)
 WHEN NOT MATCHED THEN INSERT (
    AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM,
    AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT,
    AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
    '170', 'RELEASE', 'Release', 'Release',
    '20200101000000', '99991231235959', 'Y', '3010-v2',
    'Release', 10, 'QA125', 'SYSTEM', '20260815120000'
 );
MERGE INTO CSPD112TI t
USING (SELECT '170' AS GRP, 'CLEAN' AS CD FROM DUAL) s
   ON (t.AI_INPT_GRP_CD = s.GRP AND t.AI_INPT_CMN_CD = s.CD)
 WHEN NOT MATCHED THEN INSERT (
    AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM,
    AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT,
    AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
    '170', 'CLEAN', 'Clean', 'Clean',
    '20200101000000', '99991231235959', 'Y', '3010-v2',
    'Clean', 11, 'QA125', 'SYSTEM', '20260815120000'
 );

-- ------------------------------------------------------------
-- 7) QA2 계정 · QA1 SafeWatch 권한 · C1/C2 표시용 사용자
-- ------------------------------------------------------------
UPDATE CSPD108TI
   SET AI_INPT_MENU_NM = '통합 QA',
       LST_DB_CHG_ID = 'SYSTEM',
       LST_DB_CHG_DTM = '20260815120000'
 WHERE AI_INPT_MENU_ID = '301100';

MERGE INTO CSPD101TI t
USING (SELECT 'qauser02' AS USER_ID FROM DUAL) s
   ON (t.AI_INPT_USER_ID = s.USER_ID)
 WHEN NOT MATCHED THEN INSERT (
    AI_INPT_USER_ID, AI_INPT_USER_ENO, AI_INPT_AUT_CD, AI_INPT_MGPE_YN, AI_INPT_USER_NM,
    AI_INPT_USER_YN, AI_INPT_USER_FA_RE_YN, AI_INPT_USER_RGS_DTM, AI_INPT_USER_END_DTM,
    AI_INPT_SRVC_USER_DSCD, AI_INPT_USER_TYP_CD, AI_INPT_BRCD,
    TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
    'qauser02', 'E10007', '03', 'N', '한QA',
    'Y', 'N', '20200101000000', '99991231235959',
    '01', 'QA', '0203',
    '7', 'SYSTEM', '20260815120000'
 );

MERGE INTO CSPD124TI t
USING (SELECT 'E10003' AS ENO FROM DUAL) s
   ON (t.AI_INPT_USER_ENO = s.ENO)
 WHEN MATCHED THEN UPDATE SET
       AI_INPT_QA1_YN = 'Y',
       AI_INPT_QA_EXP_YN = 'Y',
       AI_INPT_QA_WRK_YN = 'Y',
       AI_INPT_QA_SW_YN = 'Y',
       AI_INPT_DFLT_QA2_ENO = 'E10007'
 WHEN NOT MATCHED THEN INSERT (
       AI_INPT_USER_ENO, AI_INPT_QA1_YN, AI_INPT_QA2_YN, AI_INPT_DFLT_QA2_ENO,
       AI_INPT_QA_EXP_YN, AI_INPT_QA_WRK_YN, AI_INPT_QA_SW_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
       'E10003', 'Y', 'N', 'E10007', 'Y', 'Y', 'Y', 'SYSTEM', '20260815120000'
 );

MERGE INTO CSPD124TI t
USING (SELECT 'E10007' AS ENO FROM DUAL) s
   ON (t.AI_INPT_USER_ENO = s.ENO)
 WHEN NOT MATCHED THEN INSERT (
       AI_INPT_USER_ENO, AI_INPT_QA1_YN, AI_INPT_QA2_YN, AI_INPT_DFLT_QA2_ENO,
       AI_INPT_QA_EXP_YN, AI_INPT_QA_WRK_YN, AI_INPT_QA_SW_YN, LST_DB_CHG_ID, LST_DB_CHG_DTM
 ) VALUES (
       'E10007', 'N', 'Y', NULL, 'Y', 'Y', 'Y', 'SYSTEM', '20260815120000'
 );

INSERT INTO CSPD101TI (
    AI_INPT_USER_ID, AI_INPT_USER_ENO, AI_INPT_AUT_CD, AI_INPT_MGPE_YN, AI_INPT_USER_NM,
    AI_INPT_USER_YN, AI_INPT_USER_FA_RE_YN, AI_INPT_USER_RGS_DTM, AI_INPT_USER_END_DTM,
    AI_INPT_SRVC_USER_DSCD, AI_INPT_USER_TYP_CD, AI_INPT_BRCD,
    TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
)
SELECT s.USER_ID, s.ENO, '01', 'N', s.NM,
       'Y', 'N', '20200101000000', '99991231235959',
       '01', 'RVW', '0203',
       s.ENO, 'SYSTEM', '20260815120000'
  FROM (
        SELECT 'c1_choi' AS USER_ID, 'E20101' AS ENO, '최OO' AS NM FROM DUAL UNION ALL
        SELECT 'c2_cho',  'E20102', '조OO' FROM DUAL UNION ALL
        SELECT 'c1_park', 'E20103', '박OO' FROM DUAL UNION ALL
        SELECT 'c2_lee',  'E20104', '이OO' FROM DUAL UNION ALL
        SELECT 'c1_kim',  'E20105', '김OO' FROM DUAL UNION ALL
        SELECT 'c1_lim',  'E20106', '임OO' FROM DUAL
       ) s
 WHERE NOT EXISTS (SELECT 1 FROM CSPD101TI u WHERE u.AI_INPT_USER_ID = s.USER_ID);

-- ------------------------------------------------------------
-- 8) 목업 시드 (list-3010-v2.html 5행)
-- ------------------------------------------------------------
INSERT INTO CSPD201TM (
    XPO_CVRG_MK_SQ, FX_ACNO, CSNO, CUS_KORL_NM, CUS_ENG_NM,
    XPBY_COL_AM, XPBY_COL_CTR_CUCD, INPT_ATMC_REQ_DSCD, XPO_CVRG_MTBR_MK_DT,
    TRN_OPR_NO, INPT_ATMC_BIZ_DSCD, KRBR_NM, DACC_BRCD, XPO_PTN_NACD, HS_CD
) VALUES (31001, 'WTA6432600S983', '0234567', '(주)OO상사', 'OO TRADING',
    4795.00, 'USD', '1', '20260806', 'E20101', '1', '마곡기업영업지원팀', '0203', 'US', '847130');
INSERT INTO CSPD201TM (
    XPO_CVRG_MK_SQ, FX_ACNO, CSNO, CUS_KORL_NM, CUS_ENG_NM,
    XPBY_COL_AM, XPBY_COL_CTR_CUCD, INPT_ATMC_REQ_DSCD, XPO_CVRG_MTBR_MK_DT,
    TRN_OPR_NO, INPT_ATMC_BIZ_DSCD, KRBR_NM, DACC_BRCD, XPO_PTN_NACD, HS_CD
) VALUES (31002, 'FDT8912600O852', '0298765', '한국OO(주)', 'KOREA OO',
    270000.00, 'CNY', '1', '20260806', 'E20103', '1', '역전기업영업지원팀', '0203', 'CN', '870323');
INSERT INTO CSPD201TM (
    XPO_CVRG_MK_SQ, FX_ACNO, CSNO, CUS_KORL_NM, CUS_ENG_NM,
    XPBY_COL_AM, XPBY_COL_CTR_CUCD, INPT_ATMC_REQ_DSCD, XPO_CVRG_MTBR_MK_DT,
    TRN_OPR_NO, INPT_ATMC_BIZ_DSCD, KRBR_NM, DACC_BRCD, XPO_PTN_NACD, HS_CD
) VALUES (31003, 'FTA2742600Z895', '0345678', '(주)△△무역', 'TRIANGLE TRADE',
    2900.00, 'USD', '1', '20260806', 'E20105', '1', '여의기업영업지원팀', '0203', 'AE', '847130');
INSERT INTO CSPD201TM (
    XPO_CVRG_MK_SQ, FX_ACNO, CSNO, CUS_KORL_NM, CUS_ENG_NM,
    XPBY_COL_AM, XPBY_COL_CTR_CUCD, INPT_ATMC_REQ_DSCD, XPO_CVRG_MTBR_MK_DT,
    TRN_OPR_NO, INPT_ATMC_BIZ_DSCD, KRBR_NM, DACC_BRCD, XPO_PTN_NACD, HS_CD
) VALUES (31004, 'WCT5562601A221', '0387654', '배OO', 'BAE OO',
    473322.97, 'USD', '1', '20260806', 'E20106', '1', '양재중앙지점', '1877', 'US', '847130');

INSERT INTO CSPD001TM (
    INPT_MST_SRNO, AI_INSPE_ENO, AI_INPT_SNPE_ENO, INPT_ATMC_BIZ_DSCD, INPT_ATMC_REQ_DSCD,
    AI_INPT_PROS_CD, AI_INPT_ACVT_CD, AI_INPT_APPV_STCD, IMEX_HIS_CD,
    TOTALTEXT_AI_INPT_RST_CD, ITM_INPT_AI_INPT_RST_CD, SAFEWATCH_AI_INPT_RST_CD, QLT_GRN_AI_INPT_RST_CD,
    INPT_BL_GRP_NO, INPT_RCP_DT, INPT_RCP_YM, INPT_SANCTION_NM, INPT_TASK_ID, INPT_ELMT_ID,
    ACTL_FX_REFNO, FX_REFNO_SRNO, AI_INPT_BUY_AM, ALERT_YN, QLAS_PRG_YN,
    AI_INPT_QLAS_ACVT_CD, AI_INPT_QLAS_APPV_STCD, AI_INPT_QLAS_PROS_CD, QLAS_ALOC_DT,
    QLAS_CRPE_ENO, QLAS_SNPE_ENO, REPROC_CNT, RESCAN_CNT,
    PAPS_CLF_ERR_YN, PAPS_RE_SCAN_NED_YN, PAPS_RE_SCAN_CMPL_YN,
    AI_INPT_TASK_CD, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    31001, 'E20101', 'E20102', 'SHIP_EXP', '1',
    '01', '160', '160', '01',
    'RELEASE', 'CLEAN', 'RELEASE', '01',
    '1', '20260806', '202608', '수출환어음매입', '31001', 'ELMT31001',
    'WTA6432600S983', 1, 4795.00, 'N', 'Y',
    '110', '01', '01', '20260807',
    'E10003', 'E10007', 0, 0,
    'N', 'N', 'N',
    'BPRS_EXP_BILL', '31001', 'SYSTEM', '20260807100000'
);
INSERT INTO CSPD001TM (
    INPT_MST_SRNO, AI_INSPE_ENO, AI_INPT_SNPE_ENO, INPT_ATMC_BIZ_DSCD, INPT_ATMC_REQ_DSCD,
    AI_INPT_PROS_CD, AI_INPT_ACVT_CD, AI_INPT_APPV_STCD, IMEX_HIS_CD,
    TOTALTEXT_AI_INPT_RST_CD, ITM_INPT_AI_INPT_RST_CD, SAFEWATCH_AI_INPT_RST_CD, QLT_GRN_AI_INPT_RST_CD,
    INPT_BL_GRP_NO, INPT_RCP_DT, INPT_RCP_YM, INPT_SANCTION_NM, INPT_TASK_ID, INPT_ELMT_ID,
    ACTL_FX_REFNO, FX_REFNO_SRNO, AI_INPT_BUY_AM, ALERT_YN, QLAS_PRG_YN,
    AI_INPT_QLAS_ACVT_CD, AI_INPT_QLAS_APPV_STCD, AI_INPT_QLAS_PROS_CD, QLAS_ALOC_DT,
    QLAS_CRPE_ENO, QLAS_SNPE_ENO, REPROC_CNT, RESCAN_CNT,
    PAPS_CLF_ERR_YN, PAPS_RE_SCAN_NED_YN, PAPS_RE_SCAN_CMPL_YN,
    AI_INPT_TASK_CD, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    31002, 'E20103', 'E20104', 'BPRS_FX_REQ', '1',
    '01', '160', '160', '01',
    'RELEASE', 'CLEAN', 'RELEASE', '01',
    '1', '20260806', '202608', '고위험당발-외환업무요청', '31002', 'ELMT31002',
    'FDT8912600O852', 1, 270000.00, 'N', 'Y',
    '110', '01', '01', '20260807',
    'E10003', 'E10007', 0, 0,
    'N', 'N', 'N',
    'BPRS_FX_REQ', '31002', 'SYSTEM', '20260807100000'
);
INSERT INTO CSPD001TM (
    INPT_MST_SRNO, AI_INSPE_ENO, AI_INPT_SNPE_ENO, INPT_ATMC_BIZ_DSCD, INPT_ATMC_REQ_DSCD,
    AI_INPT_PROS_CD, AI_INPT_ACVT_CD, AI_INPT_APPV_STCD, IMEX_HIS_CD,
    TOTALTEXT_AI_INPT_RST_CD, ITM_INPT_AI_INPT_RST_CD, SAFEWATCH_AI_INPT_RST_CD, QLT_GRN_AI_INPT_RST_CD,
    INPT_BL_GRP_NO, INPT_RCP_DT, INPT_RCP_YM, INPT_SANCTION_NM, INPT_TASK_ID, INPT_ELMT_ID,
    ACTL_FX_REFNO, FX_REFNO_SRNO, AI_INPT_BUY_AM, ALERT_YN, QLAS_PRG_YN,
    AI_INPT_QLAS_ACVT_CD, AI_INPT_QLAS_APPV_STCD, AI_INPT_QLAS_PROS_CD, QLAS_ALOC_DT,
    QLAS_CRPE_ENO, QLAS_SNPE_ENO, REPROC_CNT, RESCAN_CNT,
    PAPS_CLF_ERR_YN, PAPS_RE_SCAN_NED_YN, PAPS_RE_SCAN_CMPL_YN,
    AI_INPT_TASK_CD, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    31003, 'E20105', 'E20103', 'BPRN_IRAN_BYPASS', '1',
    '01', '160', '160', '01',
    'RELEASE', 'CLEAN', 'RELEASE', '01',
    '1', '20260806', '202608', '이란 등 우회주의국가 타발지급-외환업무요청', '31003', 'ELMT31003',
    'FTA2742600Z895', NULL, 2900.00, 'N', 'Y',
    '110', '01', '01', '20260807',
    'E10003', 'E10007', 0, 0,
    'N', 'N', 'N',
    'BPRN_IRAN_BYPASS', '31003', 'SYSTEM', '20260807100000'
);
INSERT INTO CSPD001TM (
    INPT_MST_SRNO, AI_INSPE_ENO, AI_INPT_SNPE_ENO, INPT_ATMC_BIZ_DSCD, INPT_ATMC_REQ_DSCD,
    AI_INPT_PROS_CD, AI_INPT_ACVT_CD, AI_INPT_APPV_STCD, IMEX_HIS_CD,
    TOTALTEXT_AI_INPT_RST_CD, ITM_INPT_AI_INPT_RST_CD, SAFEWATCH_AI_INPT_RST_CD, QLT_GRN_AI_INPT_RST_CD,
    INPT_BL_GRP_NO, INPT_RCP_DT, INPT_RCP_YM, INPT_SANCTION_NM, INPT_TASK_ID, INPT_ELMT_ID,
    ACTL_FX_REFNO, FX_REFNO_SRNO, AI_INPT_BUY_AM, ALERT_YN, QLAS_PRG_YN,
    AI_INPT_QLAS_ACVT_CD, AI_INPT_QLAS_APPV_STCD, AI_INPT_QLAS_PROS_CD, QLAS_ALOC_DT,
    QLAS_CRPE_ENO, QLAS_SNPE_ENO, REPROC_CNT, RESCAN_CNT,
    PAPS_CLF_ERR_YN, PAPS_RE_SCAN_NED_YN, PAPS_RE_SCAN_CMPL_YN,
    AI_INPT_TASK_CD, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    31004, 'E20106', 'E20103', 'BPRS_REMIT', '1',
    '01', '160', '160', '01',
    'RELEASE', 'CLEAN', 'RELEASE', '01',
    '1', '20260806', '202608', 'T.T-당발송금(하와이/KEB/송금수표)', '31004', 'ELMT31004',
    'WCT5562601A221', NULL, 473322.97, 'N', 'Y',
    '110', '01', '01', '20260807',
    'E10003', 'E10007', 0, 0,
    'N', 'N', 'N',
    'BPRS_REMIT', '31004', 'SYSTEM', '20260807100000'
);

INSERT INTO CSPD004TF (
    INPT_MST_SRNO, INPT_SANCTION_NO, INPT_TASK_ID, INPT_BL_GRP_NO, INPT_ATMC_BIZ_DSCD,
    AI_INPT_BUY_AM, AI_INPT_ALT_YN, SAFEWATCH_ITM_YN, ITM_INPT_NACRD_YN, ITM_INPT_RVSN_YN,
    BFRS_AICR_EXTC_TXT, AFRS_AICR_EXTC_TXT, INPT_SANCTION_DAT_TXT, ITM_INPT_HNDG_INP_DAT_TXT,
    AI_INPT_SANCTION_RULE_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    31001, 1, '31001', '1', 'SHIP_EXP',
    4795.00, 'N', 'N', 'N', 'N',
    'REF-20240029', 'REF-20240029', 'Bill of lading No.', NULL,
    'MATCH', '3100101', 'SYSTEM', '20260807100000'
);
INSERT INTO CSPD004TF (
    INPT_MST_SRNO, INPT_SANCTION_NO, INPT_TASK_ID, INPT_BL_GRP_NO, INPT_ATMC_BIZ_DSCD,
    AI_INPT_BUY_AM, AI_INPT_ALT_YN, SAFEWATCH_ITM_YN, ITM_INPT_NACRD_YN, ITM_INPT_RVSN_YN,
    BFRS_AICR_EXTC_TXT, AFRS_AICR_EXTC_TXT, INPT_SANCTION_DAT_TXT, ITM_INPT_HNDG_INP_DAT_TXT,
    AI_INPT_SANCTION_RULE_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    31001, 2, '31001', '1', 'SHIP_EXP',
    4795.00, 'N', 'N', 'N', 'N',
    'Samsung Electronics', 'Samsung Electronics', 'Vessel Name', NULL,
    'MATCH', '3100102', 'SYSTEM', '20260807100000'
);
INSERT INTO CSPD004TF (
    INPT_MST_SRNO, INPT_SANCTION_NO, INPT_TASK_ID, INPT_BL_GRP_NO, INPT_ATMC_BIZ_DSCD,
    AI_INPT_BUY_AM, AI_INPT_ALT_YN, SAFEWATCH_ITM_YN, ITM_INPT_NACRD_YN, ITM_INPT_RVSN_YN,
    BFRS_AICR_EXTC_TXT, AFRS_AICR_EXTC_TXT, INPT_SANCTION_DAT_TXT, ITM_INPT_HNDG_INP_DAT_TXT,
    AI_INPT_SANCTION_RULE_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    31001, 3, '31001', '1', 'SHIP_EXP',
    4795.00, 'Y', 'N', 'N', 'Y',
    'KOREA (Alert)', 'KOREA', 'Country of ''Place of Receipt''', 'KOREA',
    'ALERT', '3100103', 'SYSTEM', '20260807100000'
);

INSERT INTO CSPD003TF (
    INPT_MST_SRNO, AI_INPT_TOTALTEXT_SRNO, INPT_TASK_ID, BFRS_AICR_EXTC_TXT,
    INPT_SANCTION_DAT_TXT, AI_INPT_SANCTION_RULE_TXT, AI_INPT_TOTALTEXT_RVSN_YN, AI_INPT_ALT_YN,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    31001, 1, '31001', 'B/L REF-20240029 / Samsung Electronics / Place of Receipt KOREA',
    'Total Text sample', 'RULE_OK', 'N', 'N',
    'SYSTEM', '20260807100000'
);

INSERT INTO CSPD128TI (
    AI_INPT_SW_QA_SRNO, AI_INPT_SW_REFNO, FILT_DTCT_NO, INPT_MST_SRNO,
    AI_INPT_CUST_NO, AI_INPT_CUST_NM, AI_INPT_SW_ORIG_RST_CD,
    AI_INPT_SW_USG_YN, AI_INPT_RGS_ENO, AI_INPT_RGS_DTM,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    1, 'SW-88117', NULL, NULL,
    '0456789', 'XX CO', 'RELEASE',
    'Y', 'E10003', '20260807100000',
    'E10003', '20260807100000'
);

INSERT INTO CSPD125TM (
    AI_INPT_QA_SRNO, AI_INPT_QA_BIZ_GRP_CD, AI_INPT_QA_SRC_CD,
    AI_INPT_QA_TASK_NM, AI_INPT_TASK_CD, INPT_MST_SRNO, AI_INPT_SW_QA_SRNO,
    AI_INPT_QA_EXEC_DT, AI_INPT_QA_INSP_DT,
    QLAS_CRPE_ENO, QLAS_SNPE_ENO,
    AI_INPT_TT_QA_RST_CD, AI_INPT_ITM_QA_RST_CD, AI_INPT_SW_QA_RST_CD,
    AI_INPT_QA_INTG_RST_CD, AI_INPT_QA_STCD, AI_INPT_QA_USG_YN,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    1, 'EXP', 'SMPL',
    '수출환어음매입', 'BPRS_EXP_BILL', 31001, NULL,
    '20260807', '20260810',
    'E10003', 'E10007',
    NULL, NULL, NULL,
    'ING', 'ING', 'Y',
    'E10003', '20260810100000'
);
INSERT INTO CSPD125TM (
    AI_INPT_QA_SRNO, AI_INPT_QA_BIZ_GRP_CD, AI_INPT_QA_SRC_CD,
    AI_INPT_QA_TASK_NM, AI_INPT_TASK_CD, INPT_MST_SRNO, AI_INPT_SW_QA_SRNO,
    AI_INPT_QA_EXEC_DT, AI_INPT_QA_INSP_DT,
    QLAS_CRPE_ENO, QLAS_SNPE_ENO,
    AI_INPT_TT_QA_RST_CD, AI_INPT_ITM_QA_RST_CD, AI_INPT_SW_QA_RST_CD,
    AI_INPT_QA_INTG_RST_CD, AI_INPT_QA_STCD, AI_INPT_QA_USG_YN,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    2, 'EXP', 'SMPL',
    '고위험당발-외환업무요청', 'BPRS_FX_REQ', 31002, NULL,
    '20260807', '20260810',
    'E10003', 'E10007',
    NULL, NULL, NULL,
    'ING', 'ING', 'Y',
    'E10003', '20260810100000'
);
INSERT INTO CSPD125TM (
    AI_INPT_QA_SRNO, AI_INPT_QA_BIZ_GRP_CD, AI_INPT_QA_SRC_CD,
    AI_INPT_QA_TASK_NM, AI_INPT_TASK_CD, INPT_MST_SRNO, AI_INPT_SW_QA_SRNO,
    AI_INPT_QA_EXEC_DT, AI_INPT_QA_INSP_DT,
    QLAS_CRPE_ENO, QLAS_SNPE_ENO,
    AI_INPT_TT_QA_RST_CD, AI_INPT_ITM_QA_RST_CD, AI_INPT_SW_QA_RST_CD,
    AI_INPT_QA_INTG_RST_CD, AI_INPT_QA_STCD, AI_INPT_QA_USG_YN,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    3, 'WRK', 'SMPL',
    '이란 등 우회주의국가 타발지급-외환업무요청', 'BPRN_IRAN_BYPASS', 31003, NULL,
    '20260807', '20260810',
    'E10003', 'E10007',
    NULL, NULL, NULL,
    'ING', 'ING', 'Y',
    'E10003', '20260810100000'
);
INSERT INTO CSPD125TM (
    AI_INPT_QA_SRNO, AI_INPT_QA_BIZ_GRP_CD, AI_INPT_QA_SRC_CD,
    AI_INPT_QA_TASK_NM, AI_INPT_TASK_CD, INPT_MST_SRNO, AI_INPT_SW_QA_SRNO,
    AI_INPT_QA_EXEC_DT, AI_INPT_QA_INSP_DT,
    QLAS_CRPE_ENO, QLAS_SNPE_ENO,
    AI_INPT_TT_QA_RST_CD, AI_INPT_ITM_QA_RST_CD, AI_INPT_SW_QA_RST_CD,
    AI_INPT_QA_INTG_RST_CD, AI_INPT_QA_STCD, AI_INPT_QA_USG_YN,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    4, 'WRK', 'SMPL',
    'T.T-당발송금(하와이/KEB/송금수표)', 'BPRS_REMIT', 31004, NULL,
    '20260807', '20260810',
    'E10003', 'E10007',
    NULL, NULL, NULL,
    'ING', 'ING', 'Y',
    'E10003', '20260810100000'
);
INSERT INTO CSPD125TM (
    AI_INPT_QA_SRNO, AI_INPT_QA_BIZ_GRP_CD, AI_INPT_QA_SRC_CD,
    AI_INPT_QA_TASK_NM, AI_INPT_TASK_CD, INPT_MST_SRNO, AI_INPT_SW_QA_SRNO,
    AI_INPT_QA_EXEC_DT, AI_INPT_QA_INSP_DT,
    QLAS_CRPE_ENO, QLAS_SNPE_ENO,
    AI_INPT_TT_QA_RST_CD, AI_INPT_ITM_QA_RST_CD, AI_INPT_SW_QA_RST_CD,
    AI_INPT_QA_INTG_RST_CD, AI_INPT_QA_STCD, AI_INPT_QA_USG_YN,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (
    5, 'SW', 'HNDG',
    'QA-SafeWatch (수기등록)', NULL, NULL, 1,
    '20260807', '20260810',
    'E10003', 'E10007',
    'NA', 'NA', NULL,
    'ING', 'ING', 'Y',
    'E10003', '20260810100000'
);

INSERT INTO CSPD129TH (
    AI_INPT_QA_HST_SRNO, AI_INPT_QA_SRNO, AI_INPT_QA_HST_TYP_CD,
    AI_INPT_TT_QA_RST_CD, AI_INPT_ITM_QA_RST_CD, AI_INPT_SW_QA_RST_CD,
    AI_INPT_QA_INTG_RST_CD, AI_INPT_CHG_USER_ENO, AI_INPT_CHG_DTM,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (1, 1, 'ADD', NULL, NULL, NULL, 'ING', 'E10003', '20260807100000', 'E10003', '20260807100000');
INSERT INTO CSPD129TH (
    AI_INPT_QA_HST_SRNO, AI_INPT_QA_SRNO, AI_INPT_QA_HST_TYP_CD,
    AI_INPT_TT_QA_RST_CD, AI_INPT_ITM_QA_RST_CD, AI_INPT_SW_QA_RST_CD,
    AI_INPT_QA_INTG_RST_CD, AI_INPT_CHG_USER_ENO, AI_INPT_CHG_DTM,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (2, 2, 'ADD', NULL, NULL, NULL, 'ING', 'E10003', '20260807100000', 'E10003', '20260807100000');
INSERT INTO CSPD129TH (
    AI_INPT_QA_HST_SRNO, AI_INPT_QA_SRNO, AI_INPT_QA_HST_TYP_CD,
    AI_INPT_TT_QA_RST_CD, AI_INPT_ITM_QA_RST_CD, AI_INPT_SW_QA_RST_CD,
    AI_INPT_QA_INTG_RST_CD, AI_INPT_CHG_USER_ENO, AI_INPT_CHG_DTM,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (3, 3, 'ADD', NULL, NULL, NULL, 'ING', 'E10003', '20260807100000', 'E10003', '20260807100000');
INSERT INTO CSPD129TH (
    AI_INPT_QA_HST_SRNO, AI_INPT_QA_SRNO, AI_INPT_QA_HST_TYP_CD,
    AI_INPT_TT_QA_RST_CD, AI_INPT_ITM_QA_RST_CD, AI_INPT_SW_QA_RST_CD,
    AI_INPT_QA_INTG_RST_CD, AI_INPT_CHG_USER_ENO, AI_INPT_CHG_DTM,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (4, 4, 'ADD', NULL, NULL, NULL, 'ING', 'E10003', '20260807100000', 'E10003', '20260807100000');
INSERT INTO CSPD129TH (
    AI_INPT_QA_HST_SRNO, AI_INPT_QA_SRNO, AI_INPT_QA_HST_TYP_CD,
    AI_INPT_TT_QA_RST_CD, AI_INPT_ITM_QA_RST_CD, AI_INPT_SW_QA_RST_CD,
    AI_INPT_QA_INTG_RST_CD, AI_INPT_CHG_USER_ENO, AI_INPT_CHG_DTM,
    LST_DB_CHG_ID, LST_DB_CHG_DTM
) VALUES (5, 5, 'ADD', 'NA', 'NA', NULL, 'ING', 'E10003', '20260807100000', 'E10003', '20260807100000');

COMMIT;
