-- ============================================================
-- SCR-1011 항목심사 수기 행추가 — CSPD004TF PK 확장
-- Tibero / Oracle
-- 실행: 28_annotation.sql 이후, 07_menu_role_test_data 이전
--       신규 설치는 01_ddl.sql 에 이미 반영됨. 본 파일은 기존 DB ALTER.
-- 문서: docs/항목심사_추가검출_복수값_테이블_설계_가이드.md
-- ITM_INPT_VAL_SEQ 기본값: 0 (원본 행), 수기 추가 행은 1부터
-- ============================================================

ALTER TABLE CSPD004TF ADD (
    ITM_INPT_VAL_SEQ      NUMBER(5)     DEFAULT 0,
    ITM_INPT_SRC_DSCD     VARCHAR2(32)  DEFAULT 'AI',
    ITM_INPT_ADD_ROW_YN   CHAR(1)       DEFAULT 'N'
);

UPDATE CSPD004TF SET ITM_INPT_VAL_SEQ = 0 WHERE ITM_INPT_VAL_SEQ IS NULL;
UPDATE CSPD004TF SET ITM_INPT_SRC_DSCD = 'AI' WHERE ITM_INPT_SRC_DSCD IS NULL;
UPDATE CSPD004TF SET ITM_INPT_ADD_ROW_YN = 'N' WHERE ITM_INPT_ADD_ROW_YN IS NULL;

ALTER TABLE CSPD004TF MODIFY ITM_INPT_VAL_SEQ DEFAULT 0;
ALTER TABLE CSPD004TF MODIFY ITM_INPT_VAL_SEQ NOT NULL;
ALTER TABLE CSPD004TF MODIFY ITM_INPT_SRC_DSCD DEFAULT 'AI';
ALTER TABLE CSPD004TF MODIFY ITM_INPT_SRC_DSCD NOT NULL;
ALTER TABLE CSPD004TF MODIFY ITM_INPT_ADD_ROW_YN DEFAULT 'N';
ALTER TABLE CSPD004TF MODIFY ITM_INPT_ADD_ROW_YN NOT NULL;

ALTER TABLE CSPD004TF DROP CONSTRAINT PK_CSPD004TF;
ALTER TABLE CSPD004TF ADD CONSTRAINT PK_CSPD004TF PRIMARY KEY (INPT_MST_SRNO, INPT_SANCTION_NO, ITM_INPT_VAL_SEQ);

COMMENT ON COLUMN CSPD004TF.ITM_INPT_VAL_SEQ IS '항목값순번 (동일 항목 복수행, 기본 0)';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_SRC_DSCD IS '값출처 AI/HNDG/SYS';
COMMENT ON COLUMN CSPD004TF.ITM_INPT_ADD_ROW_YN IS '화면 수기 행추가 여부';

COMMIT;

-- ------------------------------------------------------------
-- 아래 UPDATE 는 '원본 행'만 대상이다. 수기 추가 행(1,2,3...)에는 실행하지 말 것.
-- 이미 DEFAULT 1 로 원본이 들어간 DB에서, ADD_ROW_YN='N' 이고 VAL_SEQ=1 인 원본만 0 으로 맞춘다.
-- 수기 추가 행은 VAL_SEQ=1 부터 증가해야 하므로 이 UPDATE 대상이 아니다.
-- ALTER TABLE CSPD004TF MODIFY ITM_INPT_VAL_SEQ DEFAULT 0;
-- UPDATE CSPD004TF SET ITM_INPT_VAL_SEQ = 0
--  WHERE ITM_INPT_VAL_SEQ = 1
--    AND NVL(ITM_INPT_ADD_ROW_YN, 'N') = 'N';
-- COMMIT;
