-- ============================================================
-- 31_dashboard_display_config.sql
-- 대시보드(DASH-v2) 목록 표시 설정 — 공통코드 그룹 372
-- 관리자 > 공통코드(802200)에서 수정
-- 운영 일괄 MIG: sql/32_urgent_review_mig.sql (371+372)
-- 상세: docs/to-be/긴급심사_TO-BE_데이터_마이그레이션.md
-- ============================================================
MERGE INTO CSPD111TI T
USING (
  SELECT '372' AS GRP_CD, '대시보드표시설정' AS GRP_NM, 'DASH-v2 목록 표시' AS RMRK FROM DUAL
) S
ON (T.AI_INPT_GRP_CD = S.GRP_CD)
WHEN NOT MATCHED THEN
  INSERT (AI_INPT_GRP_CD, AI_INPT_GRP_NM, AI_INPT_GRP_STA_DTM, AI_INPT_GRP_END_DTM, AI_INPT_GRP_USG_YN, AI_INPT_RMRK_TXT, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
  VALUES (S.GRP_CD, S.GRP_NM, '20200101000000', '99991231235959', 'Y', S.RMRK, '43', 'SYSTEM', '20260817160000');

MERGE INTO CSPD112TI T
USING (
  SELECT '372' AS GRP_CD, '01' AS CMN_CD, '20' AS CMN_NM, 'MaxCount' AS CMN_ENG, '최대 표시 건수' AS RMRK, '20' AS SORT_SEQ FROM DUAL UNION ALL
  SELECT '372', '02', '7',  'UrgentPeriodDays', '긴급심사 표기기간(일)', '7'  FROM DUAL UNION ALL
  SELECT '372', '03', '30', 'NormalPeriodDays', '일반심사 표기기간(일)', '30' FROM DUAL UNION ALL
  SELECT '372', '04', '생성일', 'RCP', '표기기준(생성일/처리일)', '1' FROM DUAL
) S
ON (T.AI_INPT_GRP_CD = S.GRP_CD AND T.AI_INPT_CMN_CD = S.CMN_CD)
WHEN MATCHED THEN
  UPDATE SET
    T.AI_INPT_CMN_CD_NM = S.CMN_NM,
    T.AI_INPT_CMN_CD_ENG_NM = S.CMN_ENG,
    T.AI_INPT_RMRK_TXT = S.RMRK,
    T.AI_INPT_INTF_ITM_NM = S.CMN_NM,
    T.AI_INPT_SORT_SEQ = S.SORT_SEQ,
    T.AI_INPT_CMN_USG_YN = 'Y',
    T.LST_DB_CHG_ID = 'SYSTEM',
    T.LST_DB_CHG_DTM = '20260817160000'
WHEN NOT MATCHED THEN
  INSERT (AI_INPT_GRP_CD, AI_INPT_CMN_CD, AI_INPT_CMN_CD_NM, AI_INPT_CMN_CD_ENG_NM, AI_INPT_CMN_CD_STA_DTM, AI_INPT_CMN_CD_END_DTM, AI_INPT_CMN_USG_YN, AI_INPT_RMRK_TXT, AI_INPT_INTF_ITM_NM, AI_INPT_SORT_SEQ, TRN_LOG_SRNO, LST_DB_CHG_ID, LST_DB_CHG_DTM)
  VALUES (S.GRP_CD, S.CMN_CD, S.CMN_NM, S.CMN_ENG, '20200101000000', '99991231235959', 'Y', S.RMRK, S.CMN_NM, S.SORT_SEQ,
          '43' || S.CMN_CD, 'SYSTEM', '20260817160000');

COMMIT;

-- 표기기준을 처리일로 변경하려면:
-- UPDATE CSPD112TI SET AI_INPT_CMN_CD_NM='처리일', AI_INPT_CMN_CD_ENG_NM='CHG', LST_DB_CHG_DTM='20260817160000'
--  WHERE AI_INPT_GRP_CD='372' AND AI_INPT_CMN_CD='04';
